// SPDX-License-Identifier: MIT
// This file was autogenerated by scripts/codegen/gen_kernels.py; DO NOT EDIT.

#ifndef MARMOT_CPU_BYTECODE_TABLES_GEN_H
#define MARMOT_CPU_BYTECODE_TABLES_GEN_H

#include <stdint.h>

#define MARMOT_CPU_BC_OP_COUNT 1278
#define MARMOT_CPU_BC_OP_INVALID UINT16_MAX

#endif // MARMOT_CPU_BYTECODE_TABLES_GEN_H
