// SPDX-License-Identifier: MIT
// This file was autogenerated by scripts/codegen/gen_kernels.py; DO NOT EDIT.
// Matmul dispatch: dense, quantized, and QKV operations

#include "marmot/device.h"
#include "marmot/error.h"
#include "marmot/matmul_types.h"
#include "marmot/ops_types.h"
#include "marmot/tensor.h"

#include <stdint.h>
#include <stdlib.h>

#include "cpu_backend_internal.h"
#include "graph/kernel_dispatch_args.gen.h"
#include "ops/matmul/matmul_kernels.h"

// Forward declarations for QKV dispatch (per-dtype and per-quant-kind)
marmot_error_t cpu_matmul_qkv_f16(const void *device_ctx, const marmot_matmul_qkv_desc_t *desc);
marmot_error_t cpu_matmul_qkv_f32(const void *device_ctx, const marmot_matmul_qkv_desc_t *desc);
marmot_error_t cpu_matmul_qkv_bf16(const void *device_ctx, const marmot_matmul_qkv_desc_t *desc);
marmot_error_t cpu_matmul_qkv_q2_k(const void *device_ctx, const marmot_matmul_qkv_desc_t *desc);
marmot_error_t cpu_matmul_qkv_q3_k(const void *device_ctx, const marmot_matmul_qkv_desc_t *desc);
marmot_error_t cpu_matmul_qkv_q4_k(const void *device_ctx, const marmot_matmul_qkv_desc_t *desc);
marmot_error_t cpu_matmul_qkv_q5_k(const void *device_ctx, const marmot_matmul_qkv_desc_t *desc);
marmot_error_t cpu_matmul_qkv_q6_k(const void *device_ctx, const marmot_matmul_qkv_desc_t *desc);
marmot_error_t cpu_matmul_qkv_q8_0(const void *device_ctx, const marmot_matmul_qkv_desc_t *desc);
marmot_error_t cpu_matmul_qkv_q8_k(const void *device_ctx, const marmot_matmul_qkv_desc_t *desc);

// QKV dispatch helper macro - typed entrypoint
#define DEFINE_CPU_DISPATCH_QKV_TYPED(suffix)                                                                          \
    static marmot_error_t marmot_cpu_dispatch_qkv_##suffix##_typed(                                                    \
        const void *device_ctx, const marmot_kernel_args_qkv_t *decoded                                                \
    ) {                                                                                                                \
        if (decoded == nullptr) {                                                                                      \
            marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args not provided");                                  \
            return MARMOT_ERROR_INVALID_ARGUMENT;                                                                      \
        }                                                                                                              \
        if (decoded->ctx == nullptr || decoded->input == nullptr || decoded->wq == nullptr ||                          \
            decoded->wk == nullptr || decoded->wv == nullptr || decoded->out_q == nullptr ||                           \
            decoded->out_k == nullptr || decoded->out_v == nullptr) {                                                  \
            marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args missing tensors");                               \
            return MARMOT_ERROR_INVALID_ARGUMENT;                                                                      \
        }                                                                                                              \
        marmot_matmul_qkv_desc_t desc = marmot_matmul_qkv_desc_default();                                              \
        desc.input = decoded->input;                                                                                   \
        desc.layout = MARMOT_QKV_LAYOUT_SEPARATE;                                                                      \
        desc.separate.wq = decoded->wq;                                                                                \
        desc.separate.wk = decoded->wk;                                                                                \
        desc.separate.wv = decoded->wv;                                                                                \
        desc.separate.bq = decoded->bq;                                                                                \
        desc.separate.bk = decoded->bk;                                                                                \
        desc.separate.bv = decoded->bv;                                                                                \
        desc.epilogue = decoded->epilogue;                                                                             \
        desc.rope_params = decoded->rope_params;                                                                       \
        desc.out_q = decoded->out_q;                                                                                   \
        desc.out_k = decoded->out_k;                                                                                   \
        desc.out_v = decoded->out_v;                                                                                   \
        return cpu_matmul_qkv_##suffix(device_ctx, &desc);                                                             \
    }

// Generate per-dtype dispatch helpers for dense QKV
DEFINE_CPU_DISPATCH_QKV_TYPED(f16)
DEFINE_CPU_DISPATCH_QKV_TYPED(f32)
DEFINE_CPU_DISPATCH_QKV_TYPED(bf16)

// Generate per-quant-kind dispatch helpers for quantized QKV
DEFINE_CPU_DISPATCH_QKV_TYPED(q2_k)
DEFINE_CPU_DISPATCH_QKV_TYPED(q3_k)
DEFINE_CPU_DISPATCH_QKV_TYPED(q4_k)
DEFINE_CPU_DISPATCH_QKV_TYPED(q5_k)
DEFINE_CPU_DISPATCH_QKV_TYPED(q6_k)
DEFINE_CPU_DISPATCH_QKV_TYPED(q8_0)
DEFINE_CPU_DISPATCH_QKV_TYPED(q8_k)
#undef DEFINE_CPU_DISPATCH_QKV_TYPED

// ============================================================================
// Dense Matmul Kernel Implementations
// ============================================================================
// matmul_f16_accelerate_nt: dense matmul (NT)
#if MARMOT_ENABLE_ACCELERATE
marmot_error_t
marmot_cpu_matmul_f16_accelerate_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[0];
    marmot_error_t status = cpu_matmul_f16_accelerate(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// matmul_f32_accelerate_nt: dense matmul (NT)
#if MARMOT_ENABLE_ACCELERATE
marmot_error_t
marmot_cpu_matmul_f32_accelerate_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[0];
    marmot_error_t status = cpu_matmul_f32_accelerate(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// matmul_f64_accelerate_nt: dense matmul (NT)
#if MARMOT_ENABLE_ACCELERATE
marmot_error_t
marmot_cpu_matmul_f64_accelerate_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[0];
    marmot_error_t status = cpu_matmul_f64_accelerate(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// matmul_bf16_accelerate_nt: dense matmul (NT)
#if MARMOT_ENABLE_ACCELERATE
marmot_error_t
marmot_cpu_matmul_bf16_accelerate_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[0];
    marmot_error_t status = cpu_matmul_bf16_accelerate(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// matmul_fp8_e4m3_accelerate_nt: dense matmul (NT)
#if MARMOT_ENABLE_ACCELERATE
#if MARMOT_ENABLE_FP8
marmot_error_t
marmot_cpu_matmul_fp8_e4m3_accelerate_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[0];
    marmot_error_t status =
        cpu_matmul_fp8_e4m3_accelerate(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif
#endif

// matmul_fp8_e5m2_accelerate_nt: dense matmul (NT)
#if MARMOT_ENABLE_ACCELERATE
#if MARMOT_ENABLE_FP8
marmot_error_t
marmot_cpu_matmul_fp8_e5m2_accelerate_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[0];
    marmot_error_t status =
        cpu_matmul_fp8_e5m2_accelerate(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif
#endif

// matmul_f16_accelerate_nn: dense matmul (NN)
#if MARMOT_ENABLE_ACCELERATE
marmot_error_t
marmot_cpu_matmul_f16_accelerate_nn_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[1];
    marmot_error_t status = cpu_matmul_f16_accelerate_nn(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// matmul_f32_accelerate_nn: dense matmul (NN)
#if MARMOT_ENABLE_ACCELERATE
marmot_error_t
marmot_cpu_matmul_f32_accelerate_nn_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[1];
    marmot_error_t status = cpu_matmul_f32_accelerate_nn(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// matmul_f64_accelerate_nn: dense matmul (NN)
#if MARMOT_ENABLE_ACCELERATE
marmot_error_t
marmot_cpu_matmul_f64_accelerate_nn_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[1];
    marmot_error_t status = cpu_matmul_f64_accelerate_nn(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// matmul_bf16_accelerate_nn: dense matmul (NN)
#if MARMOT_ENABLE_ACCELERATE
marmot_error_t
marmot_cpu_matmul_bf16_accelerate_nn_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[1];
    marmot_error_t status = cpu_matmul_bf16_accelerate_nn(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// matmul_fp8_e4m3_accelerate_nn: dense matmul (NN)
#if MARMOT_ENABLE_ACCELERATE
#if MARMOT_ENABLE_FP8
marmot_error_t
marmot_cpu_matmul_fp8_e4m3_accelerate_nn_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[1];
    marmot_error_t status =
        cpu_matmul_fp8_e4m3_accelerate_nn(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif
#endif

// matmul_fp8_e5m2_accelerate_nn: dense matmul (NN)
#if MARMOT_ENABLE_ACCELERATE
#if MARMOT_ENABLE_FP8
marmot_error_t
marmot_cpu_matmul_fp8_e5m2_accelerate_nn_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[1];
    marmot_error_t status =
        cpu_matmul_fp8_e5m2_accelerate_nn(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif
#endif

// matmul_f16_avx2_nt: dense matmul (NT)
#if MARMOT_ENABLE_AVX2
marmot_error_t marmot_cpu_matmul_f16_avx2_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[0];
    marmot_error_t status = cpu_matmul_f16_avx2(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// matmul_bf16_avx2_nt: dense matmul (NT)
#if MARMOT_ENABLE_AVX2
marmot_error_t marmot_cpu_matmul_bf16_avx2_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[0];
    marmot_error_t status = cpu_matmul_bf16_avx2(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// matmul_f16_neon_nt: dense matmul (NT)
#if MARMOT_ENABLE_NEON
marmot_error_t marmot_cpu_matmul_f16_neon_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[0];
    marmot_error_t status =
        cpu_matmul_f16_neon_blocked_nt(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// matmul_f32_neon_nt: dense matmul (NT)
#if MARMOT_ENABLE_NEON
marmot_error_t marmot_cpu_matmul_f32_neon_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[0];
    marmot_error_t status =
        cpu_matmul_f32_neon_blocked_nt(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// matmul_f64_neon_nt: dense matmul (NT)
#if MARMOT_ENABLE_NEON
marmot_error_t marmot_cpu_matmul_f64_neon_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[0];
    marmot_error_t status =
        cpu_matmul_f64_neon_blocked_nt(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// matmul_bf16_neon_nt: dense matmul (NT)
#if MARMOT_ENABLE_NEON
marmot_error_t marmot_cpu_matmul_bf16_neon_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[0];
    marmot_error_t status =
        cpu_matmul_bf16_neon_blocked_nt(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// matmul_f16_neon_nn: dense matmul (NN)
#if MARMOT_ENABLE_NEON
marmot_error_t marmot_cpu_matmul_f16_neon_nn_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[1];
    marmot_error_t status =
        cpu_matmul_f16_neon_blocked_nn(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// matmul_f32_neon_nn: dense matmul (NN)
#if MARMOT_ENABLE_NEON
marmot_error_t marmot_cpu_matmul_f32_neon_nn_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[1];
    marmot_error_t status =
        cpu_matmul_f32_neon_blocked_nn(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// matmul_f64_neon_nn: dense matmul (NN)
#if MARMOT_ENABLE_NEON
marmot_error_t marmot_cpu_matmul_f64_neon_nn_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[1];
    marmot_error_t status =
        cpu_matmul_f64_neon_blocked_nn(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// matmul_bf16_neon_nn: dense matmul (NN)
#if MARMOT_ENABLE_NEON
marmot_error_t marmot_cpu_matmul_bf16_neon_nn_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[1];
    marmot_error_t status =
        cpu_matmul_bf16_neon_blocked_nn(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// matmul_f16_scalar_nt: dense matmul (NT)
marmot_error_t marmot_cpu_matmul_f16_scalar_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[0];
    marmot_error_t status = cpu_matmul_f16_scalar(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}

// matmul_f32_scalar_nt: dense matmul (NT)
marmot_error_t marmot_cpu_matmul_f32_scalar_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[0];
    marmot_error_t status = cpu_matmul_f32_scalar(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}

// matmul_f64_scalar_nt: dense matmul (NT)
marmot_error_t marmot_cpu_matmul_f64_scalar_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[0];
    marmot_error_t status = cpu_matmul_f64_scalar(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}

// matmul_bf16_scalar_nt: dense matmul (NT)
marmot_error_t marmot_cpu_matmul_bf16_scalar_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[0];
    marmot_error_t status = cpu_matmul_bf16_scalar(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}

// matmul_fp8_e4m3_scalar_nt: dense matmul (NT)
#if MARMOT_ENABLE_FP8
marmot_error_t
marmot_cpu_matmul_fp8_e4m3_scalar_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[0];
    marmot_error_t status = cpu_matmul_fp8_e4m3_scalar(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// matmul_fp8_e5m2_scalar_nt: dense matmul (NT)
#if MARMOT_ENABLE_FP8
marmot_error_t
marmot_cpu_matmul_fp8_e5m2_scalar_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[0];
    marmot_error_t status = cpu_matmul_fp8_e5m2_scalar(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// matmul_f16_scalar_nn: dense matmul (NN)
marmot_error_t marmot_cpu_matmul_f16_scalar_nn_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[1];
    marmot_error_t status = cpu_matmul_f16_scalar_nn(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}

// matmul_f32_scalar_nn: dense matmul (NN)
marmot_error_t marmot_cpu_matmul_f32_scalar_nn_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[1];
    marmot_error_t status = cpu_matmul_f32_scalar_nn(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}

// matmul_f64_scalar_nn: dense matmul (NN)
marmot_error_t marmot_cpu_matmul_f64_scalar_nn_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[1];
    marmot_error_t status = cpu_matmul_f64_scalar_nn(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}

// matmul_bf16_scalar_nn: dense matmul (NN)
marmot_error_t marmot_cpu_matmul_bf16_scalar_nn_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[1];
    marmot_error_t status = cpu_matmul_bf16_scalar_nn(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}

// matmul_fp8_e4m3_scalar_nn: dense matmul (NN)
#if MARMOT_ENABLE_FP8
marmot_error_t
marmot_cpu_matmul_fp8_e4m3_scalar_nn_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[1];
    marmot_error_t status = cpu_matmul_fp8_e4m3_scalar_nn(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// matmul_fp8_e5m2_scalar_nn: dense matmul (NN)
#if MARMOT_ENABLE_FP8
marmot_error_t
marmot_cpu_matmul_fp8_e5m2_scalar_nn_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const size_t N = args->input->shape.shape[0];
    const size_t K = args->input->shape.shape[1];
    const size_t M = args->weight->shape.shape[1];
    marmot_error_t status = cpu_matmul_fp8_e5m2_scalar_nn(device_ctx, args->input, args->weight, N, K, M, args->output);
    if (status != MARMOT_SUCCESS) {
        return status;
    }
    return cpu_matmul_apply_epilogue(device_ctx, args->output, args->epilogue);
}
#endif

// ============================================================================
// Quantized Matmul Kernel Implementations
// ============================================================================
// matmul_q4_0_scalar_nt: quantized matmul (q4_0)
marmot_error_t marmot_cpu_matmul_q4_0_scalar_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_matmul_quantized_q4_0(device_ctx, args->input, args->weight, args->epilogue, args->output);
}

// matmul_q4_1_scalar_nt: quantized matmul (q4_1)
marmot_error_t marmot_cpu_matmul_q4_1_scalar_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_matmul_quantized_q4_1(device_ctx, args->input, args->weight, args->epilogue, args->output);
}

// matmul_q5_0_scalar_nt: quantized matmul (q5_0)
marmot_error_t marmot_cpu_matmul_q5_0_scalar_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_matmul_quantized_q5_0(device_ctx, args->input, args->weight, args->epilogue, args->output);
}

// matmul_q5_1_scalar_nt: quantized matmul (q5_1)
marmot_error_t marmot_cpu_matmul_q5_1_scalar_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_matmul_quantized_q5_1(device_ctx, args->input, args->weight, args->epilogue, args->output);
}

// matmul_q8_0_scalar_nt: quantized matmul (q8_0)
marmot_error_t marmot_cpu_matmul_q8_0_scalar_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_matmul_quantized_q8_0(device_ctx, args->input, args->weight, args->epilogue, args->output);
}

// matmul_q8_1_scalar_nt: quantized matmul (q8_1)
marmot_error_t marmot_cpu_matmul_q8_1_scalar_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_matmul_quantized_q8_1(device_ctx, args->input, args->weight, args->epilogue, args->output);
}

// matmul_q2_k_scalar_nt: quantized matmul (q2_k)
marmot_error_t marmot_cpu_matmul_q2_k_scalar_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_matmul_quantized_q2_k(device_ctx, args->input, args->weight, args->epilogue, args->output);
}

// matmul_q3_k_scalar_nt: quantized matmul (q3_k)
marmot_error_t marmot_cpu_matmul_q3_k_scalar_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_matmul_quantized_q3_k(device_ctx, args->input, args->weight, args->epilogue, args->output);
}

// matmul_q4_k_scalar_nt: quantized matmul (q4_k)
marmot_error_t marmot_cpu_matmul_q4_k_scalar_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_matmul_quantized_q4_k(device_ctx, args->input, args->weight, args->epilogue, args->output);
}

// matmul_q5_k_scalar_nt: quantized matmul (q5_k)
marmot_error_t marmot_cpu_matmul_q5_k_scalar_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_matmul_quantized_q5_k(device_ctx, args->input, args->weight, args->epilogue, args->output);
}

// matmul_q6_k_scalar_nt: quantized matmul (q6_k)
marmot_error_t marmot_cpu_matmul_q6_k_scalar_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_matmul_quantized_q6_k(device_ctx, args->input, args->weight, args->epilogue, args->output);
}

// matmul_q8_k_scalar_nt: quantized matmul (q8_k)
marmot_error_t marmot_cpu_matmul_q8_k_scalar_nt_exec(const void *device_ctx, const marmot_kernel_args_matmul_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    if (args->ctx == nullptr || args->input == nullptr || args->weight == nullptr || args->output == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Matmul args missing tensors");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_matmul_quantized_q8_k(device_ctx, args->input, args->weight, args->epilogue, args->output);
}

// ============================================================================
// QKV Matmul Kernel Implementations
// ============================================================================
// qkv_rope_f16: QKV matmul (dense f16)
marmot_error_t marmot_cpu_qkv_rope_f16_exec(const void *device_ctx, const marmot_kernel_args_qkv_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return marmot_cpu_dispatch_qkv_f16_typed(device_ctx, args);
}

// qkv_rope_f32: QKV matmul (dense f32)
marmot_error_t marmot_cpu_qkv_rope_f32_exec(const void *device_ctx, const marmot_kernel_args_qkv_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return marmot_cpu_dispatch_qkv_f32_typed(device_ctx, args);
}

// qkv_rope_bf16: QKV matmul (dense bf16)
marmot_error_t marmot_cpu_qkv_rope_bf16_exec(const void *device_ctx, const marmot_kernel_args_qkv_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return marmot_cpu_dispatch_qkv_bf16_typed(device_ctx, args);
}

// qkv_rope_q4_k_f16: QKV matmul (quantized q4_k)
marmot_error_t marmot_cpu_qkv_rope_q4_k_f16_exec(const void *device_ctx, const marmot_kernel_args_qkv_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return marmot_cpu_dispatch_qkv_q4_k_typed(device_ctx, args);
}

// qkv_rope_q2_k_f16: QKV matmul (quantized q2_k)
marmot_error_t marmot_cpu_qkv_rope_q2_k_f16_exec(const void *device_ctx, const marmot_kernel_args_qkv_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return marmot_cpu_dispatch_qkv_q2_k_typed(device_ctx, args);
}

// qkv_rope_q3_k_f16: QKV matmul (quantized q3_k)
marmot_error_t marmot_cpu_qkv_rope_q3_k_f16_exec(const void *device_ctx, const marmot_kernel_args_qkv_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return marmot_cpu_dispatch_qkv_q3_k_typed(device_ctx, args);
}

// qkv_rope_q5_k_f16: QKV matmul (quantized q5_k)
marmot_error_t marmot_cpu_qkv_rope_q5_k_f16_exec(const void *device_ctx, const marmot_kernel_args_qkv_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return marmot_cpu_dispatch_qkv_q5_k_typed(device_ctx, args);
}

// qkv_rope_q6_k_f16: QKV matmul (quantized q6_k)
marmot_error_t marmot_cpu_qkv_rope_q6_k_f16_exec(const void *device_ctx, const marmot_kernel_args_qkv_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return marmot_cpu_dispatch_qkv_q6_k_typed(device_ctx, args);
}

// qkv_rope_q8_0_f16: QKV matmul (quantized q8_0)
marmot_error_t marmot_cpu_qkv_rope_q8_0_f16_exec(const void *device_ctx, const marmot_kernel_args_qkv_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return marmot_cpu_dispatch_qkv_q8_0_typed(device_ctx, args);
}

// qkv_rope_q8_k_f16: QKV matmul (quantized q8_k)
marmot_error_t marmot_cpu_qkv_rope_q8_k_f16_exec(const void *device_ctx, const marmot_kernel_args_qkv_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return marmot_cpu_dispatch_qkv_q8_k_typed(device_ctx, args);
}

// qkv_projection_f16: QKV matmul (dense f16)
marmot_error_t marmot_cpu_qkv_projection_f16_exec(const void *device_ctx, const marmot_kernel_args_qkv_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return marmot_cpu_dispatch_qkv_f16_typed(device_ctx, args);
}

// qkv_projection_f32: QKV matmul (dense f32)
marmot_error_t marmot_cpu_qkv_projection_f32_exec(const void *device_ctx, const marmot_kernel_args_qkv_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return marmot_cpu_dispatch_qkv_f32_typed(device_ctx, args);
}

// qkv_projection_bf16: QKV matmul (dense bf16)
marmot_error_t marmot_cpu_qkv_projection_bf16_exec(const void *device_ctx, const marmot_kernel_args_qkv_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return marmot_cpu_dispatch_qkv_bf16_typed(device_ctx, args);
}

// qkv_projection_q4_k_f16: QKV matmul (quantized q4_k)
marmot_error_t marmot_cpu_qkv_projection_q4_k_f16_exec(const void *device_ctx, const marmot_kernel_args_qkv_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return marmot_cpu_dispatch_qkv_q4_k_typed(device_ctx, args);
}

// qkv_projection_q2_k_f16: QKV matmul (quantized q2_k)
marmot_error_t marmot_cpu_qkv_projection_q2_k_f16_exec(const void *device_ctx, const marmot_kernel_args_qkv_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return marmot_cpu_dispatch_qkv_q2_k_typed(device_ctx, args);
}

// qkv_projection_q3_k_f16: QKV matmul (quantized q3_k)
marmot_error_t marmot_cpu_qkv_projection_q3_k_f16_exec(const void *device_ctx, const marmot_kernel_args_qkv_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return marmot_cpu_dispatch_qkv_q3_k_typed(device_ctx, args);
}

// qkv_projection_q5_k_f16: QKV matmul (quantized q5_k)
marmot_error_t marmot_cpu_qkv_projection_q5_k_f16_exec(const void *device_ctx, const marmot_kernel_args_qkv_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return marmot_cpu_dispatch_qkv_q5_k_typed(device_ctx, args);
}

// qkv_projection_q6_k_f16: QKV matmul (quantized q6_k)
marmot_error_t marmot_cpu_qkv_projection_q6_k_f16_exec(const void *device_ctx, const marmot_kernel_args_qkv_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return marmot_cpu_dispatch_qkv_q6_k_typed(device_ctx, args);
}

// qkv_projection_q8_0_f16: QKV matmul (quantized q8_0)
marmot_error_t marmot_cpu_qkv_projection_q8_0_f16_exec(const void *device_ctx, const marmot_kernel_args_qkv_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return marmot_cpu_dispatch_qkv_q8_0_typed(device_ctx, args);
}

// qkv_projection_q8_k_f16: QKV matmul (quantized q8_k)
marmot_error_t marmot_cpu_qkv_projection_q8_k_f16_exec(const void *device_ctx, const marmot_kernel_args_qkv_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "QKV args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return marmot_cpu_dispatch_qkv_q8_k_typed(device_ctx, args);
}
