// SPDX-License-Identifier: MIT
// This file was autogenerated by scripts/codegen/gen_kernels.py; DO NOT EDIT.
// Miscellaneous dispatch: quantization, conversion, embedding, tensor ops, vec_dot

#include "marmot/device.h"
#include "marmot/error.h"
#include "marmot/tensor.h"

#include <stdint.h>
#include <stdlib.h>

#include "cpu_backend_internal.h"
#include "graph/kernel_dispatch_args.gen.h"

// ============================================================================
// Quantization Implementations
// ============================================================================
// quantize_generic_scalar: quantization op quantize
marmot_error_t
marmot_cpu_quantize_generic_scalar_exec(const void *device_ctx, const marmot_kernel_args_quantize_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const marmot_quant_kind_traits_t *traits = marmot_get_quant_kind_traits(args->kind);
    marmot_quant_layout_t layout = traits != nullptr ? args->layout : MARMOT_QUANT_LAYOUT_GENERIC;
    if (args->kind == MARMOT_QUANT_KIND_GENERIC) {
        return cpu_quantize(device_ctx, args->input, args->quant_params, args->output);
    }
    return cpu_quantize_with_kind(device_ctx, args->kind, layout, args->input, args->output);
}

// dequantize_generic_scalar: quantization op dequantize
marmot_error_t
marmot_cpu_dequantize_generic_scalar_exec(const void *device_ctx, const marmot_kernel_args_dequantize_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const marmot_quant_kind_traits_t *traits = marmot_get_quant_kind_traits(args->kind);
    marmot_quant_layout_t layout = traits != nullptr ? args->layout : MARMOT_QUANT_LAYOUT_GENERIC;
    if (args->kind == MARMOT_QUANT_KIND_GENERIC) {
        return cpu_dequantize(device_ctx, args->input, args->output);
    }
    return cpu_dequantize_with_kind(device_ctx, args->kind, layout, args->input, args->output);
}

// compute_quant_params_scalar: quantization op compute_quant_params
marmot_error_t
marmot_cpu_compute_quant_params_scalar_exec(const void *device_ctx, const marmot_kernel_args_compute_qparams_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_compute_quant_params(device_ctx, args->tensor, args->target_dtype, args->block_size, args->out_params);
}

// quantize_block_scalar: quantization op quantize
marmot_error_t
marmot_cpu_quantize_block_scalar_exec(const void *device_ctx, const marmot_kernel_args_quantize_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const marmot_quant_kind_traits_t *traits = marmot_get_quant_kind_traits(args->kind);
    marmot_quant_layout_t layout = traits != nullptr ? args->layout : MARMOT_QUANT_LAYOUT_GENERIC;
    if (args->kind == MARMOT_QUANT_KIND_GENERIC) {
        return cpu_quantize(device_ctx, args->input, args->quant_params, args->output);
    }
    return cpu_quantize_with_kind(device_ctx, args->kind, layout, args->input, args->output);
}

// dequantize_block_scalar: quantization op dequantize
marmot_error_t
marmot_cpu_dequantize_block_scalar_exec(const void *device_ctx, const marmot_kernel_args_dequantize_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    const marmot_quant_kind_traits_t *traits = marmot_get_quant_kind_traits(args->kind);
    marmot_quant_layout_t layout = traits != nullptr ? args->layout : MARMOT_QUANT_LAYOUT_GENERIC;
    if (args->kind == MARMOT_QUANT_KIND_GENERIC) {
        return cpu_dequantize(device_ctx, args->input, args->output);
    }
    return cpu_dequantize_with_kind(device_ctx, args->kind, layout, args->input, args->output);
}

// ============================================================================
// Conversion Implementations
// ============================================================================
// convert_generic: dtype conversion
marmot_error_t marmot_cpu_convert_generic_exec(const void *device_ctx, const marmot_kernel_args_convert_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_convert_dispatch(device_ctx, args->dst_dtype, args->dst, args->src_dtype, args->src, args->n);
}

// convert_fp8_generic: dtype conversion
#if MARMOT_ENABLE_FP8
marmot_error_t marmot_cpu_convert_fp8_generic_exec(const void *device_ctx, const marmot_kernel_args_convert_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_convert_dispatch(device_ctx, args->dst_dtype, args->dst, args->src_dtype, args->src, args->n);
}
#endif

// ============================================================================
// Embedding Implementations
// ============================================================================
// embedding_float: embedding gather
marmot_error_t marmot_cpu_embedding_float_exec(const void *device_ctx, const marmot_kernel_args_embedding_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    marmot_embedding_gather_desc_t desc = {
        .weights = args->weights,
        .token_ids = args->token_ids,
        .out = args->out,
        .dtype_out = args->dtype_out,
        .scale = args->scale,
        .padding_id = args->padding_id,
        .bounds_check = args->bounds_check,
        .prefer_gpu_private = args->prefer_gpu_private ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
        .allow_quant_decode_on_the_fly =
            args->allow_quant_decode_on_the_fly ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
    };
    return cpu_embedding_gather(device_ctx, &desc);
}

// embedding_q4_0: embedding gather
marmot_error_t marmot_cpu_embedding_q4_0_exec(const void *device_ctx, const marmot_kernel_args_embedding_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    marmot_embedding_gather_desc_t desc = {
        .weights = args->weights,
        .token_ids = args->token_ids,
        .out = args->out,
        .dtype_out = args->dtype_out,
        .scale = args->scale,
        .padding_id = args->padding_id,
        .bounds_check = args->bounds_check,
        .prefer_gpu_private = args->prefer_gpu_private ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
        .allow_quant_decode_on_the_fly =
            args->allow_quant_decode_on_the_fly ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
    };
    return cpu_embedding_gather(device_ctx, &desc);
}

// embedding_q4_1: embedding gather
marmot_error_t marmot_cpu_embedding_q4_1_exec(const void *device_ctx, const marmot_kernel_args_embedding_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    marmot_embedding_gather_desc_t desc = {
        .weights = args->weights,
        .token_ids = args->token_ids,
        .out = args->out,
        .dtype_out = args->dtype_out,
        .scale = args->scale,
        .padding_id = args->padding_id,
        .bounds_check = args->bounds_check,
        .prefer_gpu_private = args->prefer_gpu_private ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
        .allow_quant_decode_on_the_fly =
            args->allow_quant_decode_on_the_fly ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
    };
    return cpu_embedding_gather(device_ctx, &desc);
}

// embedding_q5_0: embedding gather
marmot_error_t marmot_cpu_embedding_q5_0_exec(const void *device_ctx, const marmot_kernel_args_embedding_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    marmot_embedding_gather_desc_t desc = {
        .weights = args->weights,
        .token_ids = args->token_ids,
        .out = args->out,
        .dtype_out = args->dtype_out,
        .scale = args->scale,
        .padding_id = args->padding_id,
        .bounds_check = args->bounds_check,
        .prefer_gpu_private = args->prefer_gpu_private ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
        .allow_quant_decode_on_the_fly =
            args->allow_quant_decode_on_the_fly ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
    };
    return cpu_embedding_gather(device_ctx, &desc);
}

// embedding_q5_1: embedding gather
marmot_error_t marmot_cpu_embedding_q5_1_exec(const void *device_ctx, const marmot_kernel_args_embedding_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    marmot_embedding_gather_desc_t desc = {
        .weights = args->weights,
        .token_ids = args->token_ids,
        .out = args->out,
        .dtype_out = args->dtype_out,
        .scale = args->scale,
        .padding_id = args->padding_id,
        .bounds_check = args->bounds_check,
        .prefer_gpu_private = args->prefer_gpu_private ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
        .allow_quant_decode_on_the_fly =
            args->allow_quant_decode_on_the_fly ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
    };
    return cpu_embedding_gather(device_ctx, &desc);
}

// embedding_q8_0: embedding gather
marmot_error_t marmot_cpu_embedding_q8_0_exec(const void *device_ctx, const marmot_kernel_args_embedding_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    marmot_embedding_gather_desc_t desc = {
        .weights = args->weights,
        .token_ids = args->token_ids,
        .out = args->out,
        .dtype_out = args->dtype_out,
        .scale = args->scale,
        .padding_id = args->padding_id,
        .bounds_check = args->bounds_check,
        .prefer_gpu_private = args->prefer_gpu_private ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
        .allow_quant_decode_on_the_fly =
            args->allow_quant_decode_on_the_fly ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
    };
    return cpu_embedding_gather(device_ctx, &desc);
}

// embedding_q2_k: embedding gather
marmot_error_t marmot_cpu_embedding_q2_k_exec(const void *device_ctx, const marmot_kernel_args_embedding_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    marmot_embedding_gather_desc_t desc = {
        .weights = args->weights,
        .token_ids = args->token_ids,
        .out = args->out,
        .dtype_out = args->dtype_out,
        .scale = args->scale,
        .padding_id = args->padding_id,
        .bounds_check = args->bounds_check,
        .prefer_gpu_private = args->prefer_gpu_private ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
        .allow_quant_decode_on_the_fly =
            args->allow_quant_decode_on_the_fly ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
    };
    return cpu_embedding_gather(device_ctx, &desc);
}

// embedding_q3_k: embedding gather
marmot_error_t marmot_cpu_embedding_q3_k_exec(const void *device_ctx, const marmot_kernel_args_embedding_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    marmot_embedding_gather_desc_t desc = {
        .weights = args->weights,
        .token_ids = args->token_ids,
        .out = args->out,
        .dtype_out = args->dtype_out,
        .scale = args->scale,
        .padding_id = args->padding_id,
        .bounds_check = args->bounds_check,
        .prefer_gpu_private = args->prefer_gpu_private ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
        .allow_quant_decode_on_the_fly =
            args->allow_quant_decode_on_the_fly ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
    };
    return cpu_embedding_gather(device_ctx, &desc);
}

// embedding_q4_k: embedding gather
marmot_error_t marmot_cpu_embedding_q4_k_exec(const void *device_ctx, const marmot_kernel_args_embedding_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    marmot_embedding_gather_desc_t desc = {
        .weights = args->weights,
        .token_ids = args->token_ids,
        .out = args->out,
        .dtype_out = args->dtype_out,
        .scale = args->scale,
        .padding_id = args->padding_id,
        .bounds_check = args->bounds_check,
        .prefer_gpu_private = args->prefer_gpu_private ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
        .allow_quant_decode_on_the_fly =
            args->allow_quant_decode_on_the_fly ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
    };
    return cpu_embedding_gather(device_ctx, &desc);
}

// embedding_q5_k: embedding gather
marmot_error_t marmot_cpu_embedding_q5_k_exec(const void *device_ctx, const marmot_kernel_args_embedding_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    marmot_embedding_gather_desc_t desc = {
        .weights = args->weights,
        .token_ids = args->token_ids,
        .out = args->out,
        .dtype_out = args->dtype_out,
        .scale = args->scale,
        .padding_id = args->padding_id,
        .bounds_check = args->bounds_check,
        .prefer_gpu_private = args->prefer_gpu_private ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
        .allow_quant_decode_on_the_fly =
            args->allow_quant_decode_on_the_fly ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
    };
    return cpu_embedding_gather(device_ctx, &desc);
}

// embedding_q6_k: embedding gather
marmot_error_t marmot_cpu_embedding_q6_k_exec(const void *device_ctx, const marmot_kernel_args_embedding_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    marmot_embedding_gather_desc_t desc = {
        .weights = args->weights,
        .token_ids = args->token_ids,
        .out = args->out,
        .dtype_out = args->dtype_out,
        .scale = args->scale,
        .padding_id = args->padding_id,
        .bounds_check = args->bounds_check,
        .prefer_gpu_private = args->prefer_gpu_private ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
        .allow_quant_decode_on_the_fly =
            args->allow_quant_decode_on_the_fly ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
    };
    return cpu_embedding_gather(device_ctx, &desc);
}

// embedding_q8_k: embedding gather
marmot_error_t marmot_cpu_embedding_q8_k_exec(const void *device_ctx, const marmot_kernel_args_embedding_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    marmot_embedding_gather_desc_t desc = {
        .weights = args->weights,
        .token_ids = args->token_ids,
        .out = args->out,
        .dtype_out = args->dtype_out,
        .scale = args->scale,
        .padding_id = args->padding_id,
        .bounds_check = args->bounds_check,
        .prefer_gpu_private = args->prefer_gpu_private ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
        .allow_quant_decode_on_the_fly =
            args->allow_quant_decode_on_the_fly ? MARMOT_PREFERENCE_ENABLE : MARMOT_PREFERENCE_DISABLE,
    };
    return cpu_embedding_gather(device_ctx, &desc);
}

// ============================================================================
// Vec Dot Implementations
// ============================================================================
// vec_dot_q4_0_q8_0: vector dot product
marmot_error_t marmot_cpu_vec_dot_q4_0_q8_0_exec(const void *device_ctx, const marmot_kernel_args_vec_dot_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_vec_dot(device_ctx, args->desc, args->result);
}

// vec_dot_q4_1_q8_0: vector dot product
marmot_error_t marmot_cpu_vec_dot_q4_1_q8_0_exec(const void *device_ctx, const marmot_kernel_args_vec_dot_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_vec_dot(device_ctx, args->desc, args->result);
}

// vec_dot_q5_0_q8_0: vector dot product
marmot_error_t marmot_cpu_vec_dot_q5_0_q8_0_exec(const void *device_ctx, const marmot_kernel_args_vec_dot_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_vec_dot(device_ctx, args->desc, args->result);
}

// vec_dot_q5_1_q8_0: vector dot product
marmot_error_t marmot_cpu_vec_dot_q5_1_q8_0_exec(const void *device_ctx, const marmot_kernel_args_vec_dot_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_vec_dot(device_ctx, args->desc, args->result);
}

// vec_dot_q8_0_q8_0: vector dot product
marmot_error_t marmot_cpu_vec_dot_q8_0_q8_0_exec(const void *device_ctx, const marmot_kernel_args_vec_dot_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_vec_dot(device_ctx, args->desc, args->result);
}

// vec_dot_q8_1_q8_0: vector dot product
marmot_error_t marmot_cpu_vec_dot_q8_1_q8_0_exec(const void *device_ctx, const marmot_kernel_args_vec_dot_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_vec_dot(device_ctx, args->desc, args->result);
}

// vec_dot_q2_k_q8_k: vector dot product
marmot_error_t marmot_cpu_vec_dot_q2_k_q8_k_exec(const void *device_ctx, const marmot_kernel_args_vec_dot_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_vec_dot(device_ctx, args->desc, args->result);
}

// vec_dot_q3_k_q8_k: vector dot product
marmot_error_t marmot_cpu_vec_dot_q3_k_q8_k_exec(const void *device_ctx, const marmot_kernel_args_vec_dot_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_vec_dot(device_ctx, args->desc, args->result);
}

// vec_dot_q4_k_q8_k: vector dot product
marmot_error_t marmot_cpu_vec_dot_q4_k_q8_k_exec(const void *device_ctx, const marmot_kernel_args_vec_dot_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_vec_dot(device_ctx, args->desc, args->result);
}

// vec_dot_q5_k_q8_k: vector dot product
marmot_error_t marmot_cpu_vec_dot_q5_k_q8_k_exec(const void *device_ctx, const marmot_kernel_args_vec_dot_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_vec_dot(device_ctx, args->desc, args->result);
}

// vec_dot_q6_k_q8_k: vector dot product
marmot_error_t marmot_cpu_vec_dot_q6_k_q8_k_exec(const void *device_ctx, const marmot_kernel_args_vec_dot_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_vec_dot(device_ctx, args->desc, args->result);
}

// vec_dot_q8_k_q8_k: vector dot product
marmot_error_t marmot_cpu_vec_dot_q8_k_q8_k_exec(const void *device_ctx, const marmot_kernel_args_vec_dot_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_vec_dot(device_ctx, args->desc, args->result);
}

// ============================================================================
// Tensor Ops Implementations
// ============================================================================
// tensor_contiguous_generic: tensor layout op
marmot_error_t
marmot_cpu_tensor_contiguous_generic_exec(const void *device_ctx, const marmot_kernel_args_contiguous_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_contiguous(device_ctx, args->input, args->output);
}

// tensor_contiguous_fp8: tensor layout op
#if MARMOT_ENABLE_FP8
marmot_error_t
marmot_cpu_tensor_contiguous_fp8_exec(const void *device_ctx, const marmot_kernel_args_contiguous_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_contiguous(device_ctx, args->input, args->output);
}
#endif

// tensor_reshape_generic: tensor layout op
marmot_error_t
marmot_cpu_tensor_reshape_generic_exec(const void *device_ctx, const marmot_kernel_args_reshape_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reshape(device_ctx, args->input, args->output, args->new_shape, args->new_ndim);
}

// tensor_reshape_fp8: tensor layout op
#if MARMOT_ENABLE_FP8
marmot_error_t marmot_cpu_tensor_reshape_fp8_exec(const void *device_ctx, const marmot_kernel_args_reshape_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reshape(device_ctx, args->input, args->output, args->new_shape, args->new_ndim);
}
#endif

// tensor_transpose_generic: tensor layout op
marmot_error_t
marmot_cpu_tensor_transpose_generic_exec(const void *device_ctx, const marmot_kernel_args_transpose_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_transpose(device_ctx, args->input, args->output, args->perm);
}

// tensor_transpose_fp8: tensor layout op
#if MARMOT_ENABLE_FP8
marmot_error_t
marmot_cpu_tensor_transpose_fp8_exec(const void *device_ctx, const marmot_kernel_args_transpose_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_transpose(device_ctx, args->input, args->output, args->perm);
}
#endif

// tensor_concat_generic: tensor layout op
marmot_error_t marmot_cpu_tensor_concat_generic_exec(const void *device_ctx, const marmot_kernel_args_concat_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_concat(device_ctx, args->inputs, args->num_inputs, args->output, args->axis);
}

// tensor_concat_fp8: tensor layout op
#if MARMOT_ENABLE_FP8
marmot_error_t marmot_cpu_tensor_concat_fp8_exec(const void *device_ctx, const marmot_kernel_args_concat_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_concat(device_ctx, args->inputs, args->num_inputs, args->output, args->axis);
}
#endif

// tensor_slice_generic: tensor layout op
marmot_error_t marmot_cpu_tensor_slice_generic_exec(const void *device_ctx, const marmot_kernel_args_slice_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_slice(device_ctx, args->input, args->output, args->starts, args->sizes);
}

// tensor_slice_fp8: tensor layout op
#if MARMOT_ENABLE_FP8
marmot_error_t marmot_cpu_tensor_slice_fp8_exec(const void *device_ctx, const marmot_kernel_args_slice_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_slice(device_ctx, args->input, args->output, args->starts, args->sizes);
}
#endif

// tensor_view_generic: tensor layout op
marmot_error_t marmot_cpu_tensor_view_generic_exec(const void *device_ctx, const marmot_kernel_args_view_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_view(device_ctx, args->input, args->output, args->byte_offset);
}

// tensor_view_fp8: tensor layout op
#if MARMOT_ENABLE_FP8
marmot_error_t marmot_cpu_tensor_view_fp8_exec(const void *device_ctx, const marmot_kernel_args_view_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_view(device_ctx, args->input, args->output, args->byte_offset);
}
#endif

// tensor_gather_rows_generic: tensor layout op
marmot_error_t
marmot_cpu_tensor_gather_rows_generic_exec(const void *device_ctx, const marmot_kernel_args_gather_rows_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_gather_rows(device_ctx, args->input, args->indices, args->output);
}

// tensor_gather_rows_fp8: tensor layout op
#if MARMOT_ENABLE_FP8
marmot_error_t
marmot_cpu_tensor_gather_rows_fp8_exec(const void *device_ctx, const marmot_kernel_args_gather_rows_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_gather_rows(device_ctx, args->input, args->indices, args->output);
}
#endif

// tensor_scatter_u64_to_i32_generic: tensor layout op
marmot_error_t marmot_cpu_tensor_scatter_u64_to_i32_generic_exec(
    const void *device_ctx, const marmot_kernel_args_gather_rows_t *args
) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_scatter_u64_to_i32(device_ctx, args->input, args->indices, args->output);
}

// tensor_scatter_u64_to_i32_fp8: tensor layout op
#if MARMOT_ENABLE_FP8
marmot_error_t
marmot_cpu_tensor_scatter_u64_to_i32_fp8_exec(const void *device_ctx, const marmot_kernel_args_gather_rows_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_scatter_u64_to_i32(device_ctx, args->input, args->indices, args->output);
}
#endif
