// SPDX-License-Identifier: MIT
// This file was autogenerated by scripts/codegen/gen_kernels.py; DO NOT EDIT.
// Reduction dispatch: sum, mean, max, min, argmax, argmin, etc.

#include "marmot/device.h"
#include "marmot/error.h"
#include "marmot/tensor.h"

#include <stdint.h>
#include <stdlib.h>

#include "cpu_backend_internal.h"
#include "graph/kernel_dispatch_args.gen.h"

// ============================================================================
// Reduction Operation Implementations
// ============================================================================
// reduction_sum_accelerate: reduction op MARMOT_DEVICE_REDUCTION_SUM
#if MARMOT_ENABLE_ACCELERATE
marmot_error_t
marmot_cpu_reduction_sum_accelerate_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_sum_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_sum_neon: reduction op MARMOT_DEVICE_REDUCTION_SUM
#if MARMOT_ENABLE_NEON
marmot_error_t marmot_cpu_reduction_sum_neon_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_sum_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_sum_avx2: reduction op MARMOT_DEVICE_REDUCTION_SUM
#if MARMOT_ENABLE_AVX2
marmot_error_t marmot_cpu_reduction_sum_avx2_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_sum_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_sum_scalar: reduction op MARMOT_DEVICE_REDUCTION_SUM
marmot_error_t
marmot_cpu_reduction_sum_scalar_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_sum_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}

// reduction_mean_accelerate: reduction op MARMOT_DEVICE_REDUCTION_MEAN
#if MARMOT_ENABLE_ACCELERATE
marmot_error_t
marmot_cpu_reduction_mean_accelerate_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_mean_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_mean_neon: reduction op MARMOT_DEVICE_REDUCTION_MEAN
#if MARMOT_ENABLE_NEON
marmot_error_t marmot_cpu_reduction_mean_neon_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_mean_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_mean_avx2: reduction op MARMOT_DEVICE_REDUCTION_MEAN
#if MARMOT_ENABLE_AVX2
marmot_error_t marmot_cpu_reduction_mean_avx2_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_mean_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_mean_scalar: reduction op MARMOT_DEVICE_REDUCTION_MEAN
marmot_error_t
marmot_cpu_reduction_mean_scalar_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_mean_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}

// reduction_max_accelerate: reduction op MARMOT_DEVICE_REDUCTION_MAX
#if MARMOT_ENABLE_ACCELERATE
marmot_error_t
marmot_cpu_reduction_max_accelerate_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_max_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_max_neon: reduction op MARMOT_DEVICE_REDUCTION_MAX
#if MARMOT_ENABLE_NEON
marmot_error_t marmot_cpu_reduction_max_neon_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_max_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_max_avx2: reduction op MARMOT_DEVICE_REDUCTION_MAX
#if MARMOT_ENABLE_AVX2
marmot_error_t marmot_cpu_reduction_max_avx2_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_max_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_max_scalar: reduction op MARMOT_DEVICE_REDUCTION_MAX
marmot_error_t
marmot_cpu_reduction_max_scalar_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_max_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}

// reduction_min_accelerate: reduction op MARMOT_DEVICE_REDUCTION_MIN
#if MARMOT_ENABLE_ACCELERATE
marmot_error_t
marmot_cpu_reduction_min_accelerate_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_min_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_min_neon: reduction op MARMOT_DEVICE_REDUCTION_MIN
#if MARMOT_ENABLE_NEON
marmot_error_t marmot_cpu_reduction_min_neon_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_min_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_min_avx2: reduction op MARMOT_DEVICE_REDUCTION_MIN
#if MARMOT_ENABLE_AVX2
marmot_error_t marmot_cpu_reduction_min_avx2_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_min_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_min_scalar: reduction op MARMOT_DEVICE_REDUCTION_MIN
marmot_error_t
marmot_cpu_reduction_min_scalar_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_min_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}

// reduction_variance_accelerate: reduction op MARMOT_DEVICE_REDUCTION_VARIANCE
#if MARMOT_ENABLE_ACCELERATE
marmot_error_t
marmot_cpu_reduction_variance_accelerate_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_variance_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_variance_neon: reduction op MARMOT_DEVICE_REDUCTION_VARIANCE
#if MARMOT_ENABLE_NEON
marmot_error_t
marmot_cpu_reduction_variance_neon_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_variance_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_variance_avx2: reduction op MARMOT_DEVICE_REDUCTION_VARIANCE
#if MARMOT_ENABLE_AVX2
marmot_error_t
marmot_cpu_reduction_variance_avx2_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_variance_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_variance_scalar: reduction op MARMOT_DEVICE_REDUCTION_VARIANCE
marmot_error_t
marmot_cpu_reduction_variance_scalar_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_variance_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}

// reduction_std_accelerate: reduction op MARMOT_DEVICE_REDUCTION_STD
#if MARMOT_ENABLE_ACCELERATE
marmot_error_t
marmot_cpu_reduction_std_accelerate_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_std_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_std_neon: reduction op MARMOT_DEVICE_REDUCTION_STD
#if MARMOT_ENABLE_NEON
marmot_error_t marmot_cpu_reduction_std_neon_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_std_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_std_avx2: reduction op MARMOT_DEVICE_REDUCTION_STD
#if MARMOT_ENABLE_AVX2
marmot_error_t marmot_cpu_reduction_std_avx2_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_std_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_std_scalar: reduction op MARMOT_DEVICE_REDUCTION_STD
marmot_error_t
marmot_cpu_reduction_std_scalar_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_std_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}

// reduction_norm_l1_accelerate: reduction op MARMOT_DEVICE_REDUCTION_NORM_L1
#if MARMOT_ENABLE_ACCELERATE
marmot_error_t
marmot_cpu_reduction_norm_l1_accelerate_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_norm_l1_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_norm_l1_neon: reduction op MARMOT_DEVICE_REDUCTION_NORM_L1
#if MARMOT_ENABLE_NEON
marmot_error_t
marmot_cpu_reduction_norm_l1_neon_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_norm_l1_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_norm_l1_avx2: reduction op MARMOT_DEVICE_REDUCTION_NORM_L1
#if MARMOT_ENABLE_AVX2
marmot_error_t
marmot_cpu_reduction_norm_l1_avx2_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_norm_l1_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_norm_l1_scalar: reduction op MARMOT_DEVICE_REDUCTION_NORM_L1
marmot_error_t
marmot_cpu_reduction_norm_l1_scalar_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_norm_l1_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}

// reduction_norm_l2_accelerate: reduction op MARMOT_DEVICE_REDUCTION_NORM_L2
#if MARMOT_ENABLE_ACCELERATE
marmot_error_t
marmot_cpu_reduction_norm_l2_accelerate_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_norm_l2_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_norm_l2_neon: reduction op MARMOT_DEVICE_REDUCTION_NORM_L2
#if MARMOT_ENABLE_NEON
marmot_error_t
marmot_cpu_reduction_norm_l2_neon_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_norm_l2_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_norm_l2_avx2: reduction op MARMOT_DEVICE_REDUCTION_NORM_L2
#if MARMOT_ENABLE_AVX2
marmot_error_t
marmot_cpu_reduction_norm_l2_avx2_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_norm_l2_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_norm_l2_scalar: reduction op MARMOT_DEVICE_REDUCTION_NORM_L2
marmot_error_t
marmot_cpu_reduction_norm_l2_scalar_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_norm_l2_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}

// reduction_prod_accelerate: reduction op MARMOT_DEVICE_REDUCTION_PROD
#if MARMOT_ENABLE_ACCELERATE
marmot_error_t
marmot_cpu_reduction_prod_accelerate_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_prod_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_prod_neon: reduction op MARMOT_DEVICE_REDUCTION_PROD
#if MARMOT_ENABLE_NEON
marmot_error_t marmot_cpu_reduction_prod_neon_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_prod_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_prod_avx2: reduction op MARMOT_DEVICE_REDUCTION_PROD
#if MARMOT_ENABLE_AVX2
marmot_error_t marmot_cpu_reduction_prod_avx2_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_prod_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_prod_scalar: reduction op MARMOT_DEVICE_REDUCTION_PROD
marmot_error_t
marmot_cpu_reduction_prod_scalar_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_prod_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}

// reduction_argmax_accelerate: reduction op MARMOT_DEVICE_REDUCTION_ARGMAX
#if MARMOT_ENABLE_ACCELERATE
marmot_error_t
marmot_cpu_reduction_argmax_accelerate_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_argmax_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_argmax_neon: reduction op MARMOT_DEVICE_REDUCTION_ARGMAX
#if MARMOT_ENABLE_NEON
marmot_error_t
marmot_cpu_reduction_argmax_neon_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_argmax_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_argmax_avx2: reduction op MARMOT_DEVICE_REDUCTION_ARGMAX
#if MARMOT_ENABLE_AVX2
marmot_error_t
marmot_cpu_reduction_argmax_avx2_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_argmax_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_argmax_scalar: reduction op MARMOT_DEVICE_REDUCTION_ARGMAX
marmot_error_t
marmot_cpu_reduction_argmax_scalar_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_argmax_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}

// reduction_argmin_accelerate: reduction op MARMOT_DEVICE_REDUCTION_ARGMIN
#if MARMOT_ENABLE_ACCELERATE
marmot_error_t
marmot_cpu_reduction_argmin_accelerate_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_argmin_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_argmin_neon: reduction op MARMOT_DEVICE_REDUCTION_ARGMIN
#if MARMOT_ENABLE_NEON
marmot_error_t
marmot_cpu_reduction_argmin_neon_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_argmin_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_argmin_avx2: reduction op MARMOT_DEVICE_REDUCTION_ARGMIN
#if MARMOT_ENABLE_AVX2
marmot_error_t
marmot_cpu_reduction_argmin_avx2_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_argmin_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_argmin_scalar: reduction op MARMOT_DEVICE_REDUCTION_ARGMIN
marmot_error_t
marmot_cpu_reduction_argmin_scalar_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_argmin_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}

// reduction_any_accelerate: reduction op MARMOT_DEVICE_REDUCTION_ANY
#if MARMOT_ENABLE_ACCELERATE
marmot_error_t
marmot_cpu_reduction_any_accelerate_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_any_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_any_neon: reduction op MARMOT_DEVICE_REDUCTION_ANY
#if MARMOT_ENABLE_NEON
marmot_error_t marmot_cpu_reduction_any_neon_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_any_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_any_avx2: reduction op MARMOT_DEVICE_REDUCTION_ANY
#if MARMOT_ENABLE_AVX2
marmot_error_t marmot_cpu_reduction_any_avx2_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_any_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_any_scalar: reduction op MARMOT_DEVICE_REDUCTION_ANY
marmot_error_t
marmot_cpu_reduction_any_scalar_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_any_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}

// reduction_all_accelerate: reduction op MARMOT_DEVICE_REDUCTION_ALL
#if MARMOT_ENABLE_ACCELERATE
marmot_error_t
marmot_cpu_reduction_all_accelerate_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_all_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_all_neon: reduction op MARMOT_DEVICE_REDUCTION_ALL
#if MARMOT_ENABLE_NEON
marmot_error_t marmot_cpu_reduction_all_neon_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_all_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_all_avx2: reduction op MARMOT_DEVICE_REDUCTION_ALL
#if MARMOT_ENABLE_AVX2
marmot_error_t marmot_cpu_reduction_all_avx2_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_all_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
#endif

// reduction_all_scalar: reduction op MARMOT_DEVICE_REDUCTION_ALL
marmot_error_t
marmot_cpu_reduction_all_scalar_exec(const void *device_ctx, const marmot_kernel_args_reduction_t *args) {
    if (args == nullptr) {
        marmot_set_error(MARMOT_ERROR_INVALID_ARGUMENT, "Kernel args not provided");
        return MARMOT_ERROR_INVALID_ARGUMENT;
    }
    return cpu_reduction_all_impl(device_ctx, args->input, args->out_values, args->out_indices, args->params);
}
