// SPDX-License-Identifier: MIT
// This file was autogenerated by scripts/codegen/gen_dispatch_args.py; DO NOT EDIT.

#ifndef MARMOT_GRAPH_INTERNAL_KERNEL_DISPATCH_ARGS_GEN_H
#define MARMOT_GRAPH_INTERNAL_KERNEL_DISPATCH_ARGS_GEN_H

#include "marmot/ops/matmul.h"
#include "marmot/ops/quantization.h"
#include "marmot/ops/reduction.h"
#include "marmot/ops/rope.h"
#include "marmot/traits_ids.gen.h"

#ifdef __cplusplus
extern "C" {
#endif

// =============================================================================
// Arg Index Enums
// =============================================================================
enum {
    MARMOT_KERNEL_ARGS_BINARY_CTX = 0,
    MARMOT_KERNEL_ARGS_BINARY_INPUT_A = 1,
    MARMOT_KERNEL_ARGS_BINARY_INPUT_B = 2,
    MARMOT_KERNEL_ARGS_BINARY_OUTPUT = 3,
    MARMOT_KERNEL_ARGS_BINARY_COUNT = 4,
};

enum {
    MARMOT_KERNEL_ARGS_UNARY_CTX = 0,
    MARMOT_KERNEL_ARGS_UNARY_INPUT = 1,
    MARMOT_KERNEL_ARGS_UNARY_PARAMS = 2,
    MARMOT_KERNEL_ARGS_UNARY_OUTPUT = 3,
    MARMOT_KERNEL_ARGS_UNARY_COUNT = 4,
};

enum {
    MARMOT_KERNEL_ARGS_TERNARY_CTX = 0,
    MARMOT_KERNEL_ARGS_TERNARY_INPUT_A = 1,
    MARMOT_KERNEL_ARGS_TERNARY_INPUT_B = 2,
    MARMOT_KERNEL_ARGS_TERNARY_INPUT_C = 3,
    MARMOT_KERNEL_ARGS_TERNARY_OUTPUT = 4,
    MARMOT_KERNEL_ARGS_TERNARY_COUNT = 5,
};

enum {
    MARMOT_KERNEL_ARGS_REDUCTION_CTX = 0,
    MARMOT_KERNEL_ARGS_REDUCTION_INPUT = 1,
    MARMOT_KERNEL_ARGS_REDUCTION_OUT_VALUES = 2,
    MARMOT_KERNEL_ARGS_REDUCTION_OUT_INDICES = 3,
    MARMOT_KERNEL_ARGS_REDUCTION_PARAMS = 4,
    MARMOT_KERNEL_ARGS_REDUCTION_COUNT = 5,
};

enum {
    MARMOT_KERNEL_ARGS_SOFTMAX_CTX = 0,
    MARMOT_KERNEL_ARGS_SOFTMAX_INPUT = 1,
    MARMOT_KERNEL_ARGS_SOFTMAX_OUTPUT = 2,
    MARMOT_KERNEL_ARGS_SOFTMAX_AXIS = 3,
    MARMOT_KERNEL_ARGS_SOFTMAX_COUNT = 4,
};

enum {
    MARMOT_KERNEL_ARGS_LAYERNORM_CTX = 0,
    MARMOT_KERNEL_ARGS_LAYERNORM_INPUT = 1,
    MARMOT_KERNEL_ARGS_LAYERNORM_WEIGHT = 2,
    MARMOT_KERNEL_ARGS_LAYERNORM_BIAS = 3,
    MARMOT_KERNEL_ARGS_LAYERNORM_RESIDUAL = 4,
    MARMOT_KERNEL_ARGS_LAYERNORM_OUTPUT = 5,
    MARMOT_KERNEL_ARGS_LAYERNORM_EPS = 6,
    MARMOT_KERNEL_ARGS_LAYERNORM_COUNT = 7,
};

enum {
    MARMOT_KERNEL_ARGS_RMS_NORM_CTX = 0,
    MARMOT_KERNEL_ARGS_RMS_NORM_INPUT = 1,
    MARMOT_KERNEL_ARGS_RMS_NORM_WEIGHT = 2,
    MARMOT_KERNEL_ARGS_RMS_NORM_RESIDUAL = 3,
    MARMOT_KERNEL_ARGS_RMS_NORM_OUTPUT = 4,
    MARMOT_KERNEL_ARGS_RMS_NORM_EPS = 5,
    MARMOT_KERNEL_ARGS_RMS_NORM_COUNT = 6,
};

enum {
    MARMOT_KERNEL_ARGS_PAGED_ATTENTION_CTX = 0,
    MARMOT_KERNEL_ARGS_PAGED_ATTENTION_TOKEN_META = 1,
    MARMOT_KERNEL_ARGS_PAGED_ATTENTION_Q = 2,
    MARMOT_KERNEL_ARGS_PAGED_ATTENTION_K_NEW = 3,
    MARMOT_KERNEL_ARGS_PAGED_ATTENTION_V_NEW = 4,
    MARMOT_KERNEL_ARGS_PAGED_ATTENTION_KV_K = 5,
    MARMOT_KERNEL_ARGS_PAGED_ATTENTION_KV_V = 6,
    MARMOT_KERNEL_ARGS_PAGED_ATTENTION_BLOCK_TABLE = 7,
    MARMOT_KERNEL_ARGS_PAGED_ATTENTION_KV_K_SCALE = 8,
    MARMOT_KERNEL_ARGS_PAGED_ATTENTION_KV_V_SCALE = 9,
    MARMOT_KERNEL_ARGS_PAGED_ATTENTION_OUT = 10,
    MARMOT_KERNEL_ARGS_PAGED_ATTENTION_TOKEN_COUNT = 11,
    MARMOT_KERNEL_ARGS_PAGED_ATTENTION_LAYER_IDX = 12,
    MARMOT_KERNEL_ARGS_PAGED_ATTENTION_NUM_Q_HEADS = 13,
    MARMOT_KERNEL_ARGS_PAGED_ATTENTION_NUM_KV_HEADS = 14,
    MARMOT_KERNEL_ARGS_PAGED_ATTENTION_HEAD_DIM = 15,
    MARMOT_KERNEL_ARGS_PAGED_ATTENTION_BLOCK_SIZE = 16,
    MARMOT_KERNEL_ARGS_PAGED_ATTENTION_SCALE = 17,
    MARMOT_KERNEL_ARGS_PAGED_ATTENTION_COUNT = 18,
};

enum {
    MARMOT_KERNEL_ARGS_ROPE_CTX = 0,
    MARMOT_KERNEL_ARGS_ROPE_INPUT = 1,
    MARMOT_KERNEL_ARGS_ROPE_OUTPUT = 2,
    MARMOT_KERNEL_ARGS_ROPE_ROPE_PARAMS = 3,
    MARMOT_KERNEL_ARGS_ROPE_N_PAST = 4,
    MARMOT_KERNEL_ARGS_ROPE_N_ROT = 5,
    MARMOT_KERNEL_ARGS_ROPE_COUNT = 6,
};

enum {
    MARMOT_KERNEL_ARGS_MATMUL_CTX = 0,
    MARMOT_KERNEL_ARGS_MATMUL_INPUT = 1,
    MARMOT_KERNEL_ARGS_MATMUL_WEIGHT = 2,
    MARMOT_KERNEL_ARGS_MATMUL_EPILOGUE = 3,
    MARMOT_KERNEL_ARGS_MATMUL_OUTPUT = 4,
    MARMOT_KERNEL_ARGS_MATMUL_COUNT = 5,
};

enum {
    MARMOT_KERNEL_ARGS_QKV_CTX = 0,
    MARMOT_KERNEL_ARGS_QKV_INPUT = 1,
    MARMOT_KERNEL_ARGS_QKV_WQ = 2,
    MARMOT_KERNEL_ARGS_QKV_WK = 3,
    MARMOT_KERNEL_ARGS_QKV_WV = 4,
    MARMOT_KERNEL_ARGS_QKV_BQ = 5,
    MARMOT_KERNEL_ARGS_QKV_BK = 6,
    MARMOT_KERNEL_ARGS_QKV_BV = 7,
    MARMOT_KERNEL_ARGS_QKV_EPILOGUE = 8,
    MARMOT_KERNEL_ARGS_QKV_ROPE_PARAMS = 9,
    MARMOT_KERNEL_ARGS_QKV_OUT_Q = 10,
    MARMOT_KERNEL_ARGS_QKV_OUT_K = 11,
    MARMOT_KERNEL_ARGS_QKV_OUT_V = 12,
    MARMOT_KERNEL_ARGS_QKV_COUNT = 13,
};

enum {
    MARMOT_KERNEL_ARGS_RESHAPE_CTX = 0,
    MARMOT_KERNEL_ARGS_RESHAPE_INPUT = 1,
    MARMOT_KERNEL_ARGS_RESHAPE_OUTPUT = 2,
    MARMOT_KERNEL_ARGS_RESHAPE_NEW_SHAPE = 3,
    MARMOT_KERNEL_ARGS_RESHAPE_NEW_NDIM = 4,
    MARMOT_KERNEL_ARGS_RESHAPE_COUNT = 5,
};

enum {
    MARMOT_KERNEL_ARGS_VIEW_CTX = 0,
    MARMOT_KERNEL_ARGS_VIEW_INPUT = 1,
    MARMOT_KERNEL_ARGS_VIEW_OUTPUT = 2,
    MARMOT_KERNEL_ARGS_VIEW_BYTE_OFFSET = 3,
    MARMOT_KERNEL_ARGS_VIEW_COUNT = 4,
};

enum {
    MARMOT_KERNEL_ARGS_CONTIGUOUS_CTX = 0,
    MARMOT_KERNEL_ARGS_CONTIGUOUS_INPUT = 1,
    MARMOT_KERNEL_ARGS_CONTIGUOUS_OUTPUT = 2,
    MARMOT_KERNEL_ARGS_CONTIGUOUS_COUNT = 3,
};

enum {
    MARMOT_KERNEL_ARGS_TRANSPOSE_CTX = 0,
    MARMOT_KERNEL_ARGS_TRANSPOSE_INPUT = 1,
    MARMOT_KERNEL_ARGS_TRANSPOSE_OUTPUT = 2,
    MARMOT_KERNEL_ARGS_TRANSPOSE_PERM = 3,
    MARMOT_KERNEL_ARGS_TRANSPOSE_COUNT = 4,
};

enum {
    MARMOT_KERNEL_ARGS_CONCAT_CTX = 0,
    MARMOT_KERNEL_ARGS_CONCAT_INPUTS = 1,
    MARMOT_KERNEL_ARGS_CONCAT_NUM_INPUTS = 2,
    MARMOT_KERNEL_ARGS_CONCAT_OUTPUT = 3,
    MARMOT_KERNEL_ARGS_CONCAT_AXIS = 4,
    MARMOT_KERNEL_ARGS_CONCAT_COUNT = 5,
};

enum {
    MARMOT_KERNEL_ARGS_SLICE_CTX = 0,
    MARMOT_KERNEL_ARGS_SLICE_INPUT = 1,
    MARMOT_KERNEL_ARGS_SLICE_OUTPUT = 2,
    MARMOT_KERNEL_ARGS_SLICE_STARTS = 3,
    MARMOT_KERNEL_ARGS_SLICE_SIZES = 4,
    MARMOT_KERNEL_ARGS_SLICE_COUNT = 5,
};

enum {
    MARMOT_KERNEL_ARGS_GATHER_ROWS_CTX = 0,
    MARMOT_KERNEL_ARGS_GATHER_ROWS_INPUT = 1,
    MARMOT_KERNEL_ARGS_GATHER_ROWS_INDICES = 2,
    MARMOT_KERNEL_ARGS_GATHER_ROWS_OUTPUT = 3,
    MARMOT_KERNEL_ARGS_GATHER_ROWS_COUNT = 4,
};

enum {
    MARMOT_KERNEL_ARGS_QUANTIZE_CTX = 0,
    MARMOT_KERNEL_ARGS_QUANTIZE_INPUT = 1,
    MARMOT_KERNEL_ARGS_QUANTIZE_PARAMS = 2,
    MARMOT_KERNEL_ARGS_QUANTIZE_OUTPUT = 3,
    MARMOT_KERNEL_ARGS_QUANTIZE_KIND = 4,
    MARMOT_KERNEL_ARGS_QUANTIZE_LAYOUT = 5,
    MARMOT_KERNEL_ARGS_QUANTIZE_COUNT = 6,
};

enum {
    MARMOT_KERNEL_ARGS_DEQUANTIZE_CTX = 0,
    MARMOT_KERNEL_ARGS_DEQUANTIZE_INPUT = 1,
    MARMOT_KERNEL_ARGS_DEQUANTIZE_OUTPUT = 2,
    MARMOT_KERNEL_ARGS_DEQUANTIZE_KIND = 3,
    MARMOT_KERNEL_ARGS_DEQUANTIZE_LAYOUT = 4,
    MARMOT_KERNEL_ARGS_DEQUANTIZE_COUNT = 5,
};

enum {
    MARMOT_KERNEL_ARGS_COMPUTE_QPARAMS_CTX = 0,
    MARMOT_KERNEL_ARGS_COMPUTE_QPARAMS_TENSOR = 1,
    MARMOT_KERNEL_ARGS_COMPUTE_QPARAMS_TARGET_DTYPE = 2,
    MARMOT_KERNEL_ARGS_COMPUTE_QPARAMS_BLOCK_SIZE = 3,
    MARMOT_KERNEL_ARGS_COMPUTE_QPARAMS_OUTPUT = 4,
    MARMOT_KERNEL_ARGS_COMPUTE_QPARAMS_COUNT = 5,
};

enum {
    MARMOT_KERNEL_ARGS_EMBED_CTX = 0,
    MARMOT_KERNEL_ARGS_EMBED_WEIGHTS = 1,
    MARMOT_KERNEL_ARGS_EMBED_TOKEN_IDS = 2,
    MARMOT_KERNEL_ARGS_EMBED_OUT = 3,
    MARMOT_KERNEL_ARGS_EMBED_DTYPE_OUT = 4,
    MARMOT_KERNEL_ARGS_EMBED_SCALE = 5,
    MARMOT_KERNEL_ARGS_EMBED_PADDING_ID = 6,
    MARMOT_KERNEL_ARGS_EMBED_BOUNDS_CHECK = 7,
    MARMOT_KERNEL_ARGS_EMBED_PREFER_GPU = 8,
    MARMOT_KERNEL_ARGS_EMBED_ALLOW_DECODE = 9,
    MARMOT_KERNEL_ARGS_EMBED_COUNT = 10,
};

enum {
    MARMOT_KERNEL_ARGS_CONVERT_CTX = 0,
    MARMOT_KERNEL_ARGS_CONVERT_DST = 1,
    MARMOT_KERNEL_ARGS_CONVERT_SRC = 2,
    MARMOT_KERNEL_ARGS_CONVERT_N = 3,
    MARMOT_KERNEL_ARGS_CONVERT_DST_DTYPE = 4,
    MARMOT_KERNEL_ARGS_CONVERT_SRC_DTYPE = 5,
    MARMOT_KERNEL_ARGS_CONVERT_COUNT = 6,
};

enum {
    MARMOT_KERNEL_ARGS_VEC_DOT_CTX = 0,
    MARMOT_KERNEL_ARGS_VEC_DOT_DESC = 1,
    MARMOT_KERNEL_ARGS_VEC_DOT_RESULT = 2,
    MARMOT_KERNEL_ARGS_VEC_DOT_COUNT = 3,
};

// =============================================================================
// Arg Structs
// =============================================================================
typedef struct marmot_kernel_args_binary {
    const marmot_context_t *ctx;
    const marmot_tensor_t *input_a;
    const marmot_tensor_t *input_b;
    marmot_tensor_t *output;
} marmot_kernel_args_binary_t;

typedef struct marmot_kernel_args_unary {
    const marmot_context_t *ctx;
    const marmot_tensor_t *input;
    const marmot_activation_params_t *params;
    marmot_tensor_t *output;
} marmot_kernel_args_unary_t;

typedef struct marmot_kernel_args_ternary {
    const marmot_context_t *ctx;
    const marmot_tensor_t *input_a;
    const marmot_tensor_t *input_b;
    const marmot_tensor_t *input_c;
    marmot_tensor_t *output;
} marmot_kernel_args_ternary_t;

typedef struct marmot_kernel_args_reduction {
    const marmot_context_t *ctx;
    const marmot_tensor_t *input;
    marmot_tensor_t *out_values;
    marmot_tensor_t *out_indices;
    const marmot_reduction_params_t *params;
} marmot_kernel_args_reduction_t;

typedef struct marmot_kernel_args_softmax {
    const marmot_context_t *ctx;
    const marmot_tensor_t *input;
    marmot_tensor_t *output;
    int32_t axis;
} marmot_kernel_args_softmax_t;

typedef struct marmot_kernel_args_layernorm {
    const marmot_context_t *ctx;
    const marmot_tensor_t *input;
    const marmot_tensor_t *weight;
    const marmot_tensor_t *bias;
    const marmot_tensor_t *residual;
    marmot_tensor_t *output;
    float eps;
} marmot_kernel_args_layernorm_t;

typedef struct marmot_kernel_args_rms_norm {
    const marmot_context_t *ctx;
    const marmot_tensor_t *input;
    const marmot_tensor_t *weight;
    const marmot_tensor_t *residual;
    marmot_tensor_t *output;
    float eps;
} marmot_kernel_args_rms_norm_t;

typedef struct marmot_kernel_args_paged_attention {
    const marmot_context_t *ctx;
    const marmot_tensor_t *token_meta;
    const marmot_tensor_t *q;
    const marmot_tensor_t *k_new;
    const marmot_tensor_t *v_new;
    marmot_tensor_t *kv_k;
    marmot_tensor_t *kv_v;
    const marmot_tensor_t *block_table;
    marmot_tensor_t *kv_k_scale;
    marmot_tensor_t *kv_v_scale;
    marmot_tensor_t *out;
    uint32_t token_count;
    uint32_t layer_idx;
    uint32_t num_q_heads;
    uint32_t num_kv_heads;
    uint32_t head_dim;
    uint32_t block_size;
    float scale;
} marmot_kernel_args_paged_attention_t;

typedef struct marmot_kernel_args_rope {
    const marmot_context_t *ctx;
    const marmot_tensor_t *input;
    marmot_tensor_t *output;
    const marmot_rope_params_t *rope_params;
    uint32_t n_past;
    uint32_t n_rot;
} marmot_kernel_args_rope_t;

typedef struct marmot_kernel_args_matmul {
    const marmot_context_t *ctx;
    const marmot_tensor_t *input;
    const marmot_tensor_t *weight;
    const marmot_matmul_epilogue_t *epilogue;
    marmot_tensor_t *output;
} marmot_kernel_args_matmul_t;

typedef struct marmot_kernel_args_qkv {
    const marmot_context_t *ctx;
    const marmot_tensor_t *input;
    const marmot_tensor_t *wq;
    const marmot_tensor_t *wk;
    const marmot_tensor_t *wv;
    const marmot_tensor_t *bq;
    const marmot_tensor_t *bk;
    const marmot_tensor_t *bv;
    const marmot_matmul_epilogue_t *epilogue;
    const marmot_rope_params_t *rope_params;
    marmot_tensor_t *out_q;
    marmot_tensor_t *out_k;
    marmot_tensor_t *out_v;
} marmot_kernel_args_qkv_t;

typedef struct marmot_kernel_args_reshape {
    const marmot_context_t *ctx;
    const marmot_tensor_t *input;
    marmot_tensor_t *output;
    const size_t *new_shape;
    size_t new_ndim;
} marmot_kernel_args_reshape_t;

typedef struct marmot_kernel_args_view {
    const marmot_context_t *ctx;
    const marmot_tensor_t *input;
    marmot_tensor_t *output;
    size_t byte_offset;
} marmot_kernel_args_view_t;

typedef struct marmot_kernel_args_contiguous {
    const marmot_context_t *ctx;
    const marmot_tensor_t *input;
    marmot_tensor_t *output;
} marmot_kernel_args_contiguous_t;

typedef struct marmot_kernel_args_transpose {
    const marmot_context_t *ctx;
    const marmot_tensor_t *input;
    marmot_tensor_t *output;
    const int *perm;
} marmot_kernel_args_transpose_t;

typedef struct marmot_kernel_args_concat {
    const marmot_context_t *ctx;
    const marmot_tensor_t *const *inputs;
    size_t num_inputs;
    marmot_tensor_t *output;
    int axis;
} marmot_kernel_args_concat_t;

typedef struct marmot_kernel_args_slice {
    const marmot_context_t *ctx;
    const marmot_tensor_t *input;
    marmot_tensor_t *output;
    const size_t *starts;
    const size_t *sizes;
} marmot_kernel_args_slice_t;

typedef struct marmot_kernel_args_gather_rows {
    const marmot_context_t *ctx;
    const marmot_tensor_t *input;
    const marmot_tensor_t *indices;
    marmot_tensor_t *output;
} marmot_kernel_args_gather_rows_t;

typedef struct marmot_kernel_args_quantize {
    const marmot_context_t *ctx;
    const marmot_tensor_t *input;
    const marmot_quant_params_t *quant_params;
    marmot_tensor_t *output;
    marmot_quant_kind_t kind;
    marmot_quant_layout_t layout;
} marmot_kernel_args_quantize_t;

typedef struct marmot_kernel_args_dequantize {
    const marmot_context_t *ctx;
    const marmot_tensor_t *input;
    marmot_tensor_t *output;
    marmot_quant_kind_t kind;
    marmot_quant_layout_t layout;
} marmot_kernel_args_dequantize_t;

typedef struct marmot_kernel_args_compute_qparams {
    const marmot_context_t *ctx;
    const marmot_tensor_t *tensor;
    marmot_dtype_t target_dtype;
    size_t block_size;
    marmot_quant_params_t *out_params;
} marmot_kernel_args_compute_qparams_t;

typedef struct marmot_kernel_args_embedding {
    const marmot_context_t *ctx;
    const marmot_tensor_t *weights;
    const marmot_tensor_t *token_ids;
    marmot_tensor_t *out;
    marmot_dtype_t dtype_out;
    float scale;
    int32_t padding_id;
    bool bounds_check;
    bool prefer_gpu_private;
    bool allow_quant_decode_on_the_fly;
} marmot_kernel_args_embedding_t;

typedef struct marmot_kernel_args_convert {
    const marmot_context_t *ctx;
    void *dst;
    const void *src;
    size_t n;
    marmot_dtype_t dst_dtype;
    marmot_dtype_t src_dtype;
} marmot_kernel_args_convert_t;

typedef struct marmot_kernel_args_vec_dot {
    const marmot_context_t *ctx;
    const marmot_vec_dot_descriptor_t *desc;
    float *result;
} marmot_kernel_args_vec_dot_t;

// =============================================================================
// Op-Specific Aliases (for backward compatibility with generated dispatch)
// =============================================================================
typedef marmot_kernel_args_binary_t marmot_kernel_args_add_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_add_gelu_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_add_relu_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_add_silu_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_bitwise_and_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_bitwise_or_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_bitwise_shl_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_bitwise_shr_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_bitwise_shr_logical_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_bitwise_xor_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_compare_eq_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_compare_ge_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_compare_gt_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_compare_le_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_compare_lt_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_compare_ne_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_div_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_geglu_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_max_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_min_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_mod_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_mul_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_pow_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_sub_t;
typedef marmot_kernel_args_binary_t marmot_kernel_args_swiglu_t;
typedef marmot_kernel_args_unary_t marmot_kernel_args_abs_t;
typedef marmot_kernel_args_unary_t marmot_kernel_args_bitwise_not_t;
typedef marmot_kernel_args_unary_t marmot_kernel_args_elu_t;
typedef marmot_kernel_args_unary_t marmot_kernel_args_exp_t;
typedef marmot_kernel_args_unary_t marmot_kernel_args_gelu_t;
typedef marmot_kernel_args_unary_t marmot_kernel_args_gelu_tanh_t;
typedef marmot_kernel_args_unary_t marmot_kernel_args_leaky_relu_t;
typedef marmot_kernel_args_unary_t marmot_kernel_args_log_t;
typedef marmot_kernel_args_unary_t marmot_kernel_args_mish_t;
typedef marmot_kernel_args_unary_t marmot_kernel_args_neg_t;
typedef marmot_kernel_args_unary_t marmot_kernel_args_prelu_t;
typedef marmot_kernel_args_unary_t marmot_kernel_args_relu_t;
typedef marmot_kernel_args_unary_t marmot_kernel_args_selu_t;
typedef marmot_kernel_args_unary_t marmot_kernel_args_sigmoid_t;
typedef marmot_kernel_args_unary_t marmot_kernel_args_sign_t;
typedef marmot_kernel_args_unary_t marmot_kernel_args_silu_t;
typedef marmot_kernel_args_unary_t marmot_kernel_args_sqrt_t;
typedef marmot_kernel_args_unary_t marmot_kernel_args_tanh_t;
typedef marmot_kernel_args_ternary_t marmot_kernel_args_fma_t;
typedef marmot_kernel_args_ternary_t marmot_kernel_args_where_t;
typedef marmot_kernel_args_reduction_t marmot_kernel_args_reduction_all_t;
typedef marmot_kernel_args_reduction_t marmot_kernel_args_reduction_any_t;
typedef marmot_kernel_args_reduction_t marmot_kernel_args_reduction_argmax_t;
typedef marmot_kernel_args_reduction_t marmot_kernel_args_reduction_argmin_t;
typedef marmot_kernel_args_reduction_t marmot_kernel_args_reduction_max_t;
typedef marmot_kernel_args_reduction_t marmot_kernel_args_reduction_mean_t;
typedef marmot_kernel_args_reduction_t marmot_kernel_args_reduction_min_t;
typedef marmot_kernel_args_reduction_t marmot_kernel_args_reduction_norm_l1_t;
typedef marmot_kernel_args_reduction_t marmot_kernel_args_reduction_norm_l2_t;
typedef marmot_kernel_args_reduction_t marmot_kernel_args_reduction_prod_t;
typedef marmot_kernel_args_reduction_t marmot_kernel_args_reduction_std_t;
typedef marmot_kernel_args_reduction_t marmot_kernel_args_reduction_sum_t;
typedef marmot_kernel_args_reduction_t marmot_kernel_args_reduction_variance_t;
typedef marmot_kernel_args_rms_norm_t marmot_kernel_args_rms_norm_gemma_t;
typedef marmot_kernel_args_matmul_t marmot_kernel_args_matmul_bias_t;
typedef marmot_kernel_args_matmul_t marmot_kernel_args_matmul_bias_gelu_t;
typedef marmot_kernel_args_matmul_t marmot_kernel_args_matmul_bias_relu_t;
typedef marmot_kernel_args_matmul_t marmot_kernel_args_matmul_bias_silu_t;
typedef marmot_kernel_args_qkv_t marmot_kernel_args_qkv_projection_t;
typedef marmot_kernel_args_qkv_t marmot_kernel_args_qkv_rope_t;
typedef marmot_kernel_args_qkv_t marmot_kernel_args_qkv_shared_input_t;
typedef marmot_kernel_args_compute_qparams_t marmot_kernel_args_compute_quant_params_t;

// =============================================================================
// Op to Schema Mapping
// =============================================================================
typedef enum {
    MARMOT_OP_SCHEMA_BINARY,
    MARMOT_OP_SCHEMA_UNARY,
    MARMOT_OP_SCHEMA_TERNARY,
    MARMOT_OP_SCHEMA_REDUCTION,
    MARMOT_OP_SCHEMA_SOFTMAX,
    MARMOT_OP_SCHEMA_LAYERNORM,
    MARMOT_OP_SCHEMA_RMS_NORM,
    MARMOT_OP_SCHEMA_PAGED_ATTENTION,
    MARMOT_OP_SCHEMA_ROPE,
    MARMOT_OP_SCHEMA_MATMUL,
    MARMOT_OP_SCHEMA_QKV,
    MARMOT_OP_SCHEMA_RESHAPE,
    MARMOT_OP_SCHEMA_VIEW,
    MARMOT_OP_SCHEMA_CONTIGUOUS,
    MARMOT_OP_SCHEMA_TRANSPOSE,
    MARMOT_OP_SCHEMA_CONCAT,
    MARMOT_OP_SCHEMA_SLICE,
    MARMOT_OP_SCHEMA_GATHER_ROWS,
    MARMOT_OP_SCHEMA_QUANTIZE,
    MARMOT_OP_SCHEMA_DEQUANTIZE,
    MARMOT_OP_SCHEMA_COMPUTE_QPARAMS,
    MARMOT_OP_SCHEMA_EMBEDDING,
    MARMOT_OP_SCHEMA_CONVERT,
    MARMOT_OP_SCHEMA_VEC_DOT,
    MARMOT_OP_SCHEMA_COUNT,
} marmot_op_schema_t;

static inline marmot_op_schema_t marmot_op_get_schema(marmot_op_id_t op) {
    switch (op) {
    case MARMOT_OP_ADD:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_ADD_GELU:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_ADD_RELU:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_ADD_SILU:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_BITWISE_AND:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_BITWISE_OR:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_BITWISE_SHL:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_BITWISE_SHR:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_BITWISE_SHR_LOGICAL:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_BITWISE_XOR:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_COMPARE_EQ:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_COMPARE_GE:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_COMPARE_GT:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_COMPARE_LE:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_COMPARE_LT:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_COMPARE_NE:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_DIV:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_GEGLU:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_MAX:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_MIN:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_MOD:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_MUL:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_POW:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_SUB:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_SWIGLU:
        return MARMOT_OP_SCHEMA_BINARY;
    case MARMOT_OP_ABS:
        return MARMOT_OP_SCHEMA_UNARY;
    case MARMOT_OP_BITWISE_NOT:
        return MARMOT_OP_SCHEMA_UNARY;
    case MARMOT_OP_ELU:
        return MARMOT_OP_SCHEMA_UNARY;
    case MARMOT_OP_EXP:
        return MARMOT_OP_SCHEMA_UNARY;
    case MARMOT_OP_GELU:
        return MARMOT_OP_SCHEMA_UNARY;
    case MARMOT_OP_GELU_TANH:
        return MARMOT_OP_SCHEMA_UNARY;
    case MARMOT_OP_LEAKY_RELU:
        return MARMOT_OP_SCHEMA_UNARY;
    case MARMOT_OP_LOG:
        return MARMOT_OP_SCHEMA_UNARY;
    case MARMOT_OP_MISH:
        return MARMOT_OP_SCHEMA_UNARY;
    case MARMOT_OP_NEG:
        return MARMOT_OP_SCHEMA_UNARY;
    case MARMOT_OP_PRELU:
        return MARMOT_OP_SCHEMA_UNARY;
    case MARMOT_OP_RELU:
        return MARMOT_OP_SCHEMA_UNARY;
    case MARMOT_OP_SELU:
        return MARMOT_OP_SCHEMA_UNARY;
    case MARMOT_OP_SIGMOID:
        return MARMOT_OP_SCHEMA_UNARY;
    case MARMOT_OP_SIGN:
        return MARMOT_OP_SCHEMA_UNARY;
    case MARMOT_OP_SILU:
        return MARMOT_OP_SCHEMA_UNARY;
    case MARMOT_OP_SQRT:
        return MARMOT_OP_SCHEMA_UNARY;
    case MARMOT_OP_TANH:
        return MARMOT_OP_SCHEMA_UNARY;
    case MARMOT_OP_FMA:
        return MARMOT_OP_SCHEMA_TERNARY;
    case MARMOT_OP_WHERE:
        return MARMOT_OP_SCHEMA_TERNARY;
    case MARMOT_OP_REDUCTION_ALL:
        return MARMOT_OP_SCHEMA_REDUCTION;
    case MARMOT_OP_REDUCTION_ANY:
        return MARMOT_OP_SCHEMA_REDUCTION;
    case MARMOT_OP_REDUCTION_ARGMAX:
        return MARMOT_OP_SCHEMA_REDUCTION;
    case MARMOT_OP_REDUCTION_ARGMIN:
        return MARMOT_OP_SCHEMA_REDUCTION;
    case MARMOT_OP_REDUCTION_MAX:
        return MARMOT_OP_SCHEMA_REDUCTION;
    case MARMOT_OP_REDUCTION_MEAN:
        return MARMOT_OP_SCHEMA_REDUCTION;
    case MARMOT_OP_REDUCTION_MIN:
        return MARMOT_OP_SCHEMA_REDUCTION;
    case MARMOT_OP_REDUCTION_NORM_L1:
        return MARMOT_OP_SCHEMA_REDUCTION;
    case MARMOT_OP_REDUCTION_NORM_L2:
        return MARMOT_OP_SCHEMA_REDUCTION;
    case MARMOT_OP_REDUCTION_PROD:
        return MARMOT_OP_SCHEMA_REDUCTION;
    case MARMOT_OP_REDUCTION_STD:
        return MARMOT_OP_SCHEMA_REDUCTION;
    case MARMOT_OP_REDUCTION_SUM:
        return MARMOT_OP_SCHEMA_REDUCTION;
    case MARMOT_OP_REDUCTION_VARIANCE:
        return MARMOT_OP_SCHEMA_REDUCTION;
    case MARMOT_OP_SOFTMAX:
        return MARMOT_OP_SCHEMA_SOFTMAX;
    case MARMOT_OP_LAYERNORM:
        return MARMOT_OP_SCHEMA_LAYERNORM;
    case MARMOT_OP_RMS_NORM:
        return MARMOT_OP_SCHEMA_RMS_NORM;
    case MARMOT_OP_RMS_NORM_GEMMA:
        return MARMOT_OP_SCHEMA_RMS_NORM;
    case MARMOT_OP_PAGED_ATTENTION:
        return MARMOT_OP_SCHEMA_PAGED_ATTENTION;
    case MARMOT_OP_ROPE:
        return MARMOT_OP_SCHEMA_ROPE;
    case MARMOT_OP_MATMUL:
        return MARMOT_OP_SCHEMA_MATMUL;
    case MARMOT_OP_MATMUL_BIAS:
        return MARMOT_OP_SCHEMA_MATMUL;
    case MARMOT_OP_MATMUL_BIAS_GELU:
        return MARMOT_OP_SCHEMA_MATMUL;
    case MARMOT_OP_MATMUL_BIAS_RELU:
        return MARMOT_OP_SCHEMA_MATMUL;
    case MARMOT_OP_MATMUL_BIAS_SILU:
        return MARMOT_OP_SCHEMA_MATMUL;
    case MARMOT_OP_QKV_PROJECTION:
        return MARMOT_OP_SCHEMA_QKV;
    case MARMOT_OP_QKV_ROPE:
        return MARMOT_OP_SCHEMA_QKV;
    case MARMOT_OP_QKV_SHARED_INPUT:
        return MARMOT_OP_SCHEMA_QKV;
    case MARMOT_OP_RESHAPE:
        return MARMOT_OP_SCHEMA_RESHAPE;
    case MARMOT_OP_VIEW:
        return MARMOT_OP_SCHEMA_VIEW;
    case MARMOT_OP_CONTIGUOUS:
        return MARMOT_OP_SCHEMA_CONTIGUOUS;
    case MARMOT_OP_TRANSPOSE:
        return MARMOT_OP_SCHEMA_TRANSPOSE;
    case MARMOT_OP_CONCAT:
        return MARMOT_OP_SCHEMA_CONCAT;
    case MARMOT_OP_SLICE:
        return MARMOT_OP_SCHEMA_SLICE;
    case MARMOT_OP_GATHER_ROWS:
        return MARMOT_OP_SCHEMA_GATHER_ROWS;
    case MARMOT_OP_QUANTIZE:
        return MARMOT_OP_SCHEMA_QUANTIZE;
    case MARMOT_OP_DEQUANTIZE:
        return MARMOT_OP_SCHEMA_DEQUANTIZE;
    case MARMOT_OP_COMPUTE_QUANT_PARAMS:
        return MARMOT_OP_SCHEMA_COMPUTE_QPARAMS;
    case MARMOT_OP_EMBEDDING:
        return MARMOT_OP_SCHEMA_EMBEDDING;
    case MARMOT_OP_CONVERT:
        return MARMOT_OP_SCHEMA_CONVERT;
    case MARMOT_OP_VEC_DOT:
        return MARMOT_OP_SCHEMA_VEC_DOT;
    default:
        return MARMOT_OP_SCHEMA_COUNT;
    }
}

#ifdef __cplusplus
}
#endif

#endif // MARMOT_GRAPH_INTERNAL_KERNEL_DISPATCH_ARGS_GEN_H
