// SPDX-License-Identifier: MIT
// This file was autogenerated by scripts/codegen/gen_api_dispatch.py; DO NOT EDIT.

#ifndef MARMOT_OP_METADATA_GEN_H
#define MARMOT_OP_METADATA_GEN_H

#include "marmot/ops_types.h"
#include "marmot/traits_ids.gen.h"

#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

static inline marmot_op_id_t marmot_op_metadata_reduction_op_id(marmot_device_reduction_op_t op) {
    switch (op) {
    case MARMOT_DEVICE_REDUCTION_SUM:
        return MARMOT_OP_REDUCTION_SUM;
    case MARMOT_DEVICE_REDUCTION_MEAN:
        return MARMOT_OP_REDUCTION_MEAN;
    case MARMOT_DEVICE_REDUCTION_PROD:
        return MARMOT_OP_REDUCTION_PROD;
    case MARMOT_DEVICE_REDUCTION_MAX:
        return MARMOT_OP_REDUCTION_MAX;
    case MARMOT_DEVICE_REDUCTION_MIN:
        return MARMOT_OP_REDUCTION_MIN;
    case MARMOT_DEVICE_REDUCTION_ARGMAX:
        return MARMOT_OP_REDUCTION_ARGMAX;
    case MARMOT_DEVICE_REDUCTION_ARGMIN:
        return MARMOT_OP_REDUCTION_ARGMIN;
    case MARMOT_DEVICE_REDUCTION_ANY:
        return MARMOT_OP_REDUCTION_ANY;
    case MARMOT_DEVICE_REDUCTION_ALL:
        return MARMOT_OP_REDUCTION_ALL;
    case MARMOT_DEVICE_REDUCTION_VARIANCE:
        return MARMOT_OP_REDUCTION_VARIANCE;
    case MARMOT_DEVICE_REDUCTION_STD:
        return MARMOT_OP_REDUCTION_STD;
    case MARMOT_DEVICE_REDUCTION_NORM_L1:
        return MARMOT_OP_REDUCTION_NORM_L1;
    case MARMOT_DEVICE_REDUCTION_NORM_L2:
        return MARMOT_OP_REDUCTION_NORM_L2;
    default:
        return MARMOT_OP_INVALID;
    }
}

static inline marmot_device_reduction_op_t marmot_op_metadata_reduction_from_op_id(marmot_op_id_t op_id) {
    switch (op_id) {
    case MARMOT_OP_REDUCTION_SUM:
        return MARMOT_DEVICE_REDUCTION_SUM;
    case MARMOT_OP_REDUCTION_MEAN:
        return MARMOT_DEVICE_REDUCTION_MEAN;
    case MARMOT_OP_REDUCTION_PROD:
        return MARMOT_DEVICE_REDUCTION_PROD;
    case MARMOT_OP_REDUCTION_MAX:
        return MARMOT_DEVICE_REDUCTION_MAX;
    case MARMOT_OP_REDUCTION_MIN:
        return MARMOT_DEVICE_REDUCTION_MIN;
    case MARMOT_OP_REDUCTION_ARGMAX:
        return MARMOT_DEVICE_REDUCTION_ARGMAX;
    case MARMOT_OP_REDUCTION_ARGMIN:
        return MARMOT_DEVICE_REDUCTION_ARGMIN;
    case MARMOT_OP_REDUCTION_ANY:
        return MARMOT_DEVICE_REDUCTION_ANY;
    case MARMOT_OP_REDUCTION_ALL:
        return MARMOT_DEVICE_REDUCTION_ALL;
    case MARMOT_OP_REDUCTION_VARIANCE:
        return MARMOT_DEVICE_REDUCTION_VARIANCE;
    case MARMOT_OP_REDUCTION_STD:
        return MARMOT_DEVICE_REDUCTION_STD;
    case MARMOT_OP_REDUCTION_NORM_L1:
        return MARMOT_DEVICE_REDUCTION_NORM_L1;
    case MARMOT_OP_REDUCTION_NORM_L2:
        return MARMOT_DEVICE_REDUCTION_NORM_L2;
    default:
        return MARMOT_DEVICE_REDUCTION_COUNT;
    }
}

static inline marmot_op_id_t marmot_op_metadata_unary_op_id(marmot_device_unary_op_t op) {
    switch (op) {
    case MARMOT_DEVICE_UNARY_ABS:
        return MARMOT_OP_ABS;
    case MARMOT_DEVICE_UNARY_NEG:
        return MARMOT_OP_NEG;
    case MARMOT_DEVICE_UNARY_SIGN:
        return MARMOT_OP_SIGN;
    case MARMOT_DEVICE_UNARY_SQRT:
        return MARMOT_OP_SQRT;
    case MARMOT_DEVICE_UNARY_EXP:
        return MARMOT_OP_EXP;
    case MARMOT_DEVICE_UNARY_LOG:
        return MARMOT_OP_LOG;
    case MARMOT_DEVICE_UNARY_BITWISE_NOT:
        return MARMOT_OP_BITWISE_NOT;
    case MARMOT_DEVICE_UNARY_RELU:
        return MARMOT_OP_RELU;
    case MARMOT_DEVICE_UNARY_GELU:
        return MARMOT_OP_GELU;
    case MARMOT_DEVICE_UNARY_GELU_TANH:
        return MARMOT_OP_GELU_TANH;
    case MARMOT_DEVICE_UNARY_SILU:
        return MARMOT_OP_SILU;
    case MARMOT_DEVICE_UNARY_SIGMOID:
        return MARMOT_OP_SIGMOID;
    case MARMOT_DEVICE_UNARY_TANH:
        return MARMOT_OP_TANH;
    case MARMOT_DEVICE_UNARY_MISH:
        return MARMOT_OP_MISH;
    case MARMOT_DEVICE_UNARY_ELU:
        return MARMOT_OP_ELU;
    case MARMOT_DEVICE_UNARY_SELU:
        return MARMOT_OP_SELU;
    case MARMOT_DEVICE_UNARY_LEAKY_RELU:
        return MARMOT_OP_LEAKY_RELU;
    case MARMOT_DEVICE_UNARY_PRELU:
        return MARMOT_OP_PRELU;
    default:
        return MARMOT_OP_INVALID;
    }
}

static inline marmot_device_unary_op_t marmot_op_metadata_unary_from_op_id(marmot_op_id_t op_id) {
    switch (op_id) {
    case MARMOT_OP_ABS:
        return MARMOT_DEVICE_UNARY_ABS;
    case MARMOT_OP_NEG:
        return MARMOT_DEVICE_UNARY_NEG;
    case MARMOT_OP_SIGN:
        return MARMOT_DEVICE_UNARY_SIGN;
    case MARMOT_OP_SQRT:
        return MARMOT_DEVICE_UNARY_SQRT;
    case MARMOT_OP_EXP:
        return MARMOT_DEVICE_UNARY_EXP;
    case MARMOT_OP_LOG:
        return MARMOT_DEVICE_UNARY_LOG;
    case MARMOT_OP_BITWISE_NOT:
        return MARMOT_DEVICE_UNARY_BITWISE_NOT;
    case MARMOT_OP_RELU:
        return MARMOT_DEVICE_UNARY_RELU;
    case MARMOT_OP_GELU:
        return MARMOT_DEVICE_UNARY_GELU;
    case MARMOT_OP_GELU_TANH:
        return MARMOT_DEVICE_UNARY_GELU_TANH;
    case MARMOT_OP_SILU:
        return MARMOT_DEVICE_UNARY_SILU;
    case MARMOT_OP_SIGMOID:
        return MARMOT_DEVICE_UNARY_SIGMOID;
    case MARMOT_OP_TANH:
        return MARMOT_DEVICE_UNARY_TANH;
    case MARMOT_OP_MISH:
        return MARMOT_DEVICE_UNARY_MISH;
    case MARMOT_OP_ELU:
        return MARMOT_DEVICE_UNARY_ELU;
    case MARMOT_OP_SELU:
        return MARMOT_DEVICE_UNARY_SELU;
    case MARMOT_OP_LEAKY_RELU:
        return MARMOT_DEVICE_UNARY_LEAKY_RELU;
    case MARMOT_OP_PRELU:
        return MARMOT_DEVICE_UNARY_PRELU;
    default:
        return MARMOT_DEVICE_UNARY_COUNT;
    }
}

static inline marmot_op_id_t marmot_op_metadata_binary_op_id(marmot_device_binary_op_t op) {
    switch (op) {
    case MARMOT_DEVICE_BINARY_ADD:
        return MARMOT_OP_ADD;
    case MARMOT_DEVICE_BINARY_MUL:
        return MARMOT_OP_MUL;
    case MARMOT_DEVICE_BINARY_SWIGLU:
        return MARMOT_OP_SWIGLU;
    case MARMOT_DEVICE_BINARY_GEGLU:
        return MARMOT_OP_GEGLU;
    case MARMOT_DEVICE_BINARY_SUB:
        return MARMOT_OP_SUB;
    case MARMOT_DEVICE_BINARY_DIV:
        return MARMOT_OP_DIV;
    case MARMOT_DEVICE_BINARY_MIN:
        return MARMOT_OP_MIN;
    case MARMOT_DEVICE_BINARY_MAX:
        return MARMOT_OP_MAX;
    case MARMOT_DEVICE_BINARY_POW:
        return MARMOT_OP_POW;
    case MARMOT_DEVICE_BINARY_MOD:
        return MARMOT_OP_MOD;
    case MARMOT_DEVICE_BINARY_BITWISE_AND:
        return MARMOT_OP_BITWISE_AND;
    case MARMOT_DEVICE_BINARY_BITWISE_OR:
        return MARMOT_OP_BITWISE_OR;
    case MARMOT_DEVICE_BINARY_BITWISE_XOR:
        return MARMOT_OP_BITWISE_XOR;
    case MARMOT_DEVICE_BINARY_BITWISE_SHIFT_LEFT:
        return MARMOT_OP_BITWISE_SHL;
    case MARMOT_DEVICE_BINARY_BITWISE_SHIFT_RIGHT:
        return MARMOT_OP_BITWISE_SHR;
    case MARMOT_DEVICE_BINARY_BITWISE_SHIFT_RIGHT_LOGICAL:
        return MARMOT_OP_BITWISE_SHR_LOGICAL;
    case MARMOT_DEVICE_BINARY_COMPARE_EQ:
        return MARMOT_OP_COMPARE_EQ;
    case MARMOT_DEVICE_BINARY_COMPARE_NE:
        return MARMOT_OP_COMPARE_NE;
    case MARMOT_DEVICE_BINARY_COMPARE_LT:
        return MARMOT_OP_COMPARE_LT;
    case MARMOT_DEVICE_BINARY_COMPARE_LE:
        return MARMOT_OP_COMPARE_LE;
    case MARMOT_DEVICE_BINARY_COMPARE_GT:
        return MARMOT_OP_COMPARE_GT;
    case MARMOT_DEVICE_BINARY_COMPARE_GE:
        return MARMOT_OP_COMPARE_GE;
    default:
        return MARMOT_OP_INVALID;
    }
}

static inline marmot_device_binary_op_t marmot_op_metadata_binary_from_op_id(marmot_op_id_t op_id) {
    switch (op_id) {
    case MARMOT_OP_ADD:
        return MARMOT_DEVICE_BINARY_ADD;
    case MARMOT_OP_MUL:
        return MARMOT_DEVICE_BINARY_MUL;
    case MARMOT_OP_SWIGLU:
        return MARMOT_DEVICE_BINARY_SWIGLU;
    case MARMOT_OP_GEGLU:
        return MARMOT_DEVICE_BINARY_GEGLU;
    case MARMOT_OP_SUB:
        return MARMOT_DEVICE_BINARY_SUB;
    case MARMOT_OP_DIV:
        return MARMOT_DEVICE_BINARY_DIV;
    case MARMOT_OP_MIN:
        return MARMOT_DEVICE_BINARY_MIN;
    case MARMOT_OP_MAX:
        return MARMOT_DEVICE_BINARY_MAX;
    case MARMOT_OP_POW:
        return MARMOT_DEVICE_BINARY_POW;
    case MARMOT_OP_MOD:
        return MARMOT_DEVICE_BINARY_MOD;
    case MARMOT_OP_BITWISE_AND:
        return MARMOT_DEVICE_BINARY_BITWISE_AND;
    case MARMOT_OP_BITWISE_OR:
        return MARMOT_DEVICE_BINARY_BITWISE_OR;
    case MARMOT_OP_BITWISE_XOR:
        return MARMOT_DEVICE_BINARY_BITWISE_XOR;
    case MARMOT_OP_BITWISE_SHL:
        return MARMOT_DEVICE_BINARY_BITWISE_SHIFT_LEFT;
    case MARMOT_OP_BITWISE_SHR:
        return MARMOT_DEVICE_BINARY_BITWISE_SHIFT_RIGHT;
    case MARMOT_OP_BITWISE_SHR_LOGICAL:
        return MARMOT_DEVICE_BINARY_BITWISE_SHIFT_RIGHT_LOGICAL;
    case MARMOT_OP_COMPARE_EQ:
        return MARMOT_DEVICE_BINARY_COMPARE_EQ;
    case MARMOT_OP_COMPARE_NE:
        return MARMOT_DEVICE_BINARY_COMPARE_NE;
    case MARMOT_OP_COMPARE_LT:
        return MARMOT_DEVICE_BINARY_COMPARE_LT;
    case MARMOT_OP_COMPARE_LE:
        return MARMOT_DEVICE_BINARY_COMPARE_LE;
    case MARMOT_OP_COMPARE_GT:
        return MARMOT_DEVICE_BINARY_COMPARE_GT;
    case MARMOT_OP_COMPARE_GE:
        return MARMOT_DEVICE_BINARY_COMPARE_GE;
    default:
        return MARMOT_DEVICE_BINARY_COUNT;
    }
}

static inline marmot_op_id_t marmot_op_metadata_ternary_op_id(marmot_device_ternary_op_t op) {
    switch (op) {
    case MARMOT_DEVICE_TERNARY_FMA:
        return MARMOT_OP_FMA;
    case MARMOT_DEVICE_TERNARY_WHERE:
        return MARMOT_OP_WHERE;
    default:
        return MARMOT_OP_INVALID;
    }
}

static inline marmot_device_ternary_op_t marmot_op_metadata_ternary_from_op_id(marmot_op_id_t op_id) {
    switch (op_id) {
    case MARMOT_OP_FMA:
        return MARMOT_DEVICE_TERNARY_FMA;
    case MARMOT_OP_WHERE:
        return MARMOT_DEVICE_TERNARY_WHERE;
    default:
        return MARMOT_DEVICE_TERNARY_COUNT;
    }
}

static inline bool marmot_op_metadata_unary_requires_params(marmot_device_unary_op_t op) {
    switch (op) {
    case MARMOT_DEVICE_UNARY_ELU:
        return true;
    case MARMOT_DEVICE_UNARY_SELU:
        return true;
    case MARMOT_DEVICE_UNARY_LEAKY_RELU:
        return true;
    case MARMOT_DEVICE_UNARY_PRELU:
        return true;
    default:
        return false;
    }
}

static inline bool marmot_op_metadata_unary_supports_bias(marmot_device_unary_op_t op) {
    switch (op) {
    case MARMOT_DEVICE_UNARY_RELU:
        return true;
    case MARMOT_DEVICE_UNARY_GELU:
        return true;
    case MARMOT_DEVICE_UNARY_GELU_TANH:
        return true;
    case MARMOT_DEVICE_UNARY_SILU:
        return true;
    case MARMOT_DEVICE_UNARY_SIGMOID:
        return true;
    case MARMOT_DEVICE_UNARY_TANH:
        return true;
    case MARMOT_DEVICE_UNARY_MISH:
        return true;
    case MARMOT_DEVICE_UNARY_ELU:
        return true;
    case MARMOT_DEVICE_UNARY_SELU:
        return true;
    case MARMOT_DEVICE_UNARY_LEAKY_RELU:
        return true;
    case MARMOT_DEVICE_UNARY_PRELU:
        return true;
    default:
        return false;
    }
}

typedef struct {
    bool requires_input;
    bool allow_param_tensor;
    bool alpha_default_on_zero;
    bool beta_default_on_zero;
    bool has_default_alpha;
    bool has_default_beta;
    float alpha_default;
    float beta_default;
} marmot_unary_params_metadata_t;

static constexpr marmot_unary_params_metadata_t marmot_unary_params_metadata_default = {
    false, true, false, false, false, false, 0.0f, 0.0f,
};

static constexpr marmot_unary_params_metadata_t marmot_unary_params_metadata[MARMOT_DEVICE_UNARY_COUNT] = {
    [MARMOT_DEVICE_UNARY_ABS] =
        {
            .requires_input = false,
            .allow_param_tensor = true,
            .alpha_default_on_zero = false,
            .beta_default_on_zero = false,
            .has_default_alpha = false,
            .has_default_beta = false,
            .alpha_default = 0.0f,
            .beta_default = 0.0f,
        },
    [MARMOT_DEVICE_UNARY_NEG] =
        {
            .requires_input = false,
            .allow_param_tensor = true,
            .alpha_default_on_zero = false,
            .beta_default_on_zero = false,
            .has_default_alpha = false,
            .has_default_beta = false,
            .alpha_default = 0.0f,
            .beta_default = 0.0f,
        },
    [MARMOT_DEVICE_UNARY_SIGN] =
        {
            .requires_input = false,
            .allow_param_tensor = true,
            .alpha_default_on_zero = false,
            .beta_default_on_zero = false,
            .has_default_alpha = false,
            .has_default_beta = false,
            .alpha_default = 0.0f,
            .beta_default = 0.0f,
        },
    [MARMOT_DEVICE_UNARY_SQRT] =
        {
            .requires_input = false,
            .allow_param_tensor = true,
            .alpha_default_on_zero = false,
            .beta_default_on_zero = false,
            .has_default_alpha = false,
            .has_default_beta = false,
            .alpha_default = 0.0f,
            .beta_default = 0.0f,
        },
    [MARMOT_DEVICE_UNARY_EXP] =
        {
            .requires_input = false,
            .allow_param_tensor = true,
            .alpha_default_on_zero = false,
            .beta_default_on_zero = false,
            .has_default_alpha = false,
            .has_default_beta = false,
            .alpha_default = 0.0f,
            .beta_default = 0.0f,
        },
    [MARMOT_DEVICE_UNARY_LOG] =
        {
            .requires_input = false,
            .allow_param_tensor = true,
            .alpha_default_on_zero = false,
            .beta_default_on_zero = false,
            .has_default_alpha = false,
            .has_default_beta = false,
            .alpha_default = 0.0f,
            .beta_default = 0.0f,
        },
    [MARMOT_DEVICE_UNARY_BITWISE_NOT] =
        {
            .requires_input = false,
            .allow_param_tensor = true,
            .alpha_default_on_zero = false,
            .beta_default_on_zero = false,
            .has_default_alpha = false,
            .has_default_beta = false,
            .alpha_default = 0.0f,
            .beta_default = 0.0f,
        },
    [MARMOT_DEVICE_UNARY_RELU] =
        {
            .requires_input = false,
            .allow_param_tensor = true,
            .alpha_default_on_zero = false,
            .beta_default_on_zero = false,
            .has_default_alpha = false,
            .has_default_beta = false,
            .alpha_default = 0.0f,
            .beta_default = 0.0f,
        },
    [MARMOT_DEVICE_UNARY_GELU] =
        {
            .requires_input = false,
            .allow_param_tensor = true,
            .alpha_default_on_zero = false,
            .beta_default_on_zero = false,
            .has_default_alpha = false,
            .has_default_beta = false,
            .alpha_default = 0.0f,
            .beta_default = 0.0f,
        },
    [MARMOT_DEVICE_UNARY_GELU_TANH] =
        {
            .requires_input = false,
            .allow_param_tensor = true,
            .alpha_default_on_zero = false,
            .beta_default_on_zero = false,
            .has_default_alpha = false,
            .has_default_beta = false,
            .alpha_default = 0.0f,
            .beta_default = 0.0f,
        },
    [MARMOT_DEVICE_UNARY_SILU] =
        {
            .requires_input = false,
            .allow_param_tensor = true,
            .alpha_default_on_zero = false,
            .beta_default_on_zero = false,
            .has_default_alpha = false,
            .has_default_beta = false,
            .alpha_default = 0.0f,
            .beta_default = 0.0f,
        },
    [MARMOT_DEVICE_UNARY_SIGMOID] =
        {
            .requires_input = false,
            .allow_param_tensor = true,
            .alpha_default_on_zero = false,
            .beta_default_on_zero = false,
            .has_default_alpha = false,
            .has_default_beta = false,
            .alpha_default = 0.0f,
            .beta_default = 0.0f,
        },
    [MARMOT_DEVICE_UNARY_TANH] =
        {
            .requires_input = false,
            .allow_param_tensor = true,
            .alpha_default_on_zero = false,
            .beta_default_on_zero = false,
            .has_default_alpha = false,
            .has_default_beta = false,
            .alpha_default = 0.0f,
            .beta_default = 0.0f,
        },
    [MARMOT_DEVICE_UNARY_MISH] =
        {
            .requires_input = false,
            .allow_param_tensor = true,
            .alpha_default_on_zero = false,
            .beta_default_on_zero = false,
            .has_default_alpha = false,
            .has_default_beta = false,
            .alpha_default = 0.0f,
            .beta_default = 0.0f,
        },
    [MARMOT_DEVICE_UNARY_ELU] =
        {
            .requires_input = false,
            .allow_param_tensor = true,
            .alpha_default_on_zero = false,
            .beta_default_on_zero = false,
            .has_default_alpha = true,
            .has_default_beta = false,
            .alpha_default = 1.0f,
            .beta_default = 0.0f,
        },
    [MARMOT_DEVICE_UNARY_SELU] =
        {
            .requires_input = false,
            .allow_param_tensor = true,
            .alpha_default_on_zero = true,
            .beta_default_on_zero = true,
            .has_default_alpha = true,
            .has_default_beta = true,
            .alpha_default = 1.6732632423543772f,
            .beta_default = 1.0507009873554805f,
        },
    [MARMOT_DEVICE_UNARY_LEAKY_RELU] =
        {
            .requires_input = false,
            .allow_param_tensor = true,
            .alpha_default_on_zero = true,
            .beta_default_on_zero = false,
            .has_default_alpha = true,
            .has_default_beta = false,
            .alpha_default = 0.01f,
            .beta_default = 0.0f,
        },
    [MARMOT_DEVICE_UNARY_PRELU] = {
        .requires_input = true,
        .allow_param_tensor = false,
        .alpha_default_on_zero = false,
        .beta_default_on_zero = false,
        .has_default_alpha = false,
        .has_default_beta = false,
        .alpha_default = 0.0f,
        .beta_default = 0.0f,
    },
};

static inline marmot_unary_params_metadata_t marmot_op_metadata_unary_params(marmot_device_unary_op_t op) {
    if (op < 0 || op >= MARMOT_DEVICE_UNARY_COUNT) {
        return marmot_unary_params_metadata_default;
    }
    return marmot_unary_params_metadata[op];
}

static inline marmot_qscheme_id_t marmot_op_metadata_quant_kind_to_qscheme(marmot_quant_kind_t kind) {
    switch (kind) {
    case MARMOT_QUANT_KIND_GENERIC:
        return MARMOT_QSCHEME_NONE;
    case MARMOT_QUANT_KIND_Q4_0:
        return MARMOT_QSCHEME_Q4_0;
    case MARMOT_QUANT_KIND_Q4_1:
        return MARMOT_QSCHEME_Q4_1;
    case MARMOT_QUANT_KIND_Q5_0:
        return MARMOT_QSCHEME_Q5_0;
    case MARMOT_QUANT_KIND_Q5_1:
        return MARMOT_QSCHEME_Q5_1;
    case MARMOT_QUANT_KIND_Q8_0:
        return MARMOT_QSCHEME_Q8_0;
    case MARMOT_QUANT_KIND_Q8_1:
        return MARMOT_QSCHEME_Q8_1;
    case MARMOT_QUANT_KIND_Q2_K:
        return MARMOT_QSCHEME_Q2_K;
    case MARMOT_QUANT_KIND_Q3_K:
        return MARMOT_QSCHEME_Q3_K;
    case MARMOT_QUANT_KIND_Q4_K:
        return MARMOT_QSCHEME_Q4_K;
    case MARMOT_QUANT_KIND_Q5_K:
        return MARMOT_QSCHEME_Q5_K;
    case MARMOT_QUANT_KIND_Q6_K:
        return MARMOT_QSCHEME_Q6_K;
    case MARMOT_QUANT_KIND_Q8_K:
        return MARMOT_QSCHEME_Q8_K;
    default:
        return MARMOT_QSCHEME_NONE;
    }
}

static inline marmot_quant_kind_t marmot_op_metadata_quant_kind_from_qscheme(marmot_qscheme_id_t qscheme) {
    switch (qscheme) {
    case MARMOT_QSCHEME_NONE:
        return MARMOT_QUANT_KIND_GENERIC;
    case MARMOT_QSCHEME_Q4_0:
        return MARMOT_QUANT_KIND_Q4_0;
    case MARMOT_QSCHEME_Q4_1:
        return MARMOT_QUANT_KIND_Q4_1;
    case MARMOT_QSCHEME_Q5_0:
        return MARMOT_QUANT_KIND_Q5_0;
    case MARMOT_QSCHEME_Q5_1:
        return MARMOT_QUANT_KIND_Q5_1;
    case MARMOT_QSCHEME_Q8_0:
        return MARMOT_QUANT_KIND_Q8_0;
    case MARMOT_QSCHEME_Q8_1:
        return MARMOT_QUANT_KIND_Q8_1;
    case MARMOT_QSCHEME_Q2_K:
        return MARMOT_QUANT_KIND_Q2_K;
    case MARMOT_QSCHEME_Q3_K:
        return MARMOT_QUANT_KIND_Q3_K;
    case MARMOT_QSCHEME_Q4_K:
        return MARMOT_QUANT_KIND_Q4_K;
    case MARMOT_QSCHEME_Q5_K:
        return MARMOT_QUANT_KIND_Q5_K;
    case MARMOT_QSCHEME_Q6_K:
        return MARMOT_QUANT_KIND_Q6_K;
    case MARMOT_QSCHEME_Q8_K:
        return MARMOT_QUANT_KIND_Q8_K;
    default:
        return MARMOT_QUANT_KIND_GENERIC;
    }
}

#ifdef __cplusplus
}
#endif

#endif // MARMOT_OP_METADATA_GEN_H
