// SPDX-License-Identifier: MIT
// This file was autogenerated by scripts/codegen/gen_kernels.py; DO NOT EDIT.

#ifndef MARMOT_OP_SIGNATURE_HASH_GEN_H
#define MARMOT_OP_SIGNATURE_HASH_GEN_H

#include "marmot/graph/op_signature.h"
#include "marmot/traits_ids.gen.h"

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// FNV-1a hash for op signatures
static inline uint64_t marmot_hash_op_signature(const marmot_op_signature_t *sig) {
    uint64_t h = 14695981039346656037ULL; // FNV-1a offset basis
    const uint64_t prime = 1099511628211ULL;

    h ^= (uint64_t)sig->op_id;
    h *= prime;
    h ^= (uint64_t)sig->profile_id;
    h *= prime;
    h ^= (uint64_t)sig->matmul_layout;
    h *= prime;
    h ^= (uint64_t)sig->input_dtype;
    h *= prime;
    h ^= (uint64_t)sig->weight_dtype;
    h *= prime;
    h ^= (uint64_t)sig->output_dtype;
    h *= prime;
    h ^= (uint64_t)sig->accum_dtype;
    h *= prime;
    h ^= (uint64_t)sig->qscheme_id;
    h *= prime;
    h ^= (uint64_t)sig->quant_block.block_size;
    h *= prime;
    h ^= (uint64_t)sig->quant_block.group_size;
    h *= prime;
    h ^= (uint64_t)sig->quant_block.scale_dtype;
    h *= prime;
    h ^= (uint64_t)sig->quant_block.zero_point_dtype;
    h *= prime;
    h ^= (uint64_t)sig->weight_layout;
    h *= prime;
    h ^= (uint64_t)sig->stride_mode;
    h *= prime;
    h ^= (uint64_t)sig->variant_flags;
    h *= prime;
    h ^= (uint64_t)sig->epilogue_flags;
    h *= prime;
    h ^= (uint64_t)sig->activation;
    h *= prime;

    switch (sig->op_id) {
    case MARMOT_OP_MATMUL:
    case MARMOT_OP_LINEAR:
    case MARMOT_OP_QKV_ROPE:
        h ^= (uint64_t)sig->dims.matmul.M;
        h *= prime;
        h ^= (uint64_t)sig->dims.matmul.N;
        h *= prime;
        h ^= (uint64_t)sig->dims.matmul.K;
        h *= prime;
        break;
    case MARMOT_OP_LAYERNORM:
    case MARMOT_OP_RMS_NORM:
        h ^= (uint64_t)sig->dims.layernorm.n;
        h *= prime;
        h ^= (uint64_t)sig->dims.layernorm.d;
        h *= prime;
        break;
    case MARMOT_OP_ROPE:
        h ^= (uint64_t)sig->dims.rope.seq_len;
        h *= prime;
        h ^= (uint64_t)sig->dims.rope.n_rot;
        h *= prime;
        break;
    case MARMOT_OP_SOFTMAX:
        h ^= (uint64_t)sig->dims.softmax.axis_size;
        h *= prime;
        h ^= (uint64_t)sig->dims.softmax.inner_stride;
        h *= prime;
        h ^= (uint64_t)sig->dims.softmax.outer_size;
        h *= prime;
        h ^= (uint64_t)sig->dims.softmax.row_count;
        h *= prime;
        break;
    default:
        h ^= (uint64_t)sig->dims.elementwise.n_elems;
        h *= prime;
        break;
    }

    return h;
}

#ifdef __cplusplus
}
#endif

#endif // MARMOT_OP_SIGNATURE_HASH_GEN_H
