// Auto-generated by tests/golden/generate_backend_golden.py. Do not edit manually.
#pragma once
#include "marmot/ops_types.h"
#include "marmot/types.h"

#include <stddef.h>
#include <stdint.h>

// Elementwise operation golden data

static const struct {
    size_t length;
    float a[4];
    float b[4];
    float add[4];
    float sub[4];
    float mul[4];
    float div[4];
    float minv[4];
    float maxv[4];
    double a_f64[4];
    double b_f64[4];
    double add_f64[4];
    double sub_f64[4];
    double mul_f64[4];
    double div_f64[4];
    double minv_f64[4];
    double maxv_f64[4];
} g_elementwise_fp32 = {
    4,
    {-2, -0.5, 1, 3.5},
    {4, -1.5, 2, -0.5},
    {2, -2, 3, 3},
    {-6, 1, -1, 4},
    {-8, 0.75, 2, -1.75},
    {-0.5, 0.3333333333, 0.5, -7},
    {-2, -1.5, 1, -0.5},
    {4, -0.5, 2, 3.5},
    {-2, -0.5, 1, 3.5},
    {4, -1.5, 2, -0.5},
    {2, -2, 3, 3},
    {-6, 1, -1, 4},
    {-8, 0.75, 2, -1.75},
    {-0.5, 0.33333333333333331, 0.5, -7},
    {-2, -1.5, 1, -0.5},
    {4, -0.5, 2, 3.5},
};

static const struct {
    size_t length;
    float a[17];
    float b[17];
    float add[17];
    float sub[17];
    float mul[17];
    float div[17];
    float minv[17];
    float maxv[17];
} g_elementwise_fp32_wide = {
    17,
    {-8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8},
    {6.75, 5.96875, 5.1875, 4.40625, 3.625, 2.84375, 2.0625, 1.28125, 0.5, -0.28125, -1.0625, -1.84375, -2.625,
     -3.40625, -4.1875, -4.96875, -5.75},
    {-1.25, -1.03125, -0.8125, -0.59375, -0.375, -0.15625, 0.0625, 0.28125, 0.5, 0.71875, 0.9375, 1.15625, 1.375,
     1.59375, 1.8125, 2.03125, 2.25},
    {-14.75, -12.96875, -11.1875, -9.40625, -7.625, -5.84375, -4.0625, -2.28125, -0.5, 1.28125, 3.0625, 4.84375, 6.625,
     8.40625, 10.1875, 11.96875, 13.75},
    {-54, -41.78125, -31.125, -22.03125, -14.5, -8.53125, -4.125, -1.28125, 0, -0.28125, -2.125, -5.53125, -10.5,
     -17.03125, -25.125, -34.78125, -46},
    {-1.185185185, -1.172774869, -1.156626506, -1.134751773, -1.103448276, -1.054945055, -0.9696969697, -0.7804878049,
     0, -3.555555556, -1.882352941, -1.627118644, -1.523809524, -1.467889908, -1.432835821, -1.408805031, -1.391304348},
    {-8, -7, -6, -5, -4, -3, -2, -1, 0, -0.28125, -1.0625, -1.84375, -2.625, -3.40625, -4.1875, -4.96875, -5.75},
    {6.75, 5.96875, 5.1875, 4.40625, 3.625, 2.84375, 2.0625, 1.28125, 0.5, 1, 2, 3, 4, 5, 6, 7, 8},
};

static const struct {
    size_t length;
    float base[4];
    float exponent[4];
    float powv[4];
    float divisor[4];
    float modv[4];
    double base_f64[4];
    double exponent_f64[4];
    double powv_f64[4];
    double divisor_f64[4];
    double modv_f64[4];
} g_elementwise_powmod_fp32 = {
    4,
    {1.5, 2, 3.25, 4.5},
    {2, 3, 0.5, -1},
    {2.25, 8, 1.802775638, 0.2222222222},
    {0.75, 2.5, 1.25, 2},
    {0, 2, 0.75, 0.5},
    {1.5, 2, 3.25, 4.5},
    {2, 3, 0.5, -1},
    {2.25, 8, 1.8027756377319946, 0.22222222222222221},
    {0.75, 2.5, 1.25, 2},
    {0, 2, 0.75, 0.5},
};

static const struct {
    size_t length;
    float a[5];
    float b[5];
    float add[5];
    float sub[5];
    float mul[5];
    float div[5];
    float minv[5];
    float maxv[5];
} g_elementwise_fp16 = {
    5,
    {-3, -1, 0, 0.5, 1.75},
    {2, -0.5, 4, 1.5, -2},
    {-1, -1.5, 4, 2, -0.25},
    {-5, -0.5, -4, -1, 3.75},
    {-6, 0.5, 0, 0.75, -3.5},
    {-1.5, 2, 0, 0.3333333333, -0.875},
    {-3, -1, 0, 0.5, -2},
    {2, -0.5, 4, 1.5, 1.75},
};

static const struct {
    size_t length;
    float base[4];
    float exponent[4];
    float powv[4];
    float divisor[4];
    float modv[4];
} g_elementwise_powmod_fp16 = {
    4,
    {0.75, 1.5, 2, 2.5},
    {2, 1.5, 0.5, -1},
    {0.5625, 1.837117307, 1.414213562, 0.4},
    {0.5, 0.75, 1, 1.25},
    {0.25, 0, 0, 0},
};

static const struct {
    size_t length;
    float a[3];
    float b[3];
    float add[3];
    float sub[3];
    float mul[3];
    float div[3];
    float minv[3];
    float maxv[3];
} g_elementwise_bf16 = {
    3,
    {0.125, -0.25, 1.5},
    {2.5, -4, -0.75},
    {2.625, -4.25, 0.75},
    {-2.375, 3.75, 2.25},
    {0.3125, 1, -1.125},
    {0.05, 0.0625, -2},
    {0.125, -4, -0.75},
    {2.5, -0.25, 1.5},
};

static const struct {
    size_t length;
    float base[3];
    float exponent[3];
    float powv[3];
    float divisor[3];
    float modv[3];
} g_elementwise_powmod_bf16 = {
    3, {0.625, 1.25, 2.5}, {3, 0.5, -1}, {0.244140625, 1.118033989, 0.4}, {0.5, 0.75, 1.5}, {0.125, 0.5, 1},
};

static const struct {
    size_t length;
    int32_t a[4];
    int32_t b[4];
    int32_t add[4];
    int32_t sub[4];
    int32_t mul[4];
    int32_t div[4];
    int32_t minv[4];
    int32_t maxv[4];
} g_elementwise_i32 = {
    4,
    {9, -8, 7, -6},
    {3, -2, 5, -4},
    {12, -10, 12, -10},
    {6, -6, 2, -2},
    {27, 16, 35, 24},
    {3, 4, 1, 1},
    {3, -8, 5, -6},
    {9, -2, 7, -4},
};

static const struct {
    size_t length;
    int32_t a[24];
    int32_t b[24];
    int32_t add[24];
    int32_t sub[24];
    int32_t mul[24];
    int32_t div[24];
    int32_t minv[24];
    int32_t maxv[24];
    uint32_t shift_amt[24];
    int32_t shift_left[24];
    int32_t shift_right[24];
    uint32_t shift_right_logical[24];
} g_elementwise_i32_wide = {
    24,
    {-34, -31, -28, -25, -22, -19, -16, -13, -10, -7, -4, -1, 2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35},
    {5, -7, 9, -11, 13, -15, 17, -19, 21, -23, 25, -27, 29, -31, 33, -35, 37, -39, 41, -43, 45, -47, 49, -51},
    {-29, -38, -19, -36, -9, -34, 1, -32, 11, -30, 21, -28, 31, -26, 41, -24, 51, -22, 61, -20, 71, -18, 81, -16},
    {-39, -24, -37, -14, -35, -4, -33, 6, -31, 16, -29, 26, -27, 36, -25, 46, -23, 56, -21, 66, -19, 76, -17, 86},
    {-170, 217,  -252, 275,  -286, 285,  -272, 247,  -210, 161,   -100, 27,
     58,   -155, 264,  -385, 518,  -663, 820,  -989, 1170, -1363, 1568, -1785},
    {-6, 4, -3, 2, -1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {-34, -31, -28, -25, -22, -19, -16, -19, -10, -23, -4, -27, 2, -31, 8, -35, 14, -39, 20, -43, 26, -47, 32, -51},
    {5, -7, 9, -11, 13, -15, 17, -13, 21, -7, 25, -1, 29, 5, 33, 11, 37, 17, 41, 23, 45, 29, 49, 35},
    {3u, 8u, 13u, 18u, 23u, 28u, 1u, 6u, 11u, 16u, 21u, 26u, 31u, 4u, 9u, 14u, 19u, 24u, 29u, 2u, 7u, 12u, 17u, 22u},
    {-272, -7936, -229376, -6553600, -184549376, -805306368, -32,         -832, -20480, -458752, -8388608, -67108864,
     0,    80,    4096,    180224,   7340032,    285212672,  -2147483648, 92,   3328,   118784,  4194304,  146800640},
    {-5, -1, -1, -1, -1, -1, -8, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0},
    {536870907u, 16777215u, 524287u, 16383u, 511u, 15u, 2147483640u, 67108863u, 2097151u, 65535u, 2047u, 63u,
     0u,         0u,        0u,      0u,     0u,   0u,  0u,          5u,        0u,       0u,     0u,    0u},
};

static const struct {
    size_t length;
    int32_t pow_base[4];
    int32_t pow_exp[4];
    int32_t powv[4];
    int32_t mod_lhs[4];
    int32_t mod_rhs[4];
    int32_t modv[4];
    int32_t shift_lhs[4];
    uint32_t shift_amt[4];
    int32_t shift_left[4];
    int32_t shift_right[4];
    uint32_t shift_right_logical[4];
} g_elementwise_i32_ext = {
    4,
    {2, -3, 4, -5},
    {3, 2, 0, 1},
    {8, 9, 1, -5},
    {17, -19, 23, -25},
    {5, 4, 7, 6},
    {2, -3, 2, -1},
    {64, -64, 7, -9},
    {1u, 2u, 3u, 4u},
    {128, -256, 56, -144},
    {32, -16, 0, -1},
    {32u, 1073741808u, 0u, 268435455u},
};

static const struct {
    size_t length;
    uint32_t a[4];
    uint32_t b[4];
    uint32_t band[4];
    uint32_t bor[4];
    uint32_t bxor[4];
    uint32_t shift_amt[4];
    uint32_t shl[4];
    uint32_t shr[4];
} g_elementwise_bitwise_u32 = {
    4,
    {15u, 240u, 43690u, 13107u},
    {51u, 15u, 21845u, 52428u},
    {3u, 0u, 0u, 0u},
    {63u, 255u, 65535u, 65535u},
    {60u, 255u, 65535u, 65535u},
    {1u, 2u, 3u, 4u},
    {30u, 960u, 349520u, 209712u},
    {7u, 60u, 5461u, 819u},
};

static const struct {
    size_t length;
    uint32_t a[20];
    uint32_t b[20];
    uint32_t band[20];
    uint32_t bor[20];
    uint32_t bxor[20];
    uint32_t shift_amt[20];
    uint32_t shl[20];
    uint32_t shr[20];
} g_elementwise_bitwise_u32_wide = {
    20,
    {324508639u,  610839776u,  4275878552u, 2309737967u, 19088743u,   2779096485u, 1515870810u,
     4278255360u, 16711935u,   252645135u,  4042322160u, 858993459u,  3435973836u, 305419896u,
     3735928559u, 3199070221u, 2147483647u, 2147483649u, 1840700269u, 3681400539u},
    {715827883u,  3340530119u, 1908874353u, 3120378229u, 2395080266u, 1417023538u, 587294533u,
     2877943757u, 252645135u,  4042322160u, 1437226410u, 2857740885u, 2779096485u, 1515870810u,
     2576980377u, 1717986918u, 3097427154u, 1946620997u, 336026279u,  3579139413u},
    {33720971u,   67641536u,  1891899408u, 2309554533u, 132162u,    69468192u,   33571392u,
     2868965120u, 983055u,    0u,          1352683680u, 571548177u, 2223277188u, 303059544u,
     2559154313u, 639918084u, 949943506u,  1u,          67525157u,  3510965329u},
    {1006615551u, 3883728359u, 4292853497u, 3120561663u, 2414036847u, 4126651831u, 2069593951u,
     4287233997u, 268374015u,  4294967295u, 4126864890u, 3145186167u, 3991793133u, 1518231162u,
     3753754623u, 4277139055u, 4294967295u, 4094104645u, 2109201391u, 3749574623u},
    {972894580u,  3816086823u, 2400954089u, 811007130u,  2413904685u, 4057183639u, 2036022559u,
     1418268877u, 267390960u,  4294967295u, 2774181210u, 2573637990u, 1768515945u, 1215171618u,
     1194600310u, 3637220971u, 3345023789u, 4094104644u, 2041676234u, 238609294u},
    {0u, 3u, 6u, 9u, 12u, 15u, 18u, 21u, 24u, 27u, 30u, 1u, 4u, 7u, 10u, 13u, 16u, 19u, 22u, 25u},
    {324508639u,  591750912u,  3073287680u, 1469832704u, 878080000u,  3537010688u, 1768423424u,
     3758096384u, 4278190080u, 2013265920u, 0u,          1717986918u, 3435973824u, 439041024u,
     3069950976u, 3187777536u, 4294901760u, 524288u,     3678404608u, 3053453312u},
    {324508639u, 76354972u,  66810602u,  4511206u, 4660u,    84811u,  5782u,  2040u, 0u,   1u,
     3u,         429496729u, 214748364u, 2386092u, 3648367u, 390511u, 32767u, 4096u, 438u, 109u},
};

typedef struct {
    size_t len_affine;
    float values_affine[5];
    float absv[5];
    float negv[5];
    float signv[5];
    size_t len_math;
    float values_math[4];
    float sqrtv[4];
    float expv[4];
    float logv[4];
} llama_unary_float_golden_t;

static const llama_unary_float_golden_t g_unary_fp32 = {
    5,
    {-3.5, -1.25, 0, 0.75, 2.5},
    {3.5, 1.25, 0, 0.75, 2.5},
    {3.5, 1.25, -0, -0.75, -2.5},
    {-1, -1, 0, 1, 1},
    4,
    {0.25, 1, 2, 4},
    {0.5, 1, 1.414213562, 2},
    {1.284025417, 2.718281828, 7.389056099, 54.59815003},
    {-1.386294361, 0, 0.6931471806, 1.386294361},
};

static const llama_unary_float_golden_t g_unary_fp8 = {
    5,
    {-3.5, -1.25, 0, 0.75, 2.5},
    {3.5, 1.25, 0, 0.75, 2.5},
    {3.5, 1.25, -0, -0.75, -2.5},
    {-1, -1, 0, 1, 1},
    4,
    {0.25, 1, 2, 4},
    {0.5, 1, 1.414213562, 2},
    {1.284025417, 2.718281828, 7.389056099, 54.59815003},
    {-1.386294361, 0, 0.6931471806, 1.386294361},
};

static const llama_unary_float_golden_t g_unary_fp16 = {
    5,
    {-3.5, -1.25, 0, 0.75, 2.5},
    {3.5, 1.25, 0, 0.75, 2.5},
    {3.5, 1.25, -0, -0.75, -2.5},
    {-1, -1, 0, 1, 1},
    4,
    {0.25, 1, 2, 4},
    {0.5, 1, 1.414213562, 2},
    {1.284025417, 2.718281828, 7.389056099, 54.59815003},
    {-1.386294361, 0, 0.6931471806, 1.386294361},
};

static const llama_unary_float_golden_t g_unary_bf16 = {
    5,
    {-3.5, -1.25, 0, 0.75, 2.5},
    {3.5, 1.25, 0, 0.75, 2.5},
    {3.5, 1.25, -0, -0.75, -2.5},
    {-1, -1, 0, 1, 1},
    4,
    {0.25, 1, 2, 4},
    {0.5, 1, 1.414213562, 2},
    {1.284025417, 2.718281828, 7.389056099, 54.59815003},
    {-1.386294361, 0, 0.6931471806, 1.386294361},
};

static const struct {
    size_t length;
    int32_t values[5];
    int32_t absv[5];
    int32_t negv[5];
    int32_t signv[5];
    int32_t bitwise_not[5];
} g_unary_i32 = {
    5, {-9, -1, 0, 7, 15}, {9, 1, 0, 7, 15}, {9, 1, 0, -7, -15}, {-1, -1, 0, 1, 1}, {8, 0, -1, -8, -16},
};

static const struct {
    size_t length;
    uint32_t values[4];
    uint32_t signv[4];
    uint32_t bitwise_not[4];
} g_unary_u32 = {
    4,
    {0u, 1u, 2147483648u, 4294967295u},
    {0u, 1u, 1u, 1u},
    {4294967295u, 4294967294u, 2147483647u, 0u},
};

static const struct {
    size_t length;
    uint16_t a[4];
    uint16_t b[4];
    uint16_t add[4];
    uint16_t sub[4];
    uint16_t div[4];
} g_elementwise_u16 = {
    4,
    {65280u, 32752u, 4080u, 240u},
    {512u, 15u, 10u, 1u},
    {256u, 32767u, 4090u, 241u},
    {64768u, 32737u, 4070u, 239u},
    {127u, 2183u, 408u, 240u},
};

static const struct {
    size_t length;
    float a[4];
    float b[4];
    uint8_t eq[4];
    uint8_t lt[4];
    uint8_t ge[4];
} g_elementwise_cmp_float = {
    4, {1, -2, 3.5, 0}, {1, -3, 2, 0.5}, {1u, 0u, 0u, 0u}, {0u, 0u, 0u, 1u}, {1u, 1u, 1u, 0u},
};

static const struct {
    size_t length;
    int32_t a[4];
    int32_t b[4];
    uint8_t gt[4];
    uint8_t ne[4];
} g_elementwise_cmp_int = {
    4, {5, -3, 7, -9}, {4, -3, 10, -10}, {1u, 0u, 0u, 1u}, {1u, 0u, 1u, 1u},
};

static const struct {
    size_t length;
    float a[4];
    float b[4];
    float c[4];
    float expected[4];
} g_elementwise_fma = {
    4, {1, -2, 0.5, 3}, {2, 4, -1.5, 0.25}, {-0.5, 1, 0.25, -2}, {1.5, -7, -0.5, -1.25},
};

// Activation function golden data

static const struct {
    size_t rows;
    size_t cols;
    float input[6];
    float relu[6];
    float gelu[6];
    float silu[6];
    float gelu_tanh[6];
    float sigmoid[6];
    float tanh_v[6];
    float mish[6];
    float elu[6];
    float selu[6];
    float leaky[6];
    float prelu[6];
} g_activation = {
    2,
    3,
    {-6, -2.5, -0.25, 0, 0.5, 2},
    {0, 0, 0, 0, 0.5, 2},
    {-5.919525869e-09, -0.01552416331, -0.1003234186, 0, 0.3457312306, 1.954499736},
    {-0.01483573894, -0.1896454501, -0.1094558748, 0, 0.3112296656, 1.761594156},
    {-8.43964898e-11, -0.01508426609, -0.1003246493, 0, 0.3457140098, 1.954597694},
    {0.002472623157, 0.07585818002, 0.4378234991, 0.5, 0.6224593312, 0.880797078},
    {-0.9999877117, -0.9866142982, -0.2449186624, 0, 0.4621171573, 0.9640275801},
    {-0.01485408048, -0.1968162039, -0.1299269637, 0, 0.3752452113, 1.94395896},
    {-1.097273373, -1.009706502, -0.2433191386, 0, 0.5, 2},
    {-1.753741448, -1.613785759, -0.3888901975, 0, 0.5253504937, 2.101401975},
    {-0.12, -0.05, -0.005, 0, 0.5, 2},
    {-1.5, -0.625, -0.0625, 0, 0.5, 2},
};

// Normalization golden data

static const struct {
    size_t rows;
    size_t cols;
    float input[6];
    float weight[3];
    float bias[3];
    float eps;
    float expected_affine[6];
    float expected_no_affine[6];
} g_layernorm = {
    2,
    3,
    {1, 2, 3, -2, -4, -6},
    {1, 1.5, 0.5},
    {0.1, -0.2, 0.3},
    1e-05,
    {-1.124735686, -0.2, 0.912367843, 1.324742575, -0.2, -0.3123712875},
    {-1.224735686, 0, 1.224735686, 1.224742575, 0, -1.224742575},
};

static const struct {
    size_t rows;
    size_t cols;
    float input[8];
    float weight[4];
    float eps;
    float expected[8];
} g_rmsnorm = {
    2,
    4,
    {0.5, -1, 2, -4, 1.5, -3, 6, -2},
    {0.5, 1, 1.5, 2},
    1e-05,
    {0.1084651268, -0.4338605073, 1.301581522, -3.470884058, 0.209529007, -0.8381160279, 2.514348084, -1.117488037},
};

// Softmax golden data

static const struct {
    size_t ndim;
    size_t shape[2];
    float input[6];
    float expected_axis_last[6];
    float expected_axis0[6];
    double input_f64[6];
    double expected_axis_last_f64[6];
    double expected_axis0_f64[6];
} g_softmax = {
    2,
    {2, 3},
    {1, 5, 2, -1, -2, -3},
    {0.01714782555, 0.9362395519, 0.04661262258, 0.6652409558, 0.2447284711, 0.09003057317},
    {0.880797078, 0.9990889488, 0.9933071491, 0.119202922, 0.0009110511944, 0.006692850924},
    {1, 5, 2, -1, -2, -3},
    {0.017147825545520391, 0.93623955187650576, 0.046612622577973897, 0.66524095577482178, 0.24472847105479764,
     0.090030573170380462},
    {0.88079707797788231, 0.9990889488055994, 0.99330714907571527, 0.11920292202211755, 0.00091105119440064539,
     0.0066928509242848563},
};

// Reduction golden data

static const struct {
    size_t ndim;
    size_t shape[2];
    float input[6];
    float sum_all;
    float mean_all;
    float prod_all;
    float max_all;
    float min_all;
    uint64_t argmax_all;
    uint64_t argmin_all;
    float any_all;
    float all_all;
    float variance_all;
    float std_all;
    float norm_l1_all;
    float norm_l2_all;
    float sum_axis0[3];
    float sum_axis1[2];
    float mean_axis0[3];
    float mean_axis1[2];
    float max_axis0[3];
    float max_axis1[2];
    float min_axis0[3];
    float min_axis1[2];
    uint64_t argmax_axis0[3];
    uint64_t argmax_axis1[2];
    uint64_t argmin_axis0[3];
    uint64_t argmin_axis1[2];
    float any_axis0[3];
    float all_axis1[2];
    double input_f64[6];
    double sum_all_f64;
    double mean_all_f64;
    double prod_all_f64;
    double max_all_f64;
    double min_all_f64;
    double any_all_f64;
    double all_all_f64;
    double variance_all_f64;
    double std_all_f64;
    double norm_l1_all_f64;
    double norm_l2_all_f64;
    double sum_axis0_f64[3];
    double sum_axis1_f64[2];
    double mean_axis0_f64[3];
    double mean_axis1_f64[2];
    double max_axis0_f64[3];
    double max_axis1_f64[2];
    double min_axis0_f64[3];
    double min_axis1_f64[2];
    double any_axis0_f64[3];
    double all_axis1_f64[2];
} g_reduction_fp32 = {
    2,
    {2, 3},
    {1.5, -2, 3, -4.5, 0.25, 2.5},
    0.75,
    0.125,
    25.3125,
    3,
    -4.5,
    UINT64_C(2),
    UINT64_C(3),
    1,
    1,
    6.953125,
    2.636877889,
    13.75,
    6.466258578,
    {-3, -1.75, 5.5},
    {2.5, -1.75},
    {-1.5, -0.875, 2.75},
    {0.8333333333, -0.5833333333},
    {1.5, 0.25, 3},
    {3, 2.5},
    {-4.5, -2, 2.5},
    {-2, -4.5},
    {UINT64_C(0), UINT64_C(1), UINT64_C(0)},
    {UINT64_C(2), UINT64_C(2)},
    {UINT64_C(1), UINT64_C(0), UINT64_C(1)},
    {UINT64_C(1), UINT64_C(0)},
    {1, 1, 1},
    {1, 1},
    {1.5, -2, 3, -4.5, 0.25, 2.5},
    0.75,
    0.125,
    25.3125,
    3,
    -4.5,
    1,
    1,
    6.953125,
    2.6368778887161235,
    13.75,
    6.4662585781887811,
    {-3, -1.75, 5.5},
    {2.5, -1.75},
    {-1.5, -0.875, 2.75},
    {0.83333333333333337, -0.58333333333333337},
    {1.5, 0.25, 3},
    {3, 2.5},
    {-4.5, -2, 2.5},
    {-2, -4.5},
    {1, 1, 1},
    {1, 1},
};

static const struct {
    size_t ndim;
    size_t shape[2];
    int32_t input[6];
    int32_t sum_all;
    int32_t prod_all;
    int32_t max_all;
    int32_t min_all;
    uint64_t argmax_all;
    uint64_t argmin_all;
    int32_t any_all;
    int32_t all_all;
    int32_t sum_axis0[3];
    int32_t sum_axis1[2];
    int32_t max_axis0[3];
    int32_t max_axis1[2];
    int32_t min_axis0[3];
    int32_t min_axis1[2];
    uint64_t argmax_axis0[3];
    uint64_t argmax_axis1[2];
    uint64_t argmin_axis0[3];
    uint64_t argmin_axis1[2];
    int32_t any_axis0[3];
    int32_t all_axis1[2];
} g_reduction_i32 = {
    2,
    {2, 3},
    {12, 0, 3, -2, 5, -9},
    9,
    0,
    12,
    -9,
    UINT64_C(0),
    UINT64_C(5),
    1,
    0,
    {10, 5, -6},
    {15, -6},
    {12, 5, 3},
    {12, 5},
    {-2, 0, -9},
    {0, -9},
    {UINT64_C(0), UINT64_C(1), UINT64_C(0)},
    {UINT64_C(0), UINT64_C(1)},
    {UINT64_C(1), UINT64_C(0), UINT64_C(1)},
    {UINT64_C(1), UINT64_C(2)},
    {1, 1, 1},
    {0, 1},
};

static const struct {
    size_t ndim;
    size_t shape[2];
    int16_t input[6];
    int16_t sum_all;
    int16_t prod_all;
    int16_t max_all;
    int16_t min_all;
    uint64_t argmax_all;
    uint64_t argmin_all;
    int16_t any_all;
    int16_t all_all;
    int16_t sum_axis0[3];
    int16_t sum_axis1[2];
    int16_t max_axis0[3];
    int16_t max_axis1[2];
    int16_t min_axis0[3];
    int16_t min_axis1[2];
    uint64_t argmax_axis0[3];
    uint64_t argmax_axis1[2];
    uint64_t argmin_axis0[3];
    uint64_t argmin_axis1[2];
    int16_t any_axis0[3];
    int16_t all_axis1[2];
} g_reduction_i16 = {
    2,
    {2, 3},
    {12, 0, 3, -2, 5, -9},
    9,
    0,
    12,
    -9,
    UINT64_C(0),
    UINT64_C(5),
    1,
    0,
    {10, 5, -6},
    {15, -6},
    {12, 5, 3},
    {12, 5},
    {-2, 0, -9},
    {0, -9},
    {UINT64_C(0), UINT64_C(1), UINT64_C(0)},
    {UINT64_C(0), UINT64_C(1)},
    {UINT64_C(1), UINT64_C(0), UINT64_C(1)},
    {UINT64_C(1), UINT64_C(2)},
    {1, 1, 1},
    {0, 1},
};

static const struct {
    size_t ndim;
    size_t shape[2];
    int8_t input[6];
    int8_t sum_all;
    int8_t prod_all;
    int8_t max_all;
    int8_t min_all;
    uint64_t argmax_all;
    uint64_t argmin_all;
    int8_t any_all;
    int8_t all_all;
    int8_t sum_axis0[3];
    int8_t sum_axis1[2];
    int8_t max_axis0[3];
    int8_t max_axis1[2];
    int8_t min_axis0[3];
    int8_t min_axis1[2];
    uint64_t argmax_axis0[3];
    uint64_t argmax_axis1[2];
    uint64_t argmin_axis0[3];
    uint64_t argmin_axis1[2];
    int8_t any_axis0[3];
    int8_t all_axis1[2];
} g_reduction_i8 = {
    2,
    {2, 3},
    {12, 0, 3, -2, 5, -9},
    9,
    0,
    12,
    -9,
    UINT64_C(0),
    UINT64_C(5),
    1,
    0,
    {10, 5, -6},
    {15, -6},
    {12, 5, 3},
    {12, 5},
    {-2, 0, -9},
    {0, -9},
    {UINT64_C(0), UINT64_C(1), UINT64_C(0)},
    {UINT64_C(0), UINT64_C(1)},
    {UINT64_C(1), UINT64_C(0), UINT64_C(1)},
    {UINT64_C(1), UINT64_C(2)},
    {1, 1, 1},
    {0, 1},
};

static const struct {
    size_t ndim;
    size_t shape[2];
    uint32_t input[6];
    uint32_t sum_all;
    uint32_t prod_all;
    uint32_t max_all;
    uint32_t min_all;
    uint64_t argmax_all;
    uint64_t argmin_all;
    uint32_t any_all;
    uint32_t all_all;
    uint32_t sum_axis0[3];
    uint32_t sum_axis1[2];
    uint32_t max_axis0[3];
    uint32_t max_axis1[2];
    uint32_t min_axis0[3];
    uint32_t min_axis1[2];
    uint64_t argmax_axis0[3];
    uint64_t argmax_axis1[2];
    uint64_t argmin_axis0[3];
    uint64_t argmin_axis1[2];
    uint32_t any_axis0[3];
    uint32_t all_axis1[2];
} g_reduction_u32 = {
    2,
    {2, 3},
    {7u, 0u, 14u, 9u, 3u, 5u},
    38u,
    0u,
    14u,
    0u,
    UINT64_C(2),
    UINT64_C(1),
    1u,
    0u,
    {16u, 3u, 19u},
    {21u, 17u},
    {9u, 3u, 14u},
    {14u, 9u},
    {7u, 0u, 5u},
    {0u, 3u},
    {UINT64_C(1), UINT64_C(1), UINT64_C(0)},
    {UINT64_C(2), UINT64_C(0)},
    {UINT64_C(0), UINT64_C(0), UINT64_C(1)},
    {UINT64_C(1), UINT64_C(1)},
    {1u, 1u, 1u},
    {0u, 1u},
};

static const struct {
    size_t ndim;
    size_t shape[2];
    uint16_t input[6];
    uint16_t sum_all;
    uint16_t prod_all;
    uint16_t max_all;
    uint16_t min_all;
    uint64_t argmax_all;
    uint64_t argmin_all;
    uint16_t any_all;
    uint16_t all_all;
    uint16_t sum_axis0[3];
    uint16_t sum_axis1[2];
    uint16_t max_axis0[3];
    uint16_t max_axis1[2];
    uint16_t min_axis0[3];
    uint16_t min_axis1[2];
    uint64_t argmax_axis0[3];
    uint64_t argmax_axis1[2];
    uint64_t argmin_axis0[3];
    uint64_t argmin_axis1[2];
    uint16_t any_axis0[3];
    uint16_t all_axis1[2];
} g_reduction_u16 = {
    2,
    {2, 3},
    {7u, 0u, 14u, 9u, 3u, 5u},
    38u,
    0u,
    14u,
    0u,
    UINT64_C(2),
    UINT64_C(1),
    1u,
    0u,
    {16u, 3u, 19u},
    {21u, 17u},
    {9u, 3u, 14u},
    {14u, 9u},
    {7u, 0u, 5u},
    {0u, 3u},
    {UINT64_C(1), UINT64_C(1), UINT64_C(0)},
    {UINT64_C(2), UINT64_C(0)},
    {UINT64_C(0), UINT64_C(0), UINT64_C(1)},
    {UINT64_C(1), UINT64_C(1)},
    {1u, 1u, 1u},
    {0u, 1u},
};

static const struct {
    size_t ndim;
    size_t shape[2];
    uint8_t input[6];
    uint8_t sum_all;
    uint8_t prod_all;
    uint8_t max_all;
    uint8_t min_all;
    uint64_t argmax_all;
    uint64_t argmin_all;
    uint8_t any_all;
    uint8_t all_all;
    uint8_t sum_axis0[3];
    uint8_t sum_axis1[2];
    uint8_t max_axis0[3];
    uint8_t max_axis1[2];
    uint8_t min_axis0[3];
    uint8_t min_axis1[2];
    uint64_t argmax_axis0[3];
    uint64_t argmax_axis1[2];
    uint64_t argmin_axis0[3];
    uint64_t argmin_axis1[2];
    uint8_t any_axis0[3];
    uint8_t all_axis1[2];
} g_reduction_u8 = {
    2,
    {2, 3},
    {7u, 0u, 14u, 9u, 3u, 5u},
    38u,
    0u,
    14u,
    0u,
    UINT64_C(2),
    UINT64_C(1),
    1u,
    0u,
    {16u, 3u, 19u},
    {21u, 17u},
    {9u, 3u, 14u},
    {14u, 9u},
    {7u, 0u, 5u},
    {0u, 3u},
    {UINT64_C(1), UINT64_C(1), UINT64_C(0)},
    {UINT64_C(2), UINT64_C(0)},
    {UINT64_C(0), UINT64_C(0), UINT64_C(1)},
    {UINT64_C(1), UINT64_C(1)},
    {1u, 1u, 1u},
    {0u, 1u},
};

// Tensor operation golden data

static const struct {
    size_t shape_src[2];
    size_t shape_dst[2];
    float src[6];
    float transpose_default[6];
    float transpose_identity[6];
} g_tensor_2d = {
    {2, 3}, {3, 2}, {0, 1, 2, 3, 4, 5}, {0, 3, 1, 4, 2, 5}, {0, 1, 2, 3, 4, 5},
};

static const struct {
    size_t length;
    float left[3];
    float right[3];
    float concat_axis0[6];
    float slice_result[3];
} g_tensor_concat1d = {
    3, {-1, 0, 1}, {2, 3, 4}, {-1, 0, 1, 2, 3, 4}, {1, 2, 3},
};

static const struct {
    size_t shape_in[3];
    size_t perm[3];
    float input[24];
    float expected[24];
} g_tensor_transpose3d = {
    {2, 3, 4},
    {2, 0, 1},
    {0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2, 2.25, 2.5, 2.75,
     3, 3.25, 3.5, 3.75, 4, 4.25, 4.5, 4.75, 5, 5.25, 5.5, 5.75},
    {0,   1,   2,   3,   4,   5,   0.25, 1.25, 2.25, 3.25, 4.25, 5.25,
     0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 0.75, 1.75, 2.75, 3.75, 4.75, 5.75},
};

static const struct {
    size_t shape_a[3];
    size_t shape_b[3];
    float a[18];
    float b[6];
    float expected[18];
} g_tensor_concat3d = {
    {2, 2, 3},
    {2, 1, 3},
    {0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 1.1},
    {2, 2.05, 2.1, 2.15, 2.2, 2.25},
    {0, 0.1, 0.2, 0.3, 0.4, 0.5, 2, 2.05, 2.1, 0.6, 0.7, 0.8, 0.9, 1, 1.1, 2.15, 2.2, 2.25},
};

static const struct {
    size_t shape_src[3];
    size_t starts[3];
    size_t sizes[3];
    float src[24];
    float expected[4];
} g_tensor_slice3d = {
    {2, 3, 4},
    {1, 0, 1},
    {1, 2, 2},
    {0,
     0.2955202067,
     0.5646424734,
     0.7833269096,
     0.932039086,
     0.9974949866,
     0.9738476309,
     0.8632093666,
     0.6754631806,
     0.4273798802,
     0.1411200081,
     -0.1577456941,
     -0.4425204433,
     -0.6877661592,
     -0.8715757724,
     -0.9775301177,
     -0.9961646088,
     -0.9258146823,
     -0.7727644876,
     -0.5506855426,
     -0.2794154982,
     0.01681390048,
     0.3115413635,
     0.5784397644},
    {-0.6877661592, -0.8715757724, -0.9258146823, -0.7727644876},
};

// Matmul golden data

static const struct {
    size_t m;
    size_t k;
    size_t n;
    float a[6];
    float b[6];
    float expected[4];
} g_matmul_case_0 = {
    2, 3, 2, {-0.5, -0.25, 0, 0.25, 0.5, 0.75}, {-0.45, -0.3, -0.15, 0, 0.15, 0.3}, {0.2625, 0.15, -0.075, 0.15},
};

static const struct {
    size_t m;
    size_t k;
    size_t n;
    float a[12];
    float b[8];
    float expected[6];
} g_matmul_case_1 = {
    3,
    4,
    2,
    {-1, -0.75, -0.5, -0.25, 0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75},
    {-0.6, -0.45, -0.3, -0.15, 0, 0.15, 0.3, 0.45},
    {0.75, 0.375, 0.15, 0.375, -0.45, 0.375},
};

static const struct {
    size_t m;
    size_t k;
    size_t n;
    float a[8];
    float b[12];
    float expected[6];
} g_matmul_case_2 = {
    2,
    4,
    3,
    {-0.6666666667, -0.4166666667, -0.1666666667, 0.08333333333, 0.3333333333, 0.5833333333, 0.8333333333, 1.083333333},
    {-0.9, -0.75, -0.6, -0.45, -0.3, -0.15, 0, 0.15, 0.3, 0.45, 0.6, 0.75},
    {0.825, 0.65, 0.475, -0.075, 0.35, 0.775},
};

static const struct {
    size_t m;
    size_t k;
    size_t n;
    float a[8];
    float b[8];
    float expected[4];
} g_matmul_case_3 = {
    2,
    4,
    2,
    {-0.6666666667, -0.4166666667, -0.1666666667, 0.08333333333, 0.3333333333, 0.5833333333, 0.8333333333, 1.083333333},
    {-0.6, -0.45, -0.3, -0.15, 0, 0.15, 0.3, 0.45},
    {0.55, 0.375, -0.05, 0.375},
};

// FP8 matmul golden data

#if MARMOT_ENABLE_FP8

static const struct {
    size_t n;
    size_t k;
    size_t m;
    uint8_t input[8];
    uint8_t weight[12];
    float expected[6];
} g_matmul_fp8_e4m3_case0 = {
    2,
    4,
    3,
    {173u, 170u, 165u, 157u, 0u, 29u, 37u, 42u},
    {175u, 173u, 170u, 167u, 162u, 154u, 0u, 26u, 34u, 39u, 42u, 45u},
    {0.4046630859, 0.07995605469, -0.2414550781, -0.1779785156, 0.01647949219, 0.2142333984},
};

static const struct {
    size_t n;
    size_t k;
    size_t m;
    uint8_t input[24];
    uint8_t weight[32];
    float expected[12];
} g_matmul_fp8_e4m3_case1 = {
    3,
    8,
    4,
    {186u, 185u, 184u, 182u, 181u, 179u, 178u, 176u, 173u, 170u, 165u, 157u,
     0u,   29u,  37u,  42u,  45u,  48u,  50u,  51u,  53u,  54u,  56u,  57u},
    {186u, 186u, 185u, 184u, 183u, 182u, 181u, 180u, 178u, 177u, 175u, 173u, 170u, 167u, 162u, 154u,
     0u,   26u,  34u,  39u,  42u,  45u,  47u,  49u,  50u,  52u,  53u,  54u,  55u,  56u,  57u,  58u},
    {7.21484375, 2.790039062, -1.556640625, -5.98046875, 0.740234375, 0.4862060547, 0.2322998047, -0.021484375,
     -5.70703125, -1.810546875, 2.008789062, 5.90625},
};

static const struct {
    size_t n;
    size_t k;
    size_t m;
    uint8_t input[64];
    uint8_t weight[80];
    float expected[20];
} g_matmul_fp8_e4m3_case2 = {
    4,
    16,
    5,
    {197u, 196u, 196u, 196u, 195u, 195u, 194u, 194u, 194u, 193u, 193u, 192u, 192u, 191u, 190u, 190u,
     189u, 188u, 187u, 186u, 186u, 185u, 184u, 182u, 181u, 179u, 178u, 176u, 173u, 170u, 165u, 157u,
     0u,   29u,  37u,  42u,  45u,  48u,  50u,  51u,  53u,  54u,  56u,  57u,  58u,  58u,  59u,  60u,
     61u,  62u,  62u,  63u,  64u,  64u,  65u,  65u,  66u,  66u,  66u,  67u,  67u,  68u,  68u,  68u},
    {197u, 196u, 196u, 196u, 196u, 195u, 195u, 195u, 194u, 194u, 194u, 193u, 193u, 193u, 192u, 192u,
     191u, 191u, 190u, 189u, 189u, 188u, 188u, 187u, 186u, 186u, 185u, 184u, 183u, 182u, 181u, 180u,
     178u, 177u, 175u, 173u, 170u, 167u, 162u, 154u, 0u,   26u,  34u,  39u,  42u,  45u,  47u,  49u,
     50u,  52u,  53u,  54u,  55u,  56u,  57u,  58u,  58u,  59u,  60u,  60u,  61u,  61u,  62u,  63u,
     63u,  64u,  64u,  65u,  65u,  65u,  66u,  66u,  66u,  67u,  67u,  67u,  68u,  68u,  68u,  68u},
    {104.84375,   54.34375,     4.24609375,  -45.84375,   -95.96875,    38.3203125,  20.69238281,
     3.215820312, -14.22949219, -31.7265625, -28.6796875, -13.21386719, 2.200195312, 17.64550781,
     33.0390625,  -95.15625,    -46.859375,  1.19921875,  49.265625,    97.328125},
};

static const struct {
    size_t n;
    size_t k;
    size_t m;
    uint8_t input[8];
    uint8_t weight[12];
    float expected[6];
} g_matmul_fp8_e5m2_case0 = {
    2,
    4,
    3,
    {182u, 181u, 178u, 174u, 0u, 46u, 50u, 53u},
    {184u, 182u, 181u, 180u, 177u, 173u, 0u, 45u, 49u, 52u, 53u, 54u},
    {0.38671875, 0.07568359375, -0.23046875, -0.171875, 0.01708984375, 0.19921875},
};

static const struct {
    size_t n;
    size_t k;
    size_t m;
    uint8_t input[24];
    uint8_t weight[32];
    float expected[12];
} g_matmul_fp8_e5m2_case1 = {
    3,
    8,
    4,
    {189u, 188u, 188u, 187u, 186u, 186u, 185u, 184u, 182u, 181u, 178u, 174u,
     0u,   46u,  50u,  53u,  54u,  56u,  57u,  58u,  58u,  59u,  60u,  60u},
    {189u, 189u, 188u, 188u, 188u, 187u, 186u, 186u, 185u, 184u, 184u, 182u, 181u, 180u, 177u, 173u,
     0u,   45u,  49u,  52u,  53u,  54u,  56u,  56u,  57u,  58u,  58u,  59u,  60u,  60u,  60u,  61u},
    {6.9375, 2.66796875, -1.53125, -5.796875, 0.68359375, 0.4423828125, 0.2080078125, -0.01953125, -5.484375, -1.765625,
     1.88671875, 5.609375},
};

static const struct {
    size_t n;
    size_t k;
    size_t m;
    uint8_t input[64];
    uint8_t weight[80];
    float expected[20];
} g_matmul_fp8_e5m2_case2 = {
    4,
    16,
    5,
    {194u, 194u, 194u, 194u, 194u, 193u, 193u, 193u, 193u, 193u, 192u, 192u, 192u, 192u, 191u, 191u,
     190u, 190u, 190u, 189u, 189u, 188u, 188u, 187u, 186u, 186u, 185u, 184u, 182u, 181u, 178u, 174u,
     0u,   46u,  50u,  53u,  54u,  56u,  57u,  58u,  58u,  59u,  60u,  60u,  61u,  61u,  62u,  62u,
     62u,  63u,  63u,  64u,  64u,  64u,  64u,  65u,  65u,  65u,  65u,  65u,  66u,  66u,  66u,  66u},
    {194u, 194u, 194u, 194u, 194u, 194u, 193u, 193u, 193u, 193u, 193u, 193u, 192u, 192u, 192u, 192u,
     192u, 191u, 191u, 191u, 190u, 190u, 190u, 189u, 189u, 189u, 188u, 188u, 188u, 187u, 186u, 186u,
     185u, 184u, 184u, 182u, 181u, 180u, 177u, 173u, 0u,   45u,  49u,  52u,  53u,  54u,  56u,  56u,
     57u,  58u,  58u,  59u,  60u,  60u,  60u,  61u,  61u,  61u,  62u,  62u,  62u,  63u,  63u,  63u,
     64u,  64u,  64u,  64u,  64u,  65u,  65u,  65u,  65u,  65u,  65u,  66u,  66u,  66u,  66u,  66u},
    {102.5,     53.5,        4.015625,    -45,       -94.75,  37.1875, 20.265625, 3.115234375, -13.7890625, -30.90625,
     -27.90625, -12.8515625, 2.177734375, 17.265625, 32.6875, -93.25,  -46.125,   1.203125,    48.4375,     96.5},
};

typedef struct {
    size_t n;
    size_t k;
    size_t m;
    const uint8_t *input;
    const uint8_t *weight;
    const float *expected;
} matmul_fp8_e4m3_case_t;

static const matmul_fp8_e4m3_case_t g_matmul_fp8_e4m3_cases[] = {
    {
        g_matmul_fp8_e4m3_case0.n,
        g_matmul_fp8_e4m3_case0.k,
        g_matmul_fp8_e4m3_case0.m,
        g_matmul_fp8_e4m3_case0.input,
        g_matmul_fp8_e4m3_case0.weight,
        g_matmul_fp8_e4m3_case0.expected,
    },
    {
        g_matmul_fp8_e4m3_case1.n,
        g_matmul_fp8_e4m3_case1.k,
        g_matmul_fp8_e4m3_case1.m,
        g_matmul_fp8_e4m3_case1.input,
        g_matmul_fp8_e4m3_case1.weight,
        g_matmul_fp8_e4m3_case1.expected,
    },
    {
        g_matmul_fp8_e4m3_case2.n,
        g_matmul_fp8_e4m3_case2.k,
        g_matmul_fp8_e4m3_case2.m,
        g_matmul_fp8_e4m3_case2.input,
        g_matmul_fp8_e4m3_case2.weight,
        g_matmul_fp8_e4m3_case2.expected,
    },
};

static const size_t g_matmul_fp8_e4m3_case_count = sizeof(g_matmul_fp8_e4m3_cases) / sizeof(g_matmul_fp8_e4m3_cases[0]);

typedef struct {
    size_t n;
    size_t k;
    size_t m;
    const uint8_t *input;
    const uint8_t *weight;
    const float *expected;
} matmul_fp8_e5m2_case_t;

static const matmul_fp8_e5m2_case_t g_matmul_fp8_e5m2_cases[] = {
    {
        g_matmul_fp8_e5m2_case0.n,
        g_matmul_fp8_e5m2_case0.k,
        g_matmul_fp8_e5m2_case0.m,
        g_matmul_fp8_e5m2_case0.input,
        g_matmul_fp8_e5m2_case0.weight,
        g_matmul_fp8_e5m2_case0.expected,
    },
    {
        g_matmul_fp8_e5m2_case1.n,
        g_matmul_fp8_e5m2_case1.k,
        g_matmul_fp8_e5m2_case1.m,
        g_matmul_fp8_e5m2_case1.input,
        g_matmul_fp8_e5m2_case1.weight,
        g_matmul_fp8_e5m2_case1.expected,
    },
    {
        g_matmul_fp8_e5m2_case2.n,
        g_matmul_fp8_e5m2_case2.k,
        g_matmul_fp8_e5m2_case2.m,
        g_matmul_fp8_e5m2_case2.input,
        g_matmul_fp8_e5m2_case2.weight,
        g_matmul_fp8_e5m2_case2.expected,
    },
};

static const size_t g_matmul_fp8_e5m2_case_count = sizeof(g_matmul_fp8_e5m2_cases) / sizeof(g_matmul_fp8_e5m2_cases[0]);

#endif // MARMOT_ENABLE_FP8

// Fused matmul epilogue golden data

static const float g_matmul_fused_bias_residual_input[6] = {0.5, -1, 2, -0.5, 1.5, 3};
static const double g_matmul_fused_bias_residual_input_f64[6] = {0.5, -1, 2, -0.5, 1.5, 3};
static const float g_matmul_fused_bias_residual_weight[12] = {1.25, -0.75, 0.5,  0,   1.5,  -0.25,
                                                              -1,   0.75,  0.25, 0.5, -0.5, 0.25};
static const double g_matmul_fused_bias_residual_weight_f64[12] = {1.25, -0.75, 0.5,  0,   1.5,  -0.25,
                                                                   -1,   0.75,  0.25, 0.5, -0.5, 0.25};
static const float g_matmul_fused_bias_residual_bias[4] = {0.15, -0.05, 0.35, -0.2};
static const double g_matmul_fused_bias_residual_bias_f64[4] = {
    0.14999999999999999, -0.050000000000000003, 0.34999999999999998, -0.20000000000000001
};
static const float g_matmul_fused_bias_residual_residual[8] = {-0.2, 0.1, 0.05, -0.15, 0.3, -0.25, 0.2, -0.1};
static const double g_matmul_fused_bias_residual_residual_f64[8] = {-0.20000000000000001, 0.10000000000000001,
                                                                    0.050000000000000003, -0.14999999999999999,
                                                                    0.29999999999999999,  -0.25,
                                                                    0.20000000000000001,  -0.10000000000000001};
static const float g_matmul_fused_bias_residual_expected[8] = {2.325, -1.95, -0.35, 0.9, 0.2, 1.2, 2.925, -0.55};
static const double g_matmul_fused_bias_residual_expected_f64[8] = {2.3249999999999997,   -1.9499999999999997,
                                                                    -0.35000000000000003, 0.90000000000000002,
                                                                    0.19999999999999998,  1.2,
                                                                    2.9250000000000003,   -0.55000000000000004};

static const float g_matmul_fused_residual_only_input[4] = {1, -2, 0.5, 3};
static const double g_matmul_fused_residual_only_input_f64[4] = {1, -2, 0.5, 3};
static const float g_matmul_fused_residual_only_weight[12] = {-0.5, 0.25, 1,     -0.75, 0.5, -1.25,
                                                              0.75, 0,    -0.25, 0.5,   0.2, -0.4};
static const double g_matmul_fused_residual_only_weight_f64[12] = {
    -0.5, 0.25, 1, -0.75, 0.5, -1.25, 0.75, 0, -0.25, 0.5, 0.20000000000000001, -0.40000000000000002
};
static const float *g_matmul_fused_residual_only_bias = nullptr;
static const double *g_matmul_fused_residual_only_bias_f64 = nullptr;
static const float g_matmul_fused_residual_only_residual[3] = {0.05, -0.02, 0.1};
static const double g_matmul_fused_residual_only_residual_f64[3] = {0.050000000000000003, -0.02, 0.10000000000000001};
static const float g_matmul_fused_residual_only_expected[3] = {-2.7, 3.355, -2.25};
static const double g_matmul_fused_residual_only_expected_f64[3] = {-2.7000000000000002, 3.355, -2.25};

static const float g_matmul_fused_bias_relu_input[6] = {0.5, -1, 2, -0.5, 1.5, 3};
static const double g_matmul_fused_bias_relu_input_f64[6] = {0.5, -1, 2, -0.5, 1.5, 3};
static const float g_matmul_fused_bias_relu_weight[12] = {1,     -0.5, 0.25,  0.75, -1,   0.5,
                                                          -0.25, 1.25, -0.75, 0.5,  -1.5, 0.75};
static const double g_matmul_fused_bias_relu_weight_f64[12] = {1,     -0.5, 0.25,  0.75, -1,   0.5,
                                                               -0.25, 1.25, -0.75, 0.5,  -1.5, 0.75};
static const float g_matmul_fused_bias_relu_bias[4] = {0.1, -0.15, 0.2, -0.05};
static const double g_matmul_fused_bias_relu_bias_f64[4] = {
    0.10000000000000001, -0.14999999999999999, 0.20000000000000001, -0.050000000000000003
};
static const float *g_matmul_fused_bias_relu_residual = nullptr;
static const double *g_matmul_fused_bias_relu_residual_f64 = nullptr;
static const float g_matmul_fused_bias_relu_expected[8] = {1.6, 2.225, 0, 3.2, 0, 0, 0, 0};
static const double g_matmul_fused_bias_relu_expected_f64[8] = {
    1.6000000000000001, 2.2250000000000001, 0, 3.2000000000000002, 0, 0, 0, 0
};

static const float g_matmul_fused_bias_gelu_input[6] = {1, -0.5, 0.75, -1.25, 0.5, 2};
static const double g_matmul_fused_bias_gelu_input_f64[6] = {1, -0.5, 0.75, -1.25, 0.5, 2};
static const float g_matmul_fused_bias_gelu_weight[9] = {0.5, -1, 0.25, 1.5, -0.75, 0.5, -0.5, 1, -1.25};
static const double g_matmul_fused_bias_gelu_weight_f64[9] = {0.5, -1, 0.25, 1.5, -0.75, 0.5, -0.5, 1, -1.25};
static const float g_matmul_fused_bias_gelu_bias[3] = {0.05, -0.1, 0.15};
static const double g_matmul_fused_bias_gelu_bias_f64[3] = {
    0.050000000000000003, -0.10000000000000001, 0.14999999999999999
};
static const float *g_matmul_fused_bias_gelu_residual = nullptr;
static const double *g_matmul_fused_bias_gelu_residual_f64 = nullptr;
static const float g_matmul_fused_bias_gelu_expected[6] = {1.103910938,   2.116078144,   -0.06600943646,
                                                           -0.1625212479, -0.1194857884, -0.1351023226};
static const double g_matmul_fused_bias_gelu_expected_f64[6] = {1.1039109380054357,    2.1160781441091556,
                                                                -0.066009436455495382, -0.1625212478858904,
                                                                -0.1194857884404928,   -0.13510232255974275};

static const float g_matmul_fused_bias_gelu_tanh_input[4] = {0.75, -1, 1.5, -0.25};
static const double g_matmul_fused_bias_gelu_tanh_input_f64[4] = {0.75, -1, 1.5, -0.25};
static const float g_matmul_fused_bias_gelu_tanh_weight[12] = {1,    -0.5, 0.75,  -1.25, 0.5,   -1,
                                                               0.25, 1.5,  -0.75, 0.5,   -0.25, 1};
static const double g_matmul_fused_bias_gelu_tanh_weight_f64[12] = {1,    -0.5, 0.75,  -1.25, 0.5,   -1,
                                                                    0.25, 1.5,  -0.75, 0.5,   -0.25, 1};
static const float g_matmul_fused_bias_gelu_tanh_bias[3] = {0.2, -0.1, 0.05};
static const double g_matmul_fused_bias_gelu_tanh_bias_f64[3] = {
    0.20000000000000001, -0.10000000000000001, 0.050000000000000003
};
static const float *g_matmul_fused_bias_gelu_tanh_residual = nullptr;
static const double *g_matmul_fused_bias_gelu_tanh_residual_f64 = nullptr;
static const float g_matmul_fused_bias_gelu_tanh_expected[3] = {2.882341175, 1.145800462, -0.08329136795};
static const double g_matmul_fused_bias_gelu_tanh_expected_f64[3] = {
    2.8823411748744259, 1.1458004621376925, -0.083291367949357778
};

static const float g_matmul_fused_bias_silu_input[4] = {1.5, -0.75, 0.25, 2};
static const double g_matmul_fused_bias_silu_input_f64[4] = {1.5, -0.75, 0.25, 2};
static const float g_matmul_fused_bias_silu_weight[6] = {0.5, -1, 1.25, -0.5, 0.75, -1.5};
static const double g_matmul_fused_bias_silu_weight_f64[6] = {0.5, -1, 1.25, -0.5, 0.75, -1.5};
static const float g_matmul_fused_bias_silu_bias[3] = {0.1, -0.2, 0.15};
static const double g_matmul_fused_bias_silu_bias_f64[3] = {
    0.10000000000000001, -0.20000000000000001, 0.14999999999999999
};
static const float *g_matmul_fused_bias_silu_residual = nullptr;
static const double *g_matmul_fused_bias_silu_residual_f64 = nullptr;
static const float g_matmul_fused_bias_silu_expected[6] = {1.331229416,   1.816192618,  2.200385528,
                                                           -0.2572358959, -0.258818083, -0.1736555607};
static const double g_matmul_fused_bias_silu_expected_f64[6] = {1.3312294162142793,   1.8161926183764285,
                                                                2.2003855284145861,   -0.25723589589088558,
                                                                -0.25881808295880976, -0.17365556070020594};

static const float g_matmul_fused_bias_relu_residual_input[6] = {0.5, -1, 1.5, -0.5, 2, 0.75};
static const double g_matmul_fused_bias_relu_residual_input_f64[6] = {0.5, -1, 1.5, -0.5, 2, 0.75};
static const float g_matmul_fused_bias_relu_residual_weight[9] = {1, -0.75, 0.5, 0.5, -1.25, 0.75, -0.5, 1, -0.25};
static const double g_matmul_fused_bias_relu_residual_weight_f64[9] = {1, -0.75, 0.5, 0.5, -1.25, 0.75, -0.5, 1, -0.25};
static const float g_matmul_fused_bias_relu_residual_bias[3] = {0.15, -0.1, 0.25};
static const double g_matmul_fused_bias_relu_residual_bias_f64[3] = {0.14999999999999999, -0.10000000000000001, 0.25};
static const float g_matmul_fused_bias_relu_residual_residual[6] = {-0.1, 0.05, -0.15, 0.2, -0.25, 0.1};
static const double g_matmul_fused_bias_relu_residual_residual_f64[6] = {
    -0.10000000000000001, 0.050000000000000003, -0.14999999999999999, 0.20000000000000001, -0.25, 0.10000000000000001
};
static const float g_matmul_fused_bias_relu_residual_expected[6] = {2.05, 2.575, -0.15, 0.2, -0.25, 2.4125};
static const double g_matmul_fused_bias_relu_residual_expected_f64[6] = {
    2.0499999999999998, 2.5749999999999997, -0.14999999999999999, 0.20000000000000001, -0.25, 2.4125000000000001
};

static const float g_matmul_fused_bias_gelu_residual_input[4] = {1, -0.5, 1.5, -1};
static const double g_matmul_fused_bias_gelu_residual_input_f64[4] = {1, -0.5, 1.5, -1};
static const float g_matmul_fused_bias_gelu_residual_weight[16] = {0.75, -1, 0.5,  -0.25, 1.25,  -0.5, 0.75, -1.5,
                                                                   0.5,  -1, 0.25, 1,     -0.75, 1.25, -0.5, 0.5};
static const double g_matmul_fused_bias_gelu_residual_weight_f64[16] = {0.75, -1, 0.5,  -0.25, 1.25,  -0.5, 0.75, -1.5,
                                                                        0.5,  -1, 0.25, 1,     -0.75, 1.25, -0.5, 0.5};
static const float g_matmul_fused_bias_gelu_residual_bias[4] = {0.1, -0.15, 0.2, -0.05};
static const double g_matmul_fused_bias_gelu_residual_bias_f64[4] = {
    0.10000000000000001, -0.14999999999999999, 0.20000000000000001, -0.050000000000000003
};
static const float g_matmul_fused_bias_gelu_residual_residual[4] = {0.05, -0.1, 0.15, -0.2};
static const double g_matmul_fused_bias_gelu_residual_residual_f64[4] = {
    0.050000000000000003, -0.10000000000000001, 0.14999999999999999, -0.20000000000000001
};
static const float g_matmul_fused_bias_gelu_residual_expected[4] = {
    2.377941242, 3.874860121, 0.5624787521, -0.2099950372
};
static const double g_matmul_fused_bias_gelu_residual_expected_f64[4] = {
    2.3779412419931294, 3.8748601212284379, 0.56247875211410958, -0.20999503721242513
};

static const struct {
    const char *name;
    size_t n;
    size_t k;
    size_t m;
    int has_bias;
    int has_residual;
    marmot_device_unary_op_t activation;
    const float *input;
    const float *weight;
    const float *bias;
    const float *residual;
    const float *expected;
    const double *input_f64;
    const double *weight_f64;
    const double *bias_f64;
    const double *residual_f64;
    const double *expected_f64;
} g_matmul_fused_cases[] = {
    {
        "bias_residual",
        2,
        3,
        4,
        1,
        1,
        MARMOT_DEVICE_UNARY_IDENTITY,
        g_matmul_fused_bias_residual_input,
        g_matmul_fused_bias_residual_weight,
        g_matmul_fused_bias_residual_bias,
        g_matmul_fused_bias_residual_residual,
        g_matmul_fused_bias_residual_expected,
        g_matmul_fused_bias_residual_input_f64,
        g_matmul_fused_bias_residual_weight_f64,
        g_matmul_fused_bias_residual_bias_f64,
        g_matmul_fused_bias_residual_residual_f64,
        g_matmul_fused_bias_residual_expected_f64,
    },
    {
        "residual_only",
        1,
        4,
        3,
        0,
        1,
        MARMOT_DEVICE_UNARY_IDENTITY,
        g_matmul_fused_residual_only_input,
        g_matmul_fused_residual_only_weight,
        nullptr,
        g_matmul_fused_residual_only_residual,
        g_matmul_fused_residual_only_expected,
        g_matmul_fused_residual_only_input_f64,
        g_matmul_fused_residual_only_weight_f64,
        nullptr,
        g_matmul_fused_residual_only_residual_f64,
        g_matmul_fused_residual_only_expected_f64,
    },
    {
        "bias_relu",
        2,
        3,
        4,
        1,
        0,
        MARMOT_DEVICE_UNARY_RELU,
        g_matmul_fused_bias_relu_input,
        g_matmul_fused_bias_relu_weight,
        g_matmul_fused_bias_relu_bias,
        nullptr,
        g_matmul_fused_bias_relu_expected,
        g_matmul_fused_bias_relu_input_f64,
        g_matmul_fused_bias_relu_weight_f64,
        g_matmul_fused_bias_relu_bias_f64,
        nullptr,
        g_matmul_fused_bias_relu_expected_f64,
    },
    {
        "bias_gelu",
        2,
        3,
        3,
        1,
        0,
        MARMOT_DEVICE_UNARY_GELU,
        g_matmul_fused_bias_gelu_input,
        g_matmul_fused_bias_gelu_weight,
        g_matmul_fused_bias_gelu_bias,
        nullptr,
        g_matmul_fused_bias_gelu_expected,
        g_matmul_fused_bias_gelu_input_f64,
        g_matmul_fused_bias_gelu_weight_f64,
        g_matmul_fused_bias_gelu_bias_f64,
        nullptr,
        g_matmul_fused_bias_gelu_expected_f64,
    },
    {
        "bias_gelu_tanh",
        1,
        4,
        3,
        1,
        0,
        MARMOT_DEVICE_UNARY_GELU_TANH,
        g_matmul_fused_bias_gelu_tanh_input,
        g_matmul_fused_bias_gelu_tanh_weight,
        g_matmul_fused_bias_gelu_tanh_bias,
        nullptr,
        g_matmul_fused_bias_gelu_tanh_expected,
        g_matmul_fused_bias_gelu_tanh_input_f64,
        g_matmul_fused_bias_gelu_tanh_weight_f64,
        g_matmul_fused_bias_gelu_tanh_bias_f64,
        nullptr,
        g_matmul_fused_bias_gelu_tanh_expected_f64,
    },
    {
        "bias_silu",
        2,
        2,
        3,
        1,
        0,
        MARMOT_DEVICE_UNARY_SILU,
        g_matmul_fused_bias_silu_input,
        g_matmul_fused_bias_silu_weight,
        g_matmul_fused_bias_silu_bias,
        nullptr,
        g_matmul_fused_bias_silu_expected,
        g_matmul_fused_bias_silu_input_f64,
        g_matmul_fused_bias_silu_weight_f64,
        g_matmul_fused_bias_silu_bias_f64,
        nullptr,
        g_matmul_fused_bias_silu_expected_f64,
    },
    {
        "bias_relu_residual",
        2,
        3,
        3,
        1,
        1,
        MARMOT_DEVICE_UNARY_RELU,
        g_matmul_fused_bias_relu_residual_input,
        g_matmul_fused_bias_relu_residual_weight,
        g_matmul_fused_bias_relu_residual_bias,
        g_matmul_fused_bias_relu_residual_residual,
        g_matmul_fused_bias_relu_residual_expected,
        g_matmul_fused_bias_relu_residual_input_f64,
        g_matmul_fused_bias_relu_residual_weight_f64,
        g_matmul_fused_bias_relu_residual_bias_f64,
        g_matmul_fused_bias_relu_residual_residual_f64,
        g_matmul_fused_bias_relu_residual_expected_f64,
    },
    {
        "bias_gelu_residual",
        1,
        4,
        4,
        1,
        1,
        MARMOT_DEVICE_UNARY_GELU,
        g_matmul_fused_bias_gelu_residual_input,
        g_matmul_fused_bias_gelu_residual_weight,
        g_matmul_fused_bias_gelu_residual_bias,
        g_matmul_fused_bias_gelu_residual_residual,
        g_matmul_fused_bias_gelu_residual_expected,
        g_matmul_fused_bias_gelu_residual_input_f64,
        g_matmul_fused_bias_gelu_residual_weight_f64,
        g_matmul_fused_bias_gelu_residual_bias_f64,
        g_matmul_fused_bias_gelu_residual_residual_f64,
        g_matmul_fused_bias_gelu_residual_expected_f64,
    },
};
static const size_t g_matmul_fused_case_count = sizeof(g_matmul_fused_cases) / sizeof(g_matmul_fused_cases[0]);

// Fused QKV matmul golden data

static const float g_matmul_qkv_bias_input[6] = {0.25, -0.5, 1, -1.5, 2, 1.25};
static const double g_matmul_qkv_bias_input_f64[6] = {0.25, -0.5, 1, -1.5, 2, 1.25};
static const float g_matmul_qkv_bias_weight[18] = {0.5, -0.25, 0.75, -0.5,  0.1, 0.2, 0.1,  0.4,   -0.3,
                                                   0.6, -0.2,  0.5,  -0.25, 0.5, 0.1, 0.35, -0.15, 0.2};
static const double g_matmul_qkv_bias_weight_f64[18] = {
    0.5,
    -0.25,
    0.75,
    -0.5,
    0.10000000000000001,
    0.20000000000000001,
    0.10000000000000001,
    0.40000000000000002,
    -0.29999999999999999,
    0.59999999999999998,
    -0.20000000000000001,
    0.5,
    -0.25,
    0.5,
    0.10000000000000001,
    0.34999999999999998,
    -0.14999999999999999,
    0.20000000000000001
};
static const float g_matmul_qkv_bias_bias[6] = {0.05, -0.02, -0.01, 0.03, 0.02, -0.04};
static const double g_matmul_qkv_bias_bias_f64[6] = {0.050000000000000003, -0.02, -0.01,
                                                     0.029999999999999999, 0.02,  -0.040000000000000001};
static const float g_matmul_qkv_bias_expected_q[4] = {1.05, 0.005, -0.2625, 1.18};
static const float g_matmul_qkv_bias_expected_k[4] = {-0.485, 0.78, 0.265, -0.645};
static const float g_matmul_qkv_bias_expected_v[4] = {-0.1925, 0.3225, 1.52, -0.615};
static const double g_matmul_qkv_bias_expected_q_f64[4] = {
    1.05, 0.0050000000000000218, -0.26250000000000001, 1.1799999999999999
};
static const double g_matmul_qkv_bias_expected_k_f64[4] = {
    -0.48499999999999999, 0.78000000000000003, 0.26500000000000001, -0.6449999999999998
};
static const double g_matmul_qkv_bias_expected_v_f64[4] = {-0.1925, 0.32250000000000001, 1.52, -0.61499999999999999};

static const float g_matmul_qkv_no_bias_input[4] = {1.5, -2, 0.75, 3.25};
static const double g_matmul_qkv_no_bias_input_f64[4] = {1.5, -2, 0.75, 3.25};
static const float g_matmul_qkv_no_bias_weight[36] = {0.2,  -0.5,  0.1,   0.3,  -0.4,  0.25,  0.35, -0.15, 0.6,
                                                      -0.2, 0.5,   0.1,   0.1,  0.05,  -0.3,  0.4,  0.2,   -0.1,
                                                      0.25, -0.35, -0.45, 0.15, -0.05, 0.2,   0.3,  -0.25, 0.4,
                                                      -0.1, 0.15,  0.05,  -0.2, 0.35,  -0.05, 0.25, 0.1,   -0.3};
static const double g_matmul_qkv_no_bias_weight_f64[36] = {
    0.20000000000000001,
    -0.5,
    0.10000000000000001,
    0.29999999999999999,
    -0.40000000000000002,
    0.25,
    0.34999999999999998,
    -0.14999999999999999,
    0.59999999999999998,
    -0.20000000000000001,
    0.5,
    0.10000000000000001,
    0.10000000000000001,
    0.050000000000000003,
    -0.29999999999999999,
    0.40000000000000002,
    0.20000000000000001,
    -0.10000000000000001,
    0.25,
    -0.34999999999999998,
    -0.45000000000000001,
    0.14999999999999999,
    -0.050000000000000003,
    0.20000000000000001,
    0.29999999999999999,
    -0.25,
    0.40000000000000002,
    -0.10000000000000001,
    0.14999999999999999,
    0.050000000000000003,
    -0.20000000000000001,
    0.34999999999999998,
    -0.050000000000000003,
    0.25,
    0.10000000000000001,
    -0.29999999999999999
};
static const float *g_matmul_qkv_no_bias_bias = nullptr;
static const double *g_matmul_qkv_no_bias_bias_f64 = nullptr;
static const float g_matmul_qkv_no_bias_expected_q[3] = {2.35, -1.325, 2};
static const float g_matmul_qkv_no_bias_expected_k[3] = {1.125, -0.45, -0.3625};
static const float g_matmul_qkv_no_bias_expected_v[3] = {0.925, 1.1125, -1.475};
static const double g_matmul_qkv_no_bias_expected_q_f64[3] = {2.3500000000000001, -1.3250000000000002, 2};
static const double g_matmul_qkv_no_bias_expected_k_f64[3] = {1.125, -0.44999999999999996, -0.36249999999999999};
static const double g_matmul_qkv_no_bias_expected_v_f64[3] = {
    0.92500000000000004, 1.1124999999999998, -1.4750000000000001
};

static const struct {
    const char *name;
    size_t n;
    size_t k;
    size_t m;
    int has_bias;
    const float *input;
    const float *weight;
    const float *bias;
    const float *expected_q;
    const float *expected_k;
    const float *expected_v;
    const double *input_f64;
    const double *weight_f64;
    const double *bias_f64;
    const double *expected_q_f64;
    const double *expected_k_f64;
    const double *expected_v_f64;
} g_matmul_qkv_cases[] = {
    {
        "bias",
        2,
        3,
        2,
        1,
        g_matmul_qkv_bias_input,
        g_matmul_qkv_bias_weight,
        g_matmul_qkv_bias_bias,
        g_matmul_qkv_bias_expected_q,
        g_matmul_qkv_bias_expected_k,
        g_matmul_qkv_bias_expected_v,
        g_matmul_qkv_bias_input_f64,
        g_matmul_qkv_bias_weight_f64,
        g_matmul_qkv_bias_bias_f64,
        g_matmul_qkv_bias_expected_q_f64,
        g_matmul_qkv_bias_expected_k_f64,
        g_matmul_qkv_bias_expected_v_f64,
    },
    {
        "no_bias",
        1,
        4,
        3,
        0,
        g_matmul_qkv_no_bias_input,
        g_matmul_qkv_no_bias_weight,
        nullptr,
        g_matmul_qkv_no_bias_expected_q,
        g_matmul_qkv_no_bias_expected_k,
        g_matmul_qkv_no_bias_expected_v,
        g_matmul_qkv_no_bias_input_f64,
        g_matmul_qkv_no_bias_weight_f64,
        nullptr,
        g_matmul_qkv_no_bias_expected_q_f64,
        g_matmul_qkv_no_bias_expected_k_f64,
        g_matmul_qkv_no_bias_expected_v_f64,
    },
};
static const size_t g_matmul_qkv_case_count = sizeof(g_matmul_qkv_cases) / sizeof(g_matmul_qkv_cases[0]);

// Quantization golden data

static const struct {
    size_t length;
    float values[4];
    float scale_int8;
    float zero_int8;
    float scale_uint8;
    float zero_uint8;
} g_quant_params = {
    4, {-10, -5, 5, 10}, 0.07843137255, -0.5, 0.07843137255, 127.5,
};

static const struct {
    size_t length;
    float input[8];
    float scale;
    float zero_point;
    int8_t quantized[8];
    float dequantized[8];
} g_quant_int8 = {
    8,
    {-7.5, -3, -1, 0, 1, 3.5, 6, 8},
    0.06078431373,
    -4.612903226,
    {-128, -54, -21, -5, 12, 53, 94, 127},
    {-7.5, -3.001960784, -0.9960784314, -0.02352941176, 1.009803922, 3.501960784, 5.994117647, 8},
};

static const struct {
    size_t length;
    float input[8];
    float scale;
    float zero_point;
    uint8_t quantized[8];
    float dequantized[8];
} g_quant_uint8 = {
    8, {0, 0.5, 1, 2.25, 3.5, 6, 8, 10},           0.03921568627,
    0, {0u, 13u, 26u, 57u, 89u, 153u, 204u, 255u}, {0, 0.5098039216, 1.019607843, 2.235294118, 3.490196078, 6, 8, 10},
};

// Conversion golden data

static const struct {
    size_t length;
    float src[8];
    uint16_t f16_bits[8];
    float roundtrip[8];
} g_conv_f16 = {
    8,
    {-2.25, -1.5, -0.75, 0, 0.75, 1.5, 2.25, 3},
    {49280u, 48640u, 47616u, 0u, 14848u, 15872u, 16512u, 16896u},
    {-2.25, -1.5, -0.75, 0, 0.75, 1.5, 2.25, 3},
};

static const struct {
    size_t length;
    float src[8];
    uint16_t bf16_bits[8];
    float roundtrip[8];
} g_conv_bf16 = {
    8,
    {0, 0.8414709848, 0.9092974268, 0.1411200081, -0.7568024953, -0.9589242747, -0.2794154982, 0.6569865987},
    {0u, 16215u, 16233u, 15889u, 48962u, 49013u, 48783u, 16168u},
    {0, 0.83984375, 0.91015625, 0.1416015625, -0.7578125, -0.95703125, -0.279296875, 0.65625},
};

static const struct {
    size_t length;
    float src[6];
    uint16_t f16_bits[6];
    uint16_t bf16_bits[6];
    uint16_t bf16_from_f16_bits[6];
    float bf16_from_f16_roundtrip[6];
    uint16_t f16_from_bf16_bits[6];
    float f16_from_bf16_roundtrip[6];
} g_conv_f16_bf16_bridge = {
    6,
    {-1, -0.5, 0, 0.5, 1, 1.5},
    {48128u, 47104u, 0u, 14336u, 15360u, 15872u},
    {49024u, 48896u, 0u, 16128u, 16256u, 16320u},
    {49024u, 48896u, 0u, 16128u, 16256u, 16320u},
    {-1, -0.5, 0, 0.5, 1, 1.5},
    {48128u, 47104u, 0u, 14336u, 15360u, 15872u},
    {-1, -0.5, 0, 0.5, 1, 1.5},
};

#if MARMOT_ENABLE_FP8

static const struct {
    size_t length;
    float src[16];
    uint8_t e4m3_bits[16];
    float e4m3_roundtrip[16];
    uint8_t e5m2_bits[16];
    float e5m2_roundtrip[16];
} g_conv_fp8 = {
    16,
    {-3.2, -2.8, -2.4, -2, -1.6, -1.2, -0.8, -0.4, 0, 0.4, 0.8, 1.2, 1.6, 2, 2.4, 2.8},
    {197u, 195u, 194u, 192u, 189u, 186u, 181u, 173u, 0u, 45u, 53u, 58u, 61u, 64u, 66u, 67u},
    {-3.25, -2.75, -2.5, -2, -1.625, -1.25, -0.8125, -0.40625, 0, 0.40625, 0.8125, 1.25, 1.625, 2, 2.5, 2.75},
    {194u, 194u, 193u, 192u, 190u, 189u, 186u, 182u, 0u, 54u, 58u, 61u, 62u, 64u, 65u, 66u},
    {-3, -3, -2.5, -2, -1.5, -1.25, -0.75, -0.375, 0, 0.375, 0.75, 1.25, 1.5, 2, 2.5, 3},
};

static const struct {
    size_t length;
    float src[12];
    uint16_t f16_bits[12];
    uint8_t fp8_bits[12];
    float roundtrip[12];
} g_conv_fp8_half_bridge = {
    12,
    {-1, -0.75, -0.5, -0.25, 0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75},
    {48128u, 47616u, 47104u, 46080u, 0u, 13312u, 14336u, 14848u, 15360u, 15616u, 15872u, 16128u},
    {184u, 180u, 176u, 168u, 0u, 40u, 48u, 52u, 56u, 58u, 60u, 62u},
    {-1, -0.75, -0.5, -0.25, 0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75},
};

static const struct {
    size_t length;
    float src[12];
    uint16_t bf16_bits[12];
    uint8_t fp8_bits[12];
    float roundtrip[12];
} g_conv_fp8_bf16_bridge = {
    12,
    {0, 0.3428978075, 0.6442176872, 0.8674232256, 0.98544973, 0.9839859469, 0.8632093666, 0.6377647021, 0.3349881502,
     -0.008407247367, -0.3507832277, -0.6506251371},
    {0u, 16048u, 16165u, 16222u, 16252u, 16252u, 16221u, 16163u, 16044u, 48138u, 48820u, 48935u},
    {0u, 53u, 57u, 59u, 60u, 60u, 59u, 57u, 53u, 160u, 182u, 185u},
    {0, 0.3125, 0.625, 0.875, 1, 1, 0.875, 0.625, 0.3125, -0.0078125, -0.375, -0.625},
};

#endif // MARMOT_ENABLE_FP8

static const struct {
    size_t length;
    double src[10];
    uint16_t f16_bits[10];
    uint16_t bf16_bits[10];
    double f16_roundtrip[10];
    double bf16_roundtrip[10];
    int64_t trunc_i64[10];
} g_conv_f64_paths = {
    10,
    {-7.75, -3.9375, -2.5, -1.0625, -0.1875, 0.4375, 1.8125, 3.625, 6.75, 11.5},
    {51136u, 50144u, 49408u, 48192u, 45568u, 14080u, 16192u, 17216u, 18112u, 18880u},
    {49400u, 49276u, 49184u, 49032u, 48704u, 16096u, 16360u, 16488u, 16600u, 16696u},
    {-7.75, -3.9375, -2.5, -1.0625, -0.1875, 0.4375, 1.8125, 3.625, 6.75, 11.5},
    {-7.75, -3.9375, -2.5, -1.0625, -0.1875, 0.4375, 1.8125, 3.625, 6.75, 11.5},
    {-7, -3, -2, -1, 0, 0, 1, 3, 6, 11},
};

static const struct {
    size_t length;
    float f32_src[10];
    int64_t f32_to_i64[10];
    double f64_src[10];
    int64_t f64_to_i64[10];
    int64_t i64_src[10];
    float i64_to_f32[10];
    double i64_to_f64[10];
} g_conv_i64_bridge = {
    10,
    {-9.75, -6.5, -3.25, -1.5, -0.25, 0.75, 2.5, 4.75, 7.5, 12.25},
    {-9, -6, -3, -1, 0, 0, 2, 4, 7, 12},
    {-8.875, -5.5, -3.125, -0.875, 0.375, 1.625, 3.875, 6.25, 10.5, 15.75},
    {-8, -5, -3, 0, 0, 1, 3, 6, 10, 15},
    {-17, -9, -4, -1, 0, 1, 3, 8, 21, 37},
    {-17, -9, -4, -1, 0, 1, 3, 8, 21, 37},
    {-17, -9, -4, -1, 0, 1, 3, 8, 21, 37},
};
