// SPDX-License-Identifier: MIT
// This file was autogenerated by scripts/codegen/gen_kernels.py; DO NOT EDIT.

#ifndef MARMOT_METAL_BYTECODE_EXEC_GEN_H
#define MARMOT_METAL_BYTECODE_EXEC_GEN_H

#include <stdint.h>

#include "bytecode_tables_metal.gen.h"
#include "core/bytecode/bytecode.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const uint16_t marmot_metal_bc_imm_size[MARMOT_METAL_BC_OP_COUNT];
extern const marmot_bc_schema_id_t marmot_metal_bc_schema_id[MARMOT_METAL_BC_OP_COUNT];
extern const marmot_bc_exec_fn marmot_metal_bc_exec_table[MARMOT_METAL_BC_OP_COUNT];

#ifdef __cplusplus
}
#endif

#endif // MARMOT_METAL_BYTECODE_EXEC_GEN_H
