// SPDX-License-Identifier: MIT
// This file was autogenerated by scripts/codegen/gen_kernels.py; DO NOT EDIT.

#ifndef MARMOT_METAL_BYTECODE_TABLES_GEN_H
#define MARMOT_METAL_BYTECODE_TABLES_GEN_H

#include <stdint.h>

#define MARMOT_METAL_BC_OP_COUNT 660
#define MARMOT_METAL_BC_OP_INVALID UINT16_MAX

#endif // MARMOT_METAL_BYTECODE_TABLES_GEN_H
