// SPDX-License-Identifier: MIT
// This file was autogenerated by scripts/codegen/gen_kernels.py; DO NOT EDIT.

#ifndef MARMOT_METAL_UNARY_TABLES_GEN_H
#define MARMOT_METAL_UNARY_TABLES_GEN_H

#include "marmot/ops_types.h"
#include "marmot/types.h"

#include <stdbool.h>

#ifdef __cplusplus
#include <array>
#endif

#ifdef __cplusplus
using metal_unary_kernel_table_t = std::array<std::array<const char *, MARMOT_DEVICE_UNARY_COUNT>, MARMOT_DTYPE_COUNT>;
static const metal_unary_kernel_table_t k_metal_unary_kernel_name = []() {
    metal_unary_kernel_table_t table{};

    table[MARMOT_DTYPE_FLOAT32][MARMOT_DEVICE_UNARY_ABS] = "abs_f32";
    table[MARMOT_DTYPE_FLOAT32][MARMOT_DEVICE_UNARY_ELU] = "elu_f32";
    table[MARMOT_DTYPE_FLOAT32][MARMOT_DEVICE_UNARY_EXP] = "exp_f32";
    table[MARMOT_DTYPE_FLOAT32][MARMOT_DEVICE_UNARY_GELU] = "gelu_f32";
    table[MARMOT_DTYPE_FLOAT32][MARMOT_DEVICE_UNARY_GELU_TANH] = "gelu_tanh_f32";
    table[MARMOT_DTYPE_FLOAT32][MARMOT_DEVICE_UNARY_LEAKY_RELU] = "leaky_relu_f32";
    table[MARMOT_DTYPE_FLOAT32][MARMOT_DEVICE_UNARY_LOG] = "log_f32";
    table[MARMOT_DTYPE_FLOAT32][MARMOT_DEVICE_UNARY_MISH] = "mish_f32";
    table[MARMOT_DTYPE_FLOAT32][MARMOT_DEVICE_UNARY_NEG] = "neg_f32";
    table[MARMOT_DTYPE_FLOAT32][MARMOT_DEVICE_UNARY_PRELU] = "prelu_f32";
    table[MARMOT_DTYPE_FLOAT32][MARMOT_DEVICE_UNARY_RELU] = "relu_f32";
    table[MARMOT_DTYPE_FLOAT32][MARMOT_DEVICE_UNARY_SELU] = "selu_f32";
    table[MARMOT_DTYPE_FLOAT32][MARMOT_DEVICE_UNARY_SIGMOID] = "sigmoid_f32";
    table[MARMOT_DTYPE_FLOAT32][MARMOT_DEVICE_UNARY_SIGN] = "sign_f32";
    table[MARMOT_DTYPE_FLOAT32][MARMOT_DEVICE_UNARY_SILU] = "silu_f32";
    table[MARMOT_DTYPE_FLOAT32][MARMOT_DEVICE_UNARY_SQRT] = "sqrt_f32";
    table[MARMOT_DTYPE_FLOAT32][MARMOT_DEVICE_UNARY_TANH] = "tanh_act_f32";

    table[MARMOT_DTYPE_FLOAT16][MARMOT_DEVICE_UNARY_ABS] = "abs_f16";
    table[MARMOT_DTYPE_FLOAT16][MARMOT_DEVICE_UNARY_ELU] = "elu_f16";
    table[MARMOT_DTYPE_FLOAT16][MARMOT_DEVICE_UNARY_EXP] = "exp_f16";
    table[MARMOT_DTYPE_FLOAT16][MARMOT_DEVICE_UNARY_GELU] = "gelu_f16";
    table[MARMOT_DTYPE_FLOAT16][MARMOT_DEVICE_UNARY_GELU_TANH] = "gelu_tanh_f16";
    table[MARMOT_DTYPE_FLOAT16][MARMOT_DEVICE_UNARY_LEAKY_RELU] = "leaky_relu_f16";
    table[MARMOT_DTYPE_FLOAT16][MARMOT_DEVICE_UNARY_LOG] = "log_f16";
    table[MARMOT_DTYPE_FLOAT16][MARMOT_DEVICE_UNARY_MISH] = "mish_f16";
    table[MARMOT_DTYPE_FLOAT16][MARMOT_DEVICE_UNARY_NEG] = "neg_f16";
    table[MARMOT_DTYPE_FLOAT16][MARMOT_DEVICE_UNARY_PRELU] = "prelu_f16";
    table[MARMOT_DTYPE_FLOAT16][MARMOT_DEVICE_UNARY_RELU] = "relu_f16";
    table[MARMOT_DTYPE_FLOAT16][MARMOT_DEVICE_UNARY_SELU] = "selu_f16";
    table[MARMOT_DTYPE_FLOAT16][MARMOT_DEVICE_UNARY_SIGMOID] = "sigmoid_f16";
    table[MARMOT_DTYPE_FLOAT16][MARMOT_DEVICE_UNARY_SIGN] = "sign_f16";
    table[MARMOT_DTYPE_FLOAT16][MARMOT_DEVICE_UNARY_SILU] = "silu_f16";
    table[MARMOT_DTYPE_FLOAT16][MARMOT_DEVICE_UNARY_SQRT] = "sqrt_f16";
    table[MARMOT_DTYPE_FLOAT16][MARMOT_DEVICE_UNARY_TANH] = "tanh_act_f16";

    table[MARMOT_DTYPE_BFLOAT16][MARMOT_DEVICE_UNARY_ABS] = "abs_bf16";
    table[MARMOT_DTYPE_BFLOAT16][MARMOT_DEVICE_UNARY_ELU] = "elu_bf16";
    table[MARMOT_DTYPE_BFLOAT16][MARMOT_DEVICE_UNARY_EXP] = "exp_bf16";
    table[MARMOT_DTYPE_BFLOAT16][MARMOT_DEVICE_UNARY_GELU] = "gelu_bf16";
    table[MARMOT_DTYPE_BFLOAT16][MARMOT_DEVICE_UNARY_GELU_TANH] = "gelu_tanh_bf16";
    table[MARMOT_DTYPE_BFLOAT16][MARMOT_DEVICE_UNARY_LEAKY_RELU] = "leaky_relu_bf16";
    table[MARMOT_DTYPE_BFLOAT16][MARMOT_DEVICE_UNARY_LOG] = "log_bf16";
    table[MARMOT_DTYPE_BFLOAT16][MARMOT_DEVICE_UNARY_MISH] = "mish_bf16";
    table[MARMOT_DTYPE_BFLOAT16][MARMOT_DEVICE_UNARY_NEG] = "neg_bf16";
    table[MARMOT_DTYPE_BFLOAT16][MARMOT_DEVICE_UNARY_PRELU] = "prelu_bf16";
    table[MARMOT_DTYPE_BFLOAT16][MARMOT_DEVICE_UNARY_RELU] = "relu_bf16";
    table[MARMOT_DTYPE_BFLOAT16][MARMOT_DEVICE_UNARY_SELU] = "selu_bf16";
    table[MARMOT_DTYPE_BFLOAT16][MARMOT_DEVICE_UNARY_SIGMOID] = "sigmoid_bf16";
    table[MARMOT_DTYPE_BFLOAT16][MARMOT_DEVICE_UNARY_SIGN] = "sign_bf16";
    table[MARMOT_DTYPE_BFLOAT16][MARMOT_DEVICE_UNARY_SILU] = "silu_bf16";
    table[MARMOT_DTYPE_BFLOAT16][MARMOT_DEVICE_UNARY_SQRT] = "sqrt_bf16";
    table[MARMOT_DTYPE_BFLOAT16][MARMOT_DEVICE_UNARY_TANH] = "tanh_act_bf16";

    table[MARMOT_DTYPE_INT32][MARMOT_DEVICE_UNARY_ABS] = "abs_i32";
    table[MARMOT_DTYPE_INT32][MARMOT_DEVICE_UNARY_BITWISE_NOT] = "bitwise_not_i32";
    table[MARMOT_DTYPE_INT32][MARMOT_DEVICE_UNARY_NEG] = "neg_i32";
    table[MARMOT_DTYPE_INT32][MARMOT_DEVICE_UNARY_SIGN] = "sign_i32";

    table[MARMOT_DTYPE_INT16][MARMOT_DEVICE_UNARY_ABS] = "abs_i16";
    table[MARMOT_DTYPE_INT16][MARMOT_DEVICE_UNARY_BITWISE_NOT] = "bitwise_not_i16";
    table[MARMOT_DTYPE_INT16][MARMOT_DEVICE_UNARY_NEG] = "neg_i16";
    table[MARMOT_DTYPE_INT16][MARMOT_DEVICE_UNARY_SIGN] = "sign_i16";

    table[MARMOT_DTYPE_INT8][MARMOT_DEVICE_UNARY_ABS] = "abs_i8";
    table[MARMOT_DTYPE_INT8][MARMOT_DEVICE_UNARY_BITWISE_NOT] = "bitwise_not_i8";
    table[MARMOT_DTYPE_INT8][MARMOT_DEVICE_UNARY_NEG] = "neg_i8";
    table[MARMOT_DTYPE_INT8][MARMOT_DEVICE_UNARY_SIGN] = "sign_i8";

    table[MARMOT_DTYPE_UINT8][MARMOT_DEVICE_UNARY_ABS] = "abs_u8";
    table[MARMOT_DTYPE_UINT8][MARMOT_DEVICE_UNARY_BITWISE_NOT] = "bitwise_not_u8";
    table[MARMOT_DTYPE_UINT8][MARMOT_DEVICE_UNARY_SIGN] = "sign_u8";

    table[MARMOT_DTYPE_UINT16][MARMOT_DEVICE_UNARY_ABS] = "abs_u16";
    table[MARMOT_DTYPE_UINT16][MARMOT_DEVICE_UNARY_BITWISE_NOT] = "bitwise_not_u16";
    table[MARMOT_DTYPE_UINT16][MARMOT_DEVICE_UNARY_SIGN] = "sign_u16";

    table[MARMOT_DTYPE_UINT32][MARMOT_DEVICE_UNARY_ABS] = "abs_u32";
    table[MARMOT_DTYPE_UINT32][MARMOT_DEVICE_UNARY_BITWISE_NOT] = "bitwise_not_u32";
    table[MARMOT_DTYPE_UINT32][MARMOT_DEVICE_UNARY_SIGN] = "sign_u32";

    table[MARMOT_DTYPE_UINT64][MARMOT_DEVICE_UNARY_ABS] = "abs_u64";
    table[MARMOT_DTYPE_UINT64][MARMOT_DEVICE_UNARY_BITWISE_NOT] = "bitwise_not_u64";
    table[MARMOT_DTYPE_UINT64][MARMOT_DEVICE_UNARY_SIGN] = "sign_u64";

#if MARMOT_ENABLE_FP8

    table[MARMOT_DTYPE_FLOAT8_E4M3][MARMOT_DEVICE_UNARY_ABS] = "abs_fp8_e4m3";
    table[MARMOT_DTYPE_FLOAT8_E4M3][MARMOT_DEVICE_UNARY_ELU] = "elu_fp8_e4m3";
    table[MARMOT_DTYPE_FLOAT8_E4M3][MARMOT_DEVICE_UNARY_EXP] = "exp_fp8_e4m3";
    table[MARMOT_DTYPE_FLOAT8_E4M3][MARMOT_DEVICE_UNARY_GELU] = "gelu_fp8_e4m3";
    table[MARMOT_DTYPE_FLOAT8_E4M3][MARMOT_DEVICE_UNARY_GELU_TANH] = "gelu_tanh_fp8_e4m3";
    table[MARMOT_DTYPE_FLOAT8_E4M3][MARMOT_DEVICE_UNARY_LEAKY_RELU] = "leaky_relu_fp8_e4m3";
    table[MARMOT_DTYPE_FLOAT8_E4M3][MARMOT_DEVICE_UNARY_LOG] = "log_fp8_e4m3";
    table[MARMOT_DTYPE_FLOAT8_E4M3][MARMOT_DEVICE_UNARY_MISH] = "mish_fp8_e4m3";
    table[MARMOT_DTYPE_FLOAT8_E4M3][MARMOT_DEVICE_UNARY_NEG] = "neg_fp8_e4m3";
    table[MARMOT_DTYPE_FLOAT8_E4M3][MARMOT_DEVICE_UNARY_PRELU] = "prelu_fp8_e4m3";
    table[MARMOT_DTYPE_FLOAT8_E4M3][MARMOT_DEVICE_UNARY_RELU] = "relu_fp8_e4m3";
    table[MARMOT_DTYPE_FLOAT8_E4M3][MARMOT_DEVICE_UNARY_SELU] = "selu_fp8_e4m3";
    table[MARMOT_DTYPE_FLOAT8_E4M3][MARMOT_DEVICE_UNARY_SIGMOID] = "sigmoid_fp8_e4m3";
    table[MARMOT_DTYPE_FLOAT8_E4M3][MARMOT_DEVICE_UNARY_SIGN] = "sign_fp8_e4m3";
    table[MARMOT_DTYPE_FLOAT8_E4M3][MARMOT_DEVICE_UNARY_SILU] = "silu_fp8_e4m3";
    table[MARMOT_DTYPE_FLOAT8_E4M3][MARMOT_DEVICE_UNARY_SQRT] = "sqrt_fp8_e4m3";
    table[MARMOT_DTYPE_FLOAT8_E4M3][MARMOT_DEVICE_UNARY_TANH] = "tanh_act_fp8_e4m3";
#endif

#if MARMOT_ENABLE_FP8

    table[MARMOT_DTYPE_FLOAT8_E5M2][MARMOT_DEVICE_UNARY_ABS] = "abs_fp8_e5m2";
    table[MARMOT_DTYPE_FLOAT8_E5M2][MARMOT_DEVICE_UNARY_ELU] = "elu_fp8_e5m2";
    table[MARMOT_DTYPE_FLOAT8_E5M2][MARMOT_DEVICE_UNARY_EXP] = "exp_fp8_e5m2";
    table[MARMOT_DTYPE_FLOAT8_E5M2][MARMOT_DEVICE_UNARY_GELU] = "gelu_fp8_e5m2";
    table[MARMOT_DTYPE_FLOAT8_E5M2][MARMOT_DEVICE_UNARY_GELU_TANH] = "gelu_tanh_fp8_e5m2";
    table[MARMOT_DTYPE_FLOAT8_E5M2][MARMOT_DEVICE_UNARY_LEAKY_RELU] = "leaky_relu_fp8_e5m2";
    table[MARMOT_DTYPE_FLOAT8_E5M2][MARMOT_DEVICE_UNARY_LOG] = "log_fp8_e5m2";
    table[MARMOT_DTYPE_FLOAT8_E5M2][MARMOT_DEVICE_UNARY_MISH] = "mish_fp8_e5m2";
    table[MARMOT_DTYPE_FLOAT8_E5M2][MARMOT_DEVICE_UNARY_NEG] = "neg_fp8_e5m2";
    table[MARMOT_DTYPE_FLOAT8_E5M2][MARMOT_DEVICE_UNARY_PRELU] = "prelu_fp8_e5m2";
    table[MARMOT_DTYPE_FLOAT8_E5M2][MARMOT_DEVICE_UNARY_RELU] = "relu_fp8_e5m2";
    table[MARMOT_DTYPE_FLOAT8_E5M2][MARMOT_DEVICE_UNARY_SELU] = "selu_fp8_e5m2";
    table[MARMOT_DTYPE_FLOAT8_E5M2][MARMOT_DEVICE_UNARY_SIGMOID] = "sigmoid_fp8_e5m2";
    table[MARMOT_DTYPE_FLOAT8_E5M2][MARMOT_DEVICE_UNARY_SIGN] = "sign_fp8_e5m2";
    table[MARMOT_DTYPE_FLOAT8_E5M2][MARMOT_DEVICE_UNARY_SILU] = "silu_fp8_e5m2";
    table[MARMOT_DTYPE_FLOAT8_E5M2][MARMOT_DEVICE_UNARY_SQRT] = "sqrt_fp8_e5m2";
    table[MARMOT_DTYPE_FLOAT8_E5M2][MARMOT_DEVICE_UNARY_TANH] = "tanh_act_fp8_e5m2";
#endif

    return table;
}();

using metal_unary_vec4_kernel_table_t =
    std::array<std::array<const char *, MARMOT_DEVICE_UNARY_COUNT>, MARMOT_DTYPE_COUNT>;
static const metal_unary_vec4_kernel_table_t k_metal_unary_vec4_kernel_name = []() {
    metal_unary_vec4_kernel_table_t table{};
    table[MARMOT_DTYPE_FLOAT32][MARMOT_DEVICE_UNARY_GELU] = "gelu_f32_vec4";
    table[MARMOT_DTYPE_FLOAT32][MARMOT_DEVICE_UNARY_RELU] = "relu_f32_vec4";
    table[MARMOT_DTYPE_FLOAT32][MARMOT_DEVICE_UNARY_SILU] = "silu_f32_vec4";
    table[MARMOT_DTYPE_FLOAT16][MARMOT_DEVICE_UNARY_GELU] = "gelu_f16_vec4";
    table[MARMOT_DTYPE_FLOAT16][MARMOT_DEVICE_UNARY_RELU] = "relu_f16_vec4";
    table[MARMOT_DTYPE_FLOAT16][MARMOT_DEVICE_UNARY_SILU] = "silu_f16_vec4";
    table[MARMOT_DTYPE_BFLOAT16][MARMOT_DEVICE_UNARY_GELU] = "gelu_bf16_vec4";
    table[MARMOT_DTYPE_BFLOAT16][MARMOT_DEVICE_UNARY_RELU] = "relu_bf16_vec4";
    table[MARMOT_DTYPE_BFLOAT16][MARMOT_DEVICE_UNARY_SILU] = "silu_bf16_vec4";
    return table;
}();

using metal_unary_fused_bias_table_t = std::array<const char *, MARMOT_DTYPE_COUNT>;
static const metal_unary_fused_bias_table_t k_metal_unary_fused_bias_kernel_name = []() {
    metal_unary_fused_bias_table_t table{};
    table[MARMOT_DTYPE_FLOAT32] = "fused_bias_activation_f32";
    table[MARMOT_DTYPE_FLOAT16] = "fused_bias_activation_f16";
    table[MARMOT_DTYPE_BFLOAT16] = "fused_bias_activation_bf16";
    return table;
}();

using metal_unary_needs_params_table_t = std::array<bool, MARMOT_DEVICE_UNARY_COUNT>;
static const metal_unary_needs_params_table_t k_metal_unary_needs_params = []() {
    metal_unary_needs_params_table_t table{};
    table[MARMOT_DEVICE_UNARY_ELU] = true;
    table[MARMOT_DEVICE_UNARY_LEAKY_RELU] = true;
    table[MARMOT_DEVICE_UNARY_PRELU] = true;
    table[MARMOT_DEVICE_UNARY_SELU] = true;
    return table;
}();
#else
static const char *k_metal_unary_kernel_name[MARMOT_DTYPE_COUNT][MARMOT_DEVICE_UNARY_COUNT] = {

    [MARMOT_DTYPE_FLOAT32] =
        {
            [MARMOT_DEVICE_UNARY_ABS] = "abs_f32",
            [MARMOT_DEVICE_UNARY_ELU] = "elu_f32",
            [MARMOT_DEVICE_UNARY_EXP] = "exp_f32",
            [MARMOT_DEVICE_UNARY_GELU] = "gelu_f32",
            [MARMOT_DEVICE_UNARY_GELU_TANH] = "gelu_tanh_f32",
            [MARMOT_DEVICE_UNARY_LEAKY_RELU] = "leaky_relu_f32",
            [MARMOT_DEVICE_UNARY_LOG] = "log_f32",
            [MARMOT_DEVICE_UNARY_MISH] = "mish_f32",
            [MARMOT_DEVICE_UNARY_NEG] = "neg_f32",
            [MARMOT_DEVICE_UNARY_PRELU] = "prelu_f32",
            [MARMOT_DEVICE_UNARY_RELU] = "relu_f32",
            [MARMOT_DEVICE_UNARY_SELU] = "selu_f32",
            [MARMOT_DEVICE_UNARY_SIGMOID] = "sigmoid_f32",
            [MARMOT_DEVICE_UNARY_SIGN] = "sign_f32",
            [MARMOT_DEVICE_UNARY_SILU] = "silu_f32",
            [MARMOT_DEVICE_UNARY_SQRT] = "sqrt_f32",
            [MARMOT_DEVICE_UNARY_TANH] = "tanh_act_f32",
        },

    [MARMOT_DTYPE_FLOAT16] =
        {
            [MARMOT_DEVICE_UNARY_ABS] = "abs_f16",
            [MARMOT_DEVICE_UNARY_ELU] = "elu_f16",
            [MARMOT_DEVICE_UNARY_EXP] = "exp_f16",
            [MARMOT_DEVICE_UNARY_GELU] = "gelu_f16",
            [MARMOT_DEVICE_UNARY_GELU_TANH] = "gelu_tanh_f16",
            [MARMOT_DEVICE_UNARY_LEAKY_RELU] = "leaky_relu_f16",
            [MARMOT_DEVICE_UNARY_LOG] = "log_f16",
            [MARMOT_DEVICE_UNARY_MISH] = "mish_f16",
            [MARMOT_DEVICE_UNARY_NEG] = "neg_f16",
            [MARMOT_DEVICE_UNARY_PRELU] = "prelu_f16",
            [MARMOT_DEVICE_UNARY_RELU] = "relu_f16",
            [MARMOT_DEVICE_UNARY_SELU] = "selu_f16",
            [MARMOT_DEVICE_UNARY_SIGMOID] = "sigmoid_f16",
            [MARMOT_DEVICE_UNARY_SIGN] = "sign_f16",
            [MARMOT_DEVICE_UNARY_SILU] = "silu_f16",
            [MARMOT_DEVICE_UNARY_SQRT] = "sqrt_f16",
            [MARMOT_DEVICE_UNARY_TANH] = "tanh_act_f16",
        },

    [MARMOT_DTYPE_BFLOAT16] =
        {
            [MARMOT_DEVICE_UNARY_ABS] = "abs_bf16",
            [MARMOT_DEVICE_UNARY_ELU] = "elu_bf16",
            [MARMOT_DEVICE_UNARY_EXP] = "exp_bf16",
            [MARMOT_DEVICE_UNARY_GELU] = "gelu_bf16",
            [MARMOT_DEVICE_UNARY_GELU_TANH] = "gelu_tanh_bf16",
            [MARMOT_DEVICE_UNARY_LEAKY_RELU] = "leaky_relu_bf16",
            [MARMOT_DEVICE_UNARY_LOG] = "log_bf16",
            [MARMOT_DEVICE_UNARY_MISH] = "mish_bf16",
            [MARMOT_DEVICE_UNARY_NEG] = "neg_bf16",
            [MARMOT_DEVICE_UNARY_PRELU] = "prelu_bf16",
            [MARMOT_DEVICE_UNARY_RELU] = "relu_bf16",
            [MARMOT_DEVICE_UNARY_SELU] = "selu_bf16",
            [MARMOT_DEVICE_UNARY_SIGMOID] = "sigmoid_bf16",
            [MARMOT_DEVICE_UNARY_SIGN] = "sign_bf16",
            [MARMOT_DEVICE_UNARY_SILU] = "silu_bf16",
            [MARMOT_DEVICE_UNARY_SQRT] = "sqrt_bf16",
            [MARMOT_DEVICE_UNARY_TANH] = "tanh_act_bf16",
        },

    [MARMOT_DTYPE_INT32] =
        {
            [MARMOT_DEVICE_UNARY_ABS] = "abs_i32",
            [MARMOT_DEVICE_UNARY_BITWISE_NOT] = "bitwise_not_i32",
            [MARMOT_DEVICE_UNARY_NEG] = "neg_i32",
            [MARMOT_DEVICE_UNARY_SIGN] = "sign_i32",
        },

    [MARMOT_DTYPE_INT16] =
        {
            [MARMOT_DEVICE_UNARY_ABS] = "abs_i16",
            [MARMOT_DEVICE_UNARY_BITWISE_NOT] = "bitwise_not_i16",
            [MARMOT_DEVICE_UNARY_NEG] = "neg_i16",
            [MARMOT_DEVICE_UNARY_SIGN] = "sign_i16",
        },

    [MARMOT_DTYPE_INT8] =
        {
            [MARMOT_DEVICE_UNARY_ABS] = "abs_i8",
            [MARMOT_DEVICE_UNARY_BITWISE_NOT] = "bitwise_not_i8",
            [MARMOT_DEVICE_UNARY_NEG] = "neg_i8",
            [MARMOT_DEVICE_UNARY_SIGN] = "sign_i8",
        },

    [MARMOT_DTYPE_UINT8] =
        {
            [MARMOT_DEVICE_UNARY_ABS] = "abs_u8",
            [MARMOT_DEVICE_UNARY_BITWISE_NOT] = "bitwise_not_u8",
            [MARMOT_DEVICE_UNARY_SIGN] = "sign_u8",
        },

    [MARMOT_DTYPE_UINT16] =
        {
            [MARMOT_DEVICE_UNARY_ABS] = "abs_u16",
            [MARMOT_DEVICE_UNARY_BITWISE_NOT] = "bitwise_not_u16",
            [MARMOT_DEVICE_UNARY_SIGN] = "sign_u16",
        },

    [MARMOT_DTYPE_UINT32] =
        {
            [MARMOT_DEVICE_UNARY_ABS] = "abs_u32",
            [MARMOT_DEVICE_UNARY_BITWISE_NOT] = "bitwise_not_u32",
            [MARMOT_DEVICE_UNARY_SIGN] = "sign_u32",
        },

    [MARMOT_DTYPE_UINT64] =
        {
            [MARMOT_DEVICE_UNARY_ABS] = "abs_u64",
            [MARMOT_DEVICE_UNARY_BITWISE_NOT] = "bitwise_not_u64",
            [MARMOT_DEVICE_UNARY_SIGN] = "sign_u64",
        },

#if MARMOT_ENABLE_FP8

    [MARMOT_DTYPE_FLOAT8_E4M3] =
        {
            [MARMOT_DEVICE_UNARY_ABS] = "abs_fp8_e4m3",
            [MARMOT_DEVICE_UNARY_ELU] = "elu_fp8_e4m3",
            [MARMOT_DEVICE_UNARY_EXP] = "exp_fp8_e4m3",
            [MARMOT_DEVICE_UNARY_GELU] = "gelu_fp8_e4m3",
            [MARMOT_DEVICE_UNARY_GELU_TANH] = "gelu_tanh_fp8_e4m3",
            [MARMOT_DEVICE_UNARY_LEAKY_RELU] = "leaky_relu_fp8_e4m3",
            [MARMOT_DEVICE_UNARY_LOG] = "log_fp8_e4m3",
            [MARMOT_DEVICE_UNARY_MISH] = "mish_fp8_e4m3",
            [MARMOT_DEVICE_UNARY_NEG] = "neg_fp8_e4m3",
            [MARMOT_DEVICE_UNARY_PRELU] = "prelu_fp8_e4m3",
            [MARMOT_DEVICE_UNARY_RELU] = "relu_fp8_e4m3",
            [MARMOT_DEVICE_UNARY_SELU] = "selu_fp8_e4m3",
            [MARMOT_DEVICE_UNARY_SIGMOID] = "sigmoid_fp8_e4m3",
            [MARMOT_DEVICE_UNARY_SIGN] = "sign_fp8_e4m3",
            [MARMOT_DEVICE_UNARY_SILU] = "silu_fp8_e4m3",
            [MARMOT_DEVICE_UNARY_SQRT] = "sqrt_fp8_e4m3",
            [MARMOT_DEVICE_UNARY_TANH] = "tanh_act_fp8_e4m3",
        },
#endif

#if MARMOT_ENABLE_FP8

    [MARMOT_DTYPE_FLOAT8_E5M2] = {
        [MARMOT_DEVICE_UNARY_ABS] = "abs_fp8_e5m2",
        [MARMOT_DEVICE_UNARY_ELU] = "elu_fp8_e5m2",
        [MARMOT_DEVICE_UNARY_EXP] = "exp_fp8_e5m2",
        [MARMOT_DEVICE_UNARY_GELU] = "gelu_fp8_e5m2",
        [MARMOT_DEVICE_UNARY_GELU_TANH] = "gelu_tanh_fp8_e5m2",
        [MARMOT_DEVICE_UNARY_LEAKY_RELU] = "leaky_relu_fp8_e5m2",
        [MARMOT_DEVICE_UNARY_LOG] = "log_fp8_e5m2",
        [MARMOT_DEVICE_UNARY_MISH] = "mish_fp8_e5m2",
        [MARMOT_DEVICE_UNARY_NEG] = "neg_fp8_e5m2",
        [MARMOT_DEVICE_UNARY_PRELU] = "prelu_fp8_e5m2",
        [MARMOT_DEVICE_UNARY_RELU] = "relu_fp8_e5m2",
        [MARMOT_DEVICE_UNARY_SELU] = "selu_fp8_e5m2",
        [MARMOT_DEVICE_UNARY_SIGMOID] = "sigmoid_fp8_e5m2",
        [MARMOT_DEVICE_UNARY_SIGN] = "sign_fp8_e5m2",
        [MARMOT_DEVICE_UNARY_SILU] = "silu_fp8_e5m2",
        [MARMOT_DEVICE_UNARY_SQRT] = "sqrt_fp8_e5m2",
        [MARMOT_DEVICE_UNARY_TANH] = "tanh_act_fp8_e5m2",
    },
#endif

};

static const char *k_metal_unary_vec4_kernel_name[MARMOT_DTYPE_COUNT][MARMOT_DEVICE_UNARY_COUNT] = {
    [MARMOT_DTYPE_FLOAT32] =
        {
            [MARMOT_DEVICE_UNARY_GELU] = "gelu_f32_vec4",
            [MARMOT_DEVICE_UNARY_RELU] = "relu_f32_vec4",
            [MARMOT_DEVICE_UNARY_SILU] = "silu_f32_vec4",
        },
    [MARMOT_DTYPE_FLOAT16] =
        {
            [MARMOT_DEVICE_UNARY_GELU] = "gelu_f16_vec4",
            [MARMOT_DEVICE_UNARY_RELU] = "relu_f16_vec4",
            [MARMOT_DEVICE_UNARY_SILU] = "silu_f16_vec4",
        },
    [MARMOT_DTYPE_BFLOAT16] = {
        [MARMOT_DEVICE_UNARY_GELU] = "gelu_bf16_vec4",
        [MARMOT_DEVICE_UNARY_RELU] = "relu_bf16_vec4",
        [MARMOT_DEVICE_UNARY_SILU] = "silu_bf16_vec4",
    },
};

static const char *k_metal_unary_fused_bias_kernel_name[MARMOT_DTYPE_COUNT] = {
    [MARMOT_DTYPE_FLOAT32] = "fused_bias_activation_f32",
    [MARMOT_DTYPE_FLOAT16] = "fused_bias_activation_f16",
    [MARMOT_DTYPE_BFLOAT16] = "fused_bias_activation_bf16",
};

static const bool k_metal_unary_needs_params[MARMOT_DEVICE_UNARY_COUNT] = {
    [MARMOT_DEVICE_UNARY_ELU] = true,
    [MARMOT_DEVICE_UNARY_LEAKY_RELU] = true,
    [MARMOT_DEVICE_UNARY_PRELU] = true,
    [MARMOT_DEVICE_UNARY_SELU] = true,
};
#endif

#endif // MARMOT_METAL_UNARY_TABLES_GEN_H
