// SPDX-License-Identifier: MIT
// This file was autogenerated by scripts/codegen/gen_kernels.py; DO NOT EDIT.
// Generated from QUANT_SCHEME blocks in src/backends/metal/kernels/metadata/quant_schemes.def

#include "internal/metal_matmul_quant_dispatch.h"

#include "marmot/quant_block.h"

#include <array>

#include "metal_backend_internal.h"

#ifdef __APPLE__

// =============================================================================
// Static kernel tables for direct activation path (MV/OPT variants)
// =============================================================================

// Q4_0 (MV path)
static const metal_kquant_kernels_t k_q4_0_f32_f32 = {
    .kernel_opt = "matmul_q4_0_f32_f32_mv",
    .kernel_nr2 = "matmul_q4_0_f32_f32_mv_nr2",
    .kernel_small = "matmul_q4_0_f32_f32_small",
    .kernel_mv_ext = "matmul_q4_0_f32_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q4_0_f32_f32_mm",
    .kernel_mm16 = "matmul_q4_0_f32_f32_mm16",
};
static const metal_kquant_kernels_t k_q4_0_f16_f16 = {
    .kernel_opt = "matmul_q4_0_f16_f16_mv",
    .kernel_nr2 = "matmul_q4_0_f16_f16_mv_nr2",
    .kernel_small = "matmul_q4_0_f16_f16_small",
    .kernel_mv_ext = "matmul_q4_0_f16_f16_mv_ext_r1_4",
    .kernel_mm = "matmul_q4_0_f16_f16_mm",
    .kernel_mm16 = "matmul_q4_0_f16_f16_mm16",
};
static const metal_kquant_kernels_t k_q4_0_f16_f32 = {
    .kernel_opt = "matmul_q4_0_f16_f32_mv",
    .kernel_nr2 = "matmul_q4_0_f16_f32_mv_nr2",
    .kernel_small = "matmul_q4_0_f16_f32_small",
    .kernel_mv_ext = "matmul_q4_0_f16_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q4_0_f16_f32_mm",
    .kernel_mm16 = "matmul_q4_0_f16_f32_mm16",
};
// Q4_1 (MV path)
static const metal_kquant_kernels_t k_q4_1_f32_f32 = {
    .kernel_opt = "matmul_q4_1_f32_f32_mv",
    .kernel_nr2 = "matmul_q4_1_f32_f32_mv_nr2",
    .kernel_small = "matmul_q4_1_f32_f32_small",
    .kernel_mv_ext = "matmul_q4_1_f32_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q4_1_f32_f32_mm",
    .kernel_mm16 = "matmul_q4_1_f32_f32_mm16",
};
static const metal_kquant_kernels_t k_q4_1_f16_f16 = {
    .kernel_opt = "matmul_q4_1_f16_f16_mv",
    .kernel_nr2 = "matmul_q4_1_f16_f16_mv_nr2",
    .kernel_small = "matmul_q4_1_f16_f16_small",
    .kernel_mv_ext = "matmul_q4_1_f16_f16_mv_ext_r1_4",
    .kernel_mm = "matmul_q4_1_f16_f16_mm",
    .kernel_mm16 = "matmul_q4_1_f16_f16_mm16",
};
static const metal_kquant_kernels_t k_q4_1_f16_f32 = {
    .kernel_opt = "matmul_q4_1_f16_f32_mv",
    .kernel_nr2 = "matmul_q4_1_f16_f32_mv_nr2",
    .kernel_small = "matmul_q4_1_f16_f32_small",
    .kernel_mv_ext = "matmul_q4_1_f16_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q4_1_f16_f32_mm",
    .kernel_mm16 = "matmul_q4_1_f16_f32_mm16",
};
// Q5_0 (MV path)
static const metal_kquant_kernels_t k_q5_0_f32_f32 = {
    .kernel_opt = "matmul_q5_0_f32_f32_mv",
    .kernel_nr2 = "matmul_q5_0_f32_f32_mv_nr2",
    .kernel_small = "matmul_q5_0_f32_f32_small",
    .kernel_mv_ext = "matmul_q5_0_f32_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q5_0_f32_f32_mm",
    .kernel_mm16 = "matmul_q5_0_f32_f32_mm16",
};
static const metal_kquant_kernels_t k_q5_0_f16_f16 = {
    .kernel_opt = "matmul_q5_0_f16_f16_mv",
    .kernel_nr2 = "matmul_q5_0_f16_f16_mv_nr2",
    .kernel_small = "matmul_q5_0_f16_f16_small",
    .kernel_mv_ext = "matmul_q5_0_f16_f16_mv_ext_r1_4",
    .kernel_mm = "matmul_q5_0_f16_f16_mm",
    .kernel_mm16 = "matmul_q5_0_f16_f16_mm16",
};
static const metal_kquant_kernels_t k_q5_0_f16_f32 = {
    .kernel_opt = "matmul_q5_0_f16_f32_mv",
    .kernel_nr2 = "matmul_q5_0_f16_f32_mv_nr2",
    .kernel_small = "matmul_q5_0_f16_f32_small",
    .kernel_mv_ext = "matmul_q5_0_f16_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q5_0_f16_f32_mm",
    .kernel_mm16 = "matmul_q5_0_f16_f32_mm16",
};
// Q5_1 (MV path)
static const metal_kquant_kernels_t k_q5_1_f32_f32 = {
    .kernel_opt = "matmul_q5_1_f32_f32_mv",
    .kernel_nr2 = "matmul_q5_1_f32_f32_mv_nr2",
    .kernel_small = "matmul_q5_1_f32_f32_small",
    .kernel_mv_ext = "matmul_q5_1_f32_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q5_1_f32_f32_mm",
    .kernel_mm16 = "matmul_q5_1_f32_f32_mm16",
};
static const metal_kquant_kernels_t k_q5_1_f16_f16 = {
    .kernel_opt = "matmul_q5_1_f16_f16_mv",
    .kernel_nr2 = "matmul_q5_1_f16_f16_mv_nr2",
    .kernel_small = "matmul_q5_1_f16_f16_small",
    .kernel_mv_ext = "matmul_q5_1_f16_f16_mv_ext_r1_4",
    .kernel_mm = "matmul_q5_1_f16_f16_mm",
    .kernel_mm16 = "matmul_q5_1_f16_f16_mm16",
};
static const metal_kquant_kernels_t k_q5_1_f16_f32 = {
    .kernel_opt = "matmul_q5_1_f16_f32_mv",
    .kernel_nr2 = "matmul_q5_1_f16_f32_mv_nr2",
    .kernel_small = "matmul_q5_1_f16_f32_small",
    .kernel_mv_ext = "matmul_q5_1_f16_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q5_1_f16_f32_mm",
    .kernel_mm16 = "matmul_q5_1_f16_f32_mm16",
};
// Q8_0 (MV path)
static const metal_kquant_kernels_t k_q8_0_f32_f32 = {
    .kernel_opt = "matmul_q8_0_f32_f32_mv",
    .kernel_nr2 = "matmul_q8_0_f32_f32_mv_nr2",
    .kernel_small = "matmul_q8_0_f32_f32_small",
    .kernel_mv_ext = "matmul_q8_0_f32_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q8_0_f32_f32_mm",
    .kernel_mm16 = "matmul_q8_0_f32_f32_mm16",
};
static const metal_kquant_kernels_t k_q8_0_f16_f16 = {
    .kernel_opt = "matmul_q8_0_f16_f16_mv",
    .kernel_nr2 = "matmul_q8_0_f16_f16_mv_nr2",
    .kernel_small = "matmul_q8_0_f16_f16_small",
    .kernel_mv_ext = "matmul_q8_0_f16_f16_mv_ext_r1_4",
    .kernel_mm = "matmul_q8_0_f16_f16_mm",
    .kernel_mm16 = "matmul_q8_0_f16_f16_mm16",
};
static const metal_kquant_kernels_t k_q8_0_f16_f32 = {
    .kernel_opt = "matmul_q8_0_f16_f32_mv",
    .kernel_nr2 = "matmul_q8_0_f16_f32_mv_nr2",
    .kernel_small = "matmul_q8_0_f16_f32_small",
    .kernel_mv_ext = "matmul_q8_0_f16_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q8_0_f16_f32_mm",
    .kernel_mm16 = "matmul_q8_0_f16_f32_mm16",
};
// Q8_1 (MV path)
static const metal_kquant_kernels_t k_q8_1_f32_f32 = {
    .kernel_opt = "matmul_q8_1_f32_f32_mv",
    .kernel_nr2 = "matmul_q8_1_f32_f32_mv_nr2",
    .kernel_small = "matmul_q8_1_f32_f32_small",
    .kernel_mv_ext = "matmul_q8_1_f32_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q8_1_f32_f32_mm",
    .kernel_mm16 = "matmul_q8_1_f32_f32_mm16",
};
static const metal_kquant_kernels_t k_q8_1_f16_f16 = {
    .kernel_opt = "matmul_q8_1_f16_f16_mv",
    .kernel_nr2 = "matmul_q8_1_f16_f16_mv_nr2",
    .kernel_small = "matmul_q8_1_f16_f16_small",
    .kernel_mv_ext = "matmul_q8_1_f16_f16_mv_ext_r1_4",
    .kernel_mm = "matmul_q8_1_f16_f16_mm",
    .kernel_mm16 = "matmul_q8_1_f16_f16_mm16",
};
static const metal_kquant_kernels_t k_q8_1_f16_f32 = {
    .kernel_opt = "matmul_q8_1_f16_f32_mv",
    .kernel_nr2 = "matmul_q8_1_f16_f32_mv_nr2",
    .kernel_small = "matmul_q8_1_f16_f32_small",
    .kernel_mv_ext = "matmul_q8_1_f16_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q8_1_f16_f32_mm",
    .kernel_mm16 = "matmul_q8_1_f16_f32_mm16",
};
// Q2_K (MV path)
static const metal_kquant_kernels_t k_q2_k_f32_f32 = {
    .kernel_opt = "matmul_q2_k_f32_f32_mv",
    .kernel_nr2 = "matmul_q2_k_f32_f32_mv_nr2",
    .kernel_small = "matmul_q2_k_f32_f32_small",
    .kernel_mv_ext = "matmul_q2_k_f32_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q2_k_f32_f32_mm",
    .kernel_mm16 = "matmul_q2_k_f32_f32_mm16",
};
static const metal_kquant_kernels_t k_q2_k_f16_f16 = {
    .kernel_opt = "matmul_q2_k_f16_f16_mv",
    .kernel_nr2 = "matmul_q2_k_f16_f16_mv_nr2",
    .kernel_small = "matmul_q2_k_f16_f16_small",
    .kernel_mv_ext = "matmul_q2_k_f16_f16_mv_ext_r1_4",
    .kernel_mm = "matmul_q2_k_f16_f16_mm",
    .kernel_mm16 = "matmul_q2_k_f16_f16_mm16",
};
static const metal_kquant_kernels_t k_q2_k_f16_f32 = {
    .kernel_opt = "matmul_q2_k_f16_f32_mv",
    .kernel_nr2 = "matmul_q2_k_f16_f32_mv_nr2",
    .kernel_small = "matmul_q2_k_f16_f32_small",
    .kernel_mv_ext = "matmul_q2_k_f16_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q2_k_f16_f32_mm",
    .kernel_mm16 = "matmul_q2_k_f16_f32_mm16",
};
// Q3_K (MV path)
static const metal_kquant_kernels_t k_q3_k_f32_f32 = {
    .kernel_opt = "matmul_q3_k_f32_f32_mv",
    .kernel_nr2 = "matmul_q3_k_f32_f32_mv_nr2",
    .kernel_small = "matmul_q3_k_f32_f32_small",
    .kernel_mv_ext = "matmul_q3_k_f32_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q3_k_f32_f32_mm",
    .kernel_mm16 = "matmul_q3_k_f32_f32_mm16",
};
static const metal_kquant_kernels_t k_q3_k_f16_f16 = {
    .kernel_opt = "matmul_q3_k_f16_f16_mv",
    .kernel_nr2 = "matmul_q3_k_f16_f16_mv_nr2",
    .kernel_small = "matmul_q3_k_f16_f16_small",
    .kernel_mv_ext = "matmul_q3_k_f16_f16_mv_ext_r1_4",
    .kernel_mm = "matmul_q3_k_f16_f16_mm",
    .kernel_mm16 = "matmul_q3_k_f16_f16_mm16",
};
static const metal_kquant_kernels_t k_q3_k_f16_f32 = {
    .kernel_opt = "matmul_q3_k_f16_f32_mv",
    .kernel_nr2 = "matmul_q3_k_f16_f32_mv_nr2",
    .kernel_small = "matmul_q3_k_f16_f32_small",
    .kernel_mv_ext = "matmul_q3_k_f16_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q3_k_f16_f32_mm",
    .kernel_mm16 = "matmul_q3_k_f16_f32_mm16",
};
// Q4_K (MV path)
static const metal_kquant_kernels_t k_q4_k_f32_f32 = {
    .kernel_opt = "matmul_q4_k_f32_f32_mv",
    .kernel_nr2 = "matmul_q4_k_f32_f32_mv_nr2",
    .kernel_small = "matmul_q4_k_f32_f32_small",
    .kernel_mv_ext = "matmul_q4_k_f32_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q4_k_f32_f32_mm",
    .kernel_mm16 = "matmul_q4_k_f32_f32_mm16",
};
static const metal_kquant_kernels_t k_q4_k_f16_f16 = {
    .kernel_opt = "matmul_q4_k_f16_f16_mv",
    .kernel_nr2 = "matmul_q4_k_f16_f16_mv_nr2",
    .kernel_small = "matmul_q4_k_f16_f16_small",
    .kernel_mv_ext = "matmul_q4_k_f16_f16_mv_ext_r1_4",
    .kernel_mm = "matmul_q4_k_f16_f16_mm",
    .kernel_mm16 = "matmul_q4_k_f16_f16_mm16",
};
static const metal_kquant_kernels_t k_q4_k_f16_f32 = {
    .kernel_opt = "matmul_q4_k_f16_f32_mv",
    .kernel_nr2 = "matmul_q4_k_f16_f32_mv_nr2",
    .kernel_small = "matmul_q4_k_f16_f32_small",
    .kernel_mv_ext = "matmul_q4_k_f16_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q4_k_f16_f32_mm",
    .kernel_mm16 = "matmul_q4_k_f16_f32_mm16",
};
// Q5_K (MV path)
static const metal_kquant_kernels_t k_q5_k_f32_f32 = {
    .kernel_opt = "matmul_q5_k_f32_f32_mv",
    .kernel_nr2 = "matmul_q5_k_f32_f32_mv_nr2",
    .kernel_small = "matmul_q5_k_f32_f32_small",
    .kernel_mv_ext = "matmul_q5_k_f32_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q5_k_f32_f32_mm",
    .kernel_mm16 = "matmul_q5_k_f32_f32_mm16",
};
static const metal_kquant_kernels_t k_q5_k_f16_f16 = {
    .kernel_opt = "matmul_q5_k_f16_f16_mv",
    .kernel_nr2 = "matmul_q5_k_f16_f16_mv_nr2",
    .kernel_small = "matmul_q5_k_f16_f16_small",
    .kernel_mv_ext = "matmul_q5_k_f16_f16_mv_ext_r1_4",
    .kernel_mm = "matmul_q5_k_f16_f16_mm",
    .kernel_mm16 = "matmul_q5_k_f16_f16_mm16",
};
static const metal_kquant_kernels_t k_q5_k_f16_f32 = {
    .kernel_opt = "matmul_q5_k_f16_f32_mv",
    .kernel_nr2 = "matmul_q5_k_f16_f32_mv_nr2",
    .kernel_small = "matmul_q5_k_f16_f32_small",
    .kernel_mv_ext = "matmul_q5_k_f16_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q5_k_f16_f32_mm",
    .kernel_mm16 = "matmul_q5_k_f16_f32_mm16",
};
// Q6_K (MV path)
static const metal_kquant_kernels_t k_q6_k_f32_f32 = {
    .kernel_opt = "matmul_q6_k_f32_f32_mv",
    .kernel_nr2 = "matmul_q6_k_f32_f32_mv_nr2",
    .kernel_small = "matmul_q6_k_f32_f32_small",
    .kernel_mv_ext = "matmul_q6_k_f32_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q6_k_f32_f32_mm",
    .kernel_mm16 = "matmul_q6_k_f32_f32_mm16",
};
static const metal_kquant_kernels_t k_q6_k_f16_f16 = {
    .kernel_opt = "matmul_q6_k_f16_f16_mv",
    .kernel_nr2 = "matmul_q6_k_f16_f16_mv_nr2",
    .kernel_small = "matmul_q6_k_f16_f16_small",
    .kernel_mv_ext = "matmul_q6_k_f16_f16_mv_ext_r1_4",
    .kernel_mm = "matmul_q6_k_f16_f16_mm",
    .kernel_mm16 = "matmul_q6_k_f16_f16_mm16",
};
static const metal_kquant_kernels_t k_q6_k_f16_f32 = {
    .kernel_opt = "matmul_q6_k_f16_f32_mv",
    .kernel_nr2 = "matmul_q6_k_f16_f32_mv_nr2",
    .kernel_small = "matmul_q6_k_f16_f32_small",
    .kernel_mv_ext = "matmul_q6_k_f16_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q6_k_f16_f32_mm",
    .kernel_mm16 = "matmul_q6_k_f16_f32_mm16",
};
// Q8_K (MV path)
static const metal_kquant_kernels_t k_q8_k_f32_f32 = {
    .kernel_opt = "matmul_q8_k_f32_f32_mv",
    .kernel_nr2 = "matmul_q8_k_f32_f32_mv_nr2",
    .kernel_small = "matmul_q8_k_f32_f32_small",
    .kernel_mv_ext = "matmul_q8_k_f32_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q8_k_f32_f32_mm",
    .kernel_mm16 = "matmul_q8_k_f32_f32_mm16",
};
static const metal_kquant_kernels_t k_q8_k_f16_f16 = {
    .kernel_opt = "matmul_q8_k_f16_f16_mv",
    .kernel_nr2 = "matmul_q8_k_f16_f16_mv_nr2",
    .kernel_small = "matmul_q8_k_f16_f16_small",
    .kernel_mv_ext = "matmul_q8_k_f16_f16_mv_ext_r1_4",
    .kernel_mm = "matmul_q8_k_f16_f16_mm",
    .kernel_mm16 = "matmul_q8_k_f16_f16_mm16",
};
static const metal_kquant_kernels_t k_q8_k_f16_f32 = {
    .kernel_opt = "matmul_q8_k_f16_f32_mv",
    .kernel_nr2 = "matmul_q8_k_f16_f32_mv_nr2",
    .kernel_small = "matmul_q8_k_f16_f32_small",
    .kernel_mv_ext = "matmul_q8_k_f16_f32_mv_ext_r1_4",
    .kernel_mm = "matmul_q8_k_f16_f32_mm",
    .kernel_mm16 = "matmul_q8_k_f16_f32_mm16",
};

// =============================================================================
// Kernel table lookup by quant kind and dtype
// =============================================================================

typedef struct {
    const metal_kquant_kernels_t *f32_f32;
    const metal_kquant_kernels_t *f16_f16;
    const metal_kquant_kernels_t *f16_f32;
} metal_quant_kernel_set_t;

static const std::array<metal_quant_kernel_set_t, MARMOT_QUANT_KIND_COUNT> k_direct_kernel_sets = []() {
    std::array<metal_quant_kernel_set_t, MARMOT_QUANT_KIND_COUNT> table{};
    table[MARMOT_QUANT_KIND_Q4_0] = {
        &k_q4_0_f32_f32,
        &k_q4_0_f16_f16,
        &k_q4_0_f16_f32,
    };
    table[MARMOT_QUANT_KIND_Q4_1] = {
        &k_q4_1_f32_f32,
        &k_q4_1_f16_f16,
        &k_q4_1_f16_f32,
    };
    table[MARMOT_QUANT_KIND_Q5_0] = {
        &k_q5_0_f32_f32,
        &k_q5_0_f16_f16,
        &k_q5_0_f16_f32,
    };
    table[MARMOT_QUANT_KIND_Q5_1] = {
        &k_q5_1_f32_f32,
        &k_q5_1_f16_f16,
        &k_q5_1_f16_f32,
    };
    table[MARMOT_QUANT_KIND_Q8_0] = {
        &k_q8_0_f32_f32,
        &k_q8_0_f16_f16,
        &k_q8_0_f16_f32,
    };
    table[MARMOT_QUANT_KIND_Q8_1] = {
        &k_q8_1_f32_f32,
        &k_q8_1_f16_f16,
        &k_q8_1_f16_f32,
    };
    table[MARMOT_QUANT_KIND_Q2_K] = {
        &k_q2_k_f32_f32,
        &k_q2_k_f16_f16,
        &k_q2_k_f16_f32,
    };
    table[MARMOT_QUANT_KIND_Q3_K] = {
        &k_q3_k_f32_f32,
        &k_q3_k_f16_f16,
        &k_q3_k_f16_f32,
    };
    table[MARMOT_QUANT_KIND_Q4_K] = {
        &k_q4_k_f32_f32,
        &k_q4_k_f16_f16,
        &k_q4_k_f16_f32,
    };
    table[MARMOT_QUANT_KIND_Q5_K] = {
        &k_q5_k_f32_f32,
        &k_q5_k_f16_f16,
        &k_q5_k_f16_f32,
    };
    table[MARMOT_QUANT_KIND_Q6_K] = {
        &k_q6_k_f32_f32,
        &k_q6_k_f16_f16,
        &k_q6_k_f16_f32,
    };
    table[MARMOT_QUANT_KIND_Q8_K] = {
        &k_q8_k_f32_f32,
        &k_q8_k_f16_f16,
        &k_q8_k_f16_f32,
    };
    return table;
}();

// Scheme names for error messages
static const std::array<const char *, MARMOT_QUANT_KIND_COUNT> k_quant_scheme_names = []() {
    std::array<const char *, MARMOT_QUANT_KIND_COUNT> table{};
    table[MARMOT_QUANT_KIND_Q4_0] = "Q4_0";
    table[MARMOT_QUANT_KIND_Q4_1] = "Q4_1";
    table[MARMOT_QUANT_KIND_Q5_0] = "Q5_0";
    table[MARMOT_QUANT_KIND_Q5_1] = "Q5_1";
    table[MARMOT_QUANT_KIND_Q8_0] = "Q8_0";
    table[MARMOT_QUANT_KIND_Q8_1] = "Q8_1";
    table[MARMOT_QUANT_KIND_Q2_K] = "Q2_K";
    table[MARMOT_QUANT_KIND_Q3_K] = "Q3_K";
    table[MARMOT_QUANT_KIND_Q4_K] = "Q4_K";
    table[MARMOT_QUANT_KIND_Q5_K] = "Q5_K";
    table[MARMOT_QUANT_KIND_Q6_K] = "Q6_K";
    table[MARMOT_QUANT_KIND_Q8_K] = "Q8_K";
    return table;
}();

// =============================================================================
// Unified dispatch for direct activation path
// =============================================================================

static marmot_error_t metal_matmul_quant_dispatch_direct_path(
    metal_context_t *ctx, marmot_quant_kind_t quant_kind, marmot_dtype_t input_dtype, marmot_dtype_t output_dtype,
    const marmot_tensor_t *input, const marmot_tensor_t *weight, marmot_tensor_t *out, size_t N, size_t K, size_t M,
    size_t weight_blocks_per_row, const marmot_matmul_epilogue_t *epilogue, size_t ep_feature_dim, bool ep_bias_scalar,
    const marmot_rope_params_t *rope
) {
    const metal_quant_kernel_set_t *set = &k_direct_kernel_sets[quant_kind];
    const char *scheme_name = k_quant_scheme_names[quant_kind];
    const metal_kquant_kernels_t *kernels = nullptr;

    if (input_dtype == MARMOT_DTYPE_FLOAT32) {
        if (output_dtype != MARMOT_DTYPE_FLOAT32) {
            char msg[128];
            snprintf(
                msg, sizeof(msg), "Quantized matmul requires FLOAT32 output for FLOAT32 activations on %s", scheme_name
            );
            marmot_set_error(MARMOT_ERROR_UNSUPPORTED_DTYPE, msg);
            return MARMOT_ERROR_UNSUPPORTED_DTYPE;
        }
        kernels = set->f32_f32;
    } else if (input_dtype == MARMOT_DTYPE_FLOAT16) {
        kernels = (output_dtype == MARMOT_DTYPE_FLOAT16) ? set->f16_f16 : set->f16_f32;
    } else {
        char msg[128];
        snprintf(msg, sizeof(msg), "Quantized matmul requires FLOAT32/FLOAT16 activations for %s", scheme_name);
        marmot_set_error(MARMOT_ERROR_UNSUPPORTED_DTYPE, msg);
        return MARMOT_ERROR_UNSUPPORTED_DTYPE;
    }

    if (kernels == nullptr) {
        marmot_set_error(MARMOT_ERROR_NOT_IMPLEMENTED, "Direct activation path not available for this quant kind");
        return MARMOT_ERROR_NOT_IMPLEMENTED;
    }

    return metal_matmul_quant_dispatch_k_direct(
        ctx, kernels, scheme_name, input, weight, out, N, K, M, weight_blocks_per_row, epilogue, ep_feature_dim,
        ep_bias_scalar, rope
    );
}

// =============================================================================
// Special case handlers for schemes without direct activation path
// =============================================================================

// =============================================================================
// Main dispatch - routes to unified direct path or special handlers
// =============================================================================

marmot_error_t metal_matmul_quantized_dispatch(
    metal_context_t *ctx, marmot_quant_kind_t quant_kind, marmot_dtype_t input_dtype, marmot_dtype_t output_dtype,
    const marmot_tensor_t *input, const marmot_tensor_t *weight, marmot_tensor_t *out, size_t N, size_t K, size_t M,
    size_t weight_blocks_per_row, bool uses_super_blocks, const marmot_matmul_epilogue_t *epilogue,
    size_t ep_feature_dim, bool ep_bias_scalar, const marmot_rope_params_t *rope
) {
    (void)uses_super_blocks;
    // Fast path: schemes with direct activation support use unified dispatch
    if ((size_t)quant_kind < MARMOT_QUANT_KIND_COUNT && k_direct_kernel_sets[quant_kind].f32_f32 != nullptr) {
        return metal_matmul_quant_dispatch_direct_path(
            ctx, quant_kind, input_dtype, output_dtype, input, weight, out, N, K, M, weight_blocks_per_row, epilogue,
            ep_feature_dim, ep_bias_scalar, rope
        );
    }

    marmot_set_error(MARMOT_ERROR_NOT_IMPLEMENTED, "Quantized matmul not implemented for this quant kind on Metal");
    return MARMOT_ERROR_NOT_IMPLEMENTED;
}

#endif // __APPLE__
