#!/usr/bin/env python3
"""
Generate ops_schema_gen.py from ops.def.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any, Dict, Iterable, List, Set

import def_parser
from codegen_base import write_output, write_stamp


_OP_ID_CATEGORIES = {"binary", "reduction", "ternary", "unary"}
_QUANTIZE_SIGNATURES = {"quantize_generic", "quantize_fixed_kind"}


def _raise_missing(op_def: def_parser.BlockDef, key: str) -> None:
    offset = op_def.field_offsets.get(key, op_def.offset)
    def_parser._raise_with_location(
        f"Operation '{op_def.name}' missing required field '{key}'",
        path=op_def.path,
        content=op_def.source,
        offset=offset,
    )


def _require(fields: Dict[str, Any], op_def: def_parser.BlockDef, key: str) -> Any:
    if key not in fields:
        _raise_missing(op_def, key)
    return fields[key]


def _op_id_to_name(op_id: str) -> str:
    prefix = "MARMOT_OP_"
    if not op_id.startswith(prefix):
        raise ValueError(f"Unexpected op id '{op_id}'")
    return op_id[len(prefix) :].lower()


def _collect_ops(paths: Iterable[Path]) -> Dict[str, Set[str]]:
    mod = def_parser.parse_def_files(paths)
    sets: Dict[str, List[Any]] = {}
    for name, s in mod.sets.items():
        sets[name] = def_parser._expand_set(mod.sets, name, stack=[], path=s.path, source=s.source)
    fragments = def_parser._resolve_fragments(mod, sets)
    ctx = def_parser._ResolvedContext(path=Path("<ops.def>"), source="", sets=sets, fragments=fragments, quant_schemes={})

    ops_by_category: Dict[str, Set[str]] = {name: set() for name in _OP_ID_CATEGORIES}
    ops_by_category["convert"] = set()
    quantize_present = False
    compute_qparams_present = False
    convert_present = False

    for name, op_def in mod.operations.items():
        fields_expr = def_parser._resolve_block_fields(mod.operations, name, kind="operation", stack=[])
        fields: Dict[str, Any] = {}
        for key, expr in fields_expr.items():
            fields[key] = def_parser._eval_expr(expr, {}, ctx)

        if fields.get("ALIAS_OF") is not None:
            continue

        category = str(_require(fields, op_def, "CATEGORY")).lower()
        api_signature = str(_require(fields, op_def, "API_SIGNATURE")).lower()

        if category in _OP_ID_CATEGORIES:
            op_id = str(_require(fields, op_def, "OP_ID"))
            ops_by_category[category].add(_op_id_to_name(op_id))
            continue

        if category == "convert":
            op_id = fields.get("OP_ID")
            if op_id is not None:
                ops_by_category["convert"].add(_op_id_to_name(str(op_id)))
                convert_present = True
            continue

        if category == "quantize":
            if api_signature in _QUANTIZE_SIGNATURES:
                quantize_present = True
            if api_signature == "compute_quant_params":
                compute_qparams_present = True

    if not convert_present:
        raise SystemExit("Missing convert op definition in ops.def")
    if not compute_qparams_present:
        raise SystemExit("Missing compute_quant_params op definition in ops.def")

    ops_by_category["quantize"] = {"quantize"} if quantize_present else set()
    ops_by_category["dequantize"] = {"dequantize"} if quantize_present else set()
    ops_by_category["compute_qparams"] = {"compute_quant_params"}
    return ops_by_category


def _render_set(name: str, values: Iterable[str]) -> str:
    items = sorted(values)
    if not items:
        return f"{name} = set()\n"
    lines = [f"{name} = {{"]
    for item in items:
        lines.append(f'    "{item}",')
    lines.append("}\n")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate ops_schema_gen.py from ops.def")
    parser.add_argument("--ops-def", required=True, type=Path, help="ops.def path")
    parser.add_argument("--metadata-def", type=Path, help="Optional ops metadata .def path")
    parser.add_argument("--output", required=True, type=Path, help="Output python module path")
    parser.add_argument("--stamp-output", type=Path)
    args = parser.parse_args()

    paths = [args.ops_def]
    if args.metadata_def is not None:
        paths.append(args.metadata_def)

    ops_by_category = _collect_ops(paths)
    content = (
        "# SPDX-License-Identifier: MIT\n"
        "# This file was autogenerated by scripts/codegen/gen_ops_schema.py; DO NOT EDIT.\n\n"
        "from __future__ import annotations\n\n"
    )
    content += _render_set("BINARY_OPS", ops_by_category.get("binary", set()))
    content += _render_set("UNARY_OPS", ops_by_category.get("unary", set()))
    content += _render_set("TERNARY_OPS", ops_by_category.get("ternary", set()))
    content += _render_set("REDUCTION_OPS", ops_by_category.get("reduction", set()))
    content += _render_set("CONVERT_OPS", ops_by_category.get("convert", set()))
    content += _render_set("QUANTIZE_OPS", ops_by_category.get("quantize", set()))
    content += _render_set("DEQUANTIZE_OPS", ops_by_category.get("dequantize", set()))
    content += _render_set("COMPUTE_QPARAMS_OPS", ops_by_category.get("compute_qparams", set()))
    content += (
        "__all__ = [\n"
        '    "BINARY_OPS",\n'
        '    "UNARY_OPS",\n'
        '    "TERNARY_OPS",\n'
        '    "REDUCTION_OPS",\n'
        '    "CONVERT_OPS",\n'
        '    "QUANTIZE_OPS",\n'
        '    "DEQUANTIZE_OPS",\n'
        '    "COMPUTE_QPARAMS_OPS",\n'
        "]\n"
    )

    write_output(args.output, content)
    if args.stamp_output:
        write_stamp(args.stamp_output)


if __name__ == "__main__":
    main()
