# SPDX-License-Identifier: MIT
# This file was autogenerated by scripts/codegen/gen_ops_schema.py; DO NOT EDIT.

from __future__ import annotations

BINARY_OPS = {
    "add",
    "add_gelu",
    "add_relu",
    "add_silu",
    "bitwise_and",
    "bitwise_or",
    "bitwise_shl",
    "bitwise_shr",
    "bitwise_shr_logical",
    "bitwise_xor",
    "compare_eq",
    "compare_ge",
    "compare_gt",
    "compare_le",
    "compare_lt",
    "compare_ne",
    "div",
    "geglu",
    "max",
    "min",
    "mod",
    "mul",
    "pow",
    "sub",
    "swiglu",
}
UNARY_OPS = {
    "abs",
    "bitwise_not",
    "elu",
    "exp",
    "gelu",
    "gelu_tanh",
    "leaky_relu",
    "log",
    "mish",
    "neg",
    "prelu",
    "relu",
    "selu",
    "sigmoid",
    "sign",
    "silu",
    "sqrt",
    "tanh",
}
TERNARY_OPS = {
    "fma",
    "where",
}
REDUCTION_OPS = {
    "reduction_all",
    "reduction_any",
    "reduction_argmax",
    "reduction_argmin",
    "reduction_max",
    "reduction_mean",
    "reduction_min",
    "reduction_norm_l1",
    "reduction_norm_l2",
    "reduction_prod",
    "reduction_std",
    "reduction_sum",
    "reduction_variance",
}
CONVERT_OPS = {
    "convert",
}
QUANTIZE_OPS = {
    "quantize",
}
DEQUANTIZE_OPS = {
    "dequantize",
}
COMPUTE_QPARAMS_OPS = {
    "compute_quant_params",
}
__all__ = [
    "BINARY_OPS",
    "UNARY_OPS",
    "TERNARY_OPS",
    "REDUCTION_OPS",
    "CONVERT_OPS",
    "QUANTIZE_OPS",
    "DEQUANTIZE_OPS",
    "COMPUTE_QPARAMS_OPS",
]
